### ISSUE TITLE
Audio crackled/stuttered while playing Song 55, 109 and 121

### ISSUE THREAD

**Issue by EfrenAvilaJr** [AntonyCorbett/OnlyM#103]
We use a HP computer And a Surface pro 4 (backup) for our KH media, today halfway through the songs (mp4) the songs  we lost audio for a a very brief moment. it happened on both machines.

I tried it at home with Surface and the issue is still there. I tried Soundbox and it worked perfectly.

We use a HDMI cable to a HDMI switcher then from the switcher a 3.5" audio cable to our mixer, HDMI out to 2 TV monitors.
Settings on OnlyM: Rendering engine is Ffmpeg (Media Foundation doesn't work at all), versions were 1.1.0.8 and then 1.1.0.23 (same issue with both).
Windows 10 Pro 1803 i5 2.3Ghz 800 GB
Attached is the log file
[log-20181111.txt](https://github.com/AntonyCorbett/OnlyM/files/2570041/log-20181111.txt)

**Comment by AntonyCorbett** [comment]
@EfrenAvilaJr The ffmpeg engine relies on CPU for decoding of video and audio streams which means it is susceptible to dropout if other applications or services draw on the CPU. If Media Foundation doesn't work then the wrong video driver is installed. Update the video driver by downloading and installing from the manufacturer’s website (rather than relying on Windows to update the driver). The Media Foundation engine offloads the decoding function to the graphics card.

**Comment by EfrenAvilaJr** [comment]
@AntonyCorbett Thank you for responding . I just upgraded the video driver to the latest version (25.20.100.6373) to no avail, Media Foundation rendering still doesn't work. We'll just have to continue to use Ffmpeg for now. Any plans to possibly use VLC as Soundbox did???

Once again Anthony thx

**Comment by AntonyCorbett** [comment]
@EfrenAvilaJr No plans for VLC support. I've not known Media Foundation to fail except on machines with outdated or misconfigured drivers. It would be _very_ unusual for a mainstream system to lack support for this basic rendering mode. Having said that, it looks like you have installed the latest driver (but best to check which driver the OEM recommends).

**Comment by EfrenAvilaJr** [comment]
It sure is uncommon, I have tried on 3 other KH computers same result 😞. I guess we'll have to limit or use of OnlyM to pictures.

Thx Anthony

**Comment by timjobutler** [comment]
@EfrenAvilaJr May I ask a simple question? Have you tried playing these songs using JW Library and if so, was the issue still present?

**Comment by EfrenAvilaJr** [comment]
JWL and Soundbox both work without any issues. We wanted to use OnlyM as our go to Media player, instead of using two, now we'll use JWL for songs/videos and OnlyM for pictures and videos not available in JWL 😎.

**Comment by timjobutler** [comment]
@EfrenAvilaJr JW Library is the primary media player as directed by the organisation. Programs like OnlyM or VLC are used to fill the void to display media not available in JW Library.

**Comment by EfrenAvilaJr** [comment]
@timjobutler it is the recommended media player your correct my brother. But with the technical limitations our A/V brothers have in our congregation, simplifying things works best to not affect the quality and purpose of the spiritual food.

Thx for the reminder 😎
