### ISSUE TITLE
Subtitle Error

### ISSUE THREAD

**Issue by jsquiggz** [AntonyCorbett/OnlyM#105]
Hi,

When using the subtitles on Song 84 (Childrens version for meeting of Dec 17-23) each set of subtitles is preceded by {\an7} throughout the video. 

Thanks for your hardwork on these apps.

Jon

![2018-11-12](https://user-images.githubusercontent.com/41520698/48364312-ffc3a300-e69f-11e8-8038-f657955938ce.png)

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@jsquiggz Thanks. The codes are ASS tags (not standard srt), but many players support some of them. I will modify OnlyM to remove the codes.

**Comment by AntonyCorbett** [comment]
@jsquiggz Fixed

**Comment by jsquiggz** [comment]
Great. Thank you so much!!!

**Comment by talkingdragon** [comment]
Hi. Question to you @jsquiggz …
Were you get the sub file? when I had a look on the website I couldn't find it.. 😅

**Comment by jsquiggz** [comment]
Hi,

I downloaded them from tv.jw.org. i have ticked the "display subtitles when
available" box.
