### ISSUE TITLE
Unable to display Images

### ISSUE THREAD

**Issue by rydlo98** [AntonyCorbett/OnlyM#108]
Our Kingdom Hall is sharing a media computer with multiple accounts, each account is using OnlyM,(along with JW Library)  but we have noticed that we are unable to drag and drop pictures. When we try to drag and drop an image, the cursor changes to the invalid symbol. We are to, however, drag and drop video. We tried moving the image directly to the media folder, but it does not appear in OnlyM. 
This issue appears to only be happening on the Kingdom Hall's PC, as I have downloaded a copy of OnlyM and I did not find this issue. 
Please let me know if there is anything we could to do to resolve this issue.

**Comment by AntonyCorbett** [comment]
@rydlo98 I suspect that the image is either not supported or you are copying a shortcut of the image. Please send me one of the images after you have copied it into the media folder and confirmed it doesn't appear in OnlyM.

**Comment by rydlo98** [comment]
This is one of the images that does not appear in OnlyM. 
![image](https://user-images.githubusercontent.com/28401892/48512247-07fa1a80-e827-11e8-8b2b-9158c49604a8.png) As a side note, I did some more testing last night, and I am able to copy images directly from a USB drive, just not images that have been downloaded and are stored on the system.

**Comment by AntonyCorbett** [comment]
@rydlo98 all works fine here. As a test, please right-click on the above image, select "Save As" and store the image in your Documents\OnlyM\Media  folder. Let me know if OnlyM can display the image.

**Comment by TizianoNoto** [comment]
As a frequent user of drag-and-drop, I stumbled upon the invalid symbol a couple of times, usually because one of the applications were running with administrative privileges or did not have enough permissions t access the folder. Where are the downloaded files stored?

**Comment by TizianoNoto** [comment]
I'd also check if the NTFS permissions for the source folder/files are ok. @rydlo98 What folder are your files stored?

**Comment by rydlo98** [comment]
Apologizes for the late response. The files were stored in the downloads folder, in the default location (C:\users\$username\downloads). I did some more testing and got it to work, I had to view the image in a new tab, and download them from that screen. Before, I was going through google images, and right-clicking on the images and clicking on "Save-As". I do remember reading somethings about google images changing the way you could download images. So it might be that.

**Comment by TizianoNoto** [comment]
@rydlo98 Yes, Google does that on purpose. They now want you to open the webpage that contains the image to avoid problems with site owners.

Make sure you have permission to use the images if they're copyrighted ;-)

**Comment by lennydance** [comment]
I am having the same problem.  I was able to use it the first day I downloaded OnlyM last Sunday.  Today we ran a test to show some additional brothers how to use OnlyM and the app comes up and works as expected but nothing appears on secondary monitors. Using the same pics we used last Sunday. Microsoft did have an update since last meeting not sure that this is the issue.

Any help is appreciated.

**Comment by AntonyCorbett** [comment]
@lennydance please send the log file corresponding to the date of the problem. See wiki for details.

**Comment by MorrieB** [comment]
I had the same problem but discovered that the monitor setting had
defaulted to the primary display. Correcting that sorted my problem.

**Comment by lennydance** [comment]
Please find log files attached.  @MorrieB I checked display settings on the computer and all is correct on that.  The JW Library app recognizes the proper display and is functioning properly.

Thanks.
[log-20190120.txt](https://github.com/AntonyCorbett/OnlyM/files/2799366/log-20190120.txt)
[log-20190125.txt](https://github.com/AntonyCorbett/OnlyM/files/2799367/log-20190125.txt)
[log-20190126.txt](https://github.com/AntonyCorbett/OnlyM/files/2799368/log-20190126.txt)

**Comment by lennydance** [comment]
@MorrieB I finally found the setting you were talking about.  I was looking at computer settings but you were addressing app settings.  I set the monitor to the correct one and restarted and it works like it did originally.  Not sure why it worked perfectly when I first started the app, since I had not touched that setting.  It was so plug and play.  But no matter.  Issue resolved.
