### ISSUE TITLE
Countdown Clock for 2nd Monitor

### ISSUE THREAD

**Issue by ksl64** [AntonyCorbett/OnlyM#11]
Is it possible to have a countdown clock for the second monitor? OnlyT works for the 3trd monitor. but it would be good to have it in OnlyM for the 2nd monitor since it helps us start the meeting on time, it also helps everyone to be seated before the meeting begins.

**Comment by AntonyCorbett** [comment]
@ksl64 Current direction is to display the year text on media monitors before and after the meeting (ie the JWL background). See https://github.com/AntonyCorbett/OnlyT/issues/64
