### ISSUE TITLE
Slide shows feature

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#110]
Hi Anthony,
Will you consider to add the Slide Shows feature like it was in SoundBox or something similar?
I'm currently use it at the end of the meeting to display the cleaning group and year text in continuous rolling mode (10 seconds per each slide).
Also we used it on the memorial to display some images with the new world at the end of the meeting.
I know that other congregations are using this feature too but it's up to you if this will be added or not.
Thanks.

**Comment by AntonyCorbett** [comment]
@LvDaniel Yes. All the framework is ready and it's actually in use for OnlyV content. If you want to experiment you can create an OnlyM slideshow file by dragging and dropping from OnlyV. Then rename the ".omslide" file to ".zip", and extract. You will see the format used and can manually create slideshows if you want. Eventually I will create a slideshow editor.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks, it's looking good.
Do you know if there is/will be implemented a "Play" button like in SoundBox that starts a continuous rolling display of images that automatically transition every 8 seconds?

**Comment by AntonyCorbett** [comment]
@LvDaniel Sorry, I don't have a work schedule for this project. Although, as I say above you can create such a rolling slideshow already with a little effort.

**Comment by LvDaniel** [comment]
No worries I'll manually create the slides, but can I make them to automatically transition from one to another and create a loop? If that's possible it's perfect, I just need to see how to do it.

**Comment by AntonyCorbett** [comment]
@LvDaniel Yes, automatic loop with timed interval is possible. Please let me know if you need any help.

**Comment by AntonyCorbett** [comment]
@LvDaniel Hint - When modifying config.json, change the "AutoPlay" property to true, "Loop" to true, "DwellTimeMilliseconds" to 8000 (for 8 sec interval).
