### ISSUE TITLE
Automatically stop the rolling slides

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#112]
This is not an important feature, but if the effort is not too great will be a nice to have.
Automatically stop the loop rolling slides after an amount of time and return the screen to JWL.

**Comment by LvDaniel** [comment]
@mbrakutt1 that's a good ideea, especially with the mp4 file which stops automatically and returns the screen to JWL.
Thanks, I think we can close this thread.

**Comment by TizianoNoto** [comment]
@mbrakutt1 Note that .GIF files only use 256 colours which is not good for photos or pictures with a lot of gradients. Video is the best choice for a custom slideshow.

(@LvDaniel You can try hacking the slideshow file to disable the loop option with the help of 7-Zip. Only if you know what you're doing.)
