### ISSUE TITLE
Assembly Hall

### ISSUE THREAD

**Issue by Luiz-Alphamicro** [AntonyCorbett/OnlyM#12]
I am Audio and Video coordinator of the Assembly Hall of Vargem Grande Paulista, one of the more than 20 that we have in Brazil.

Would it be possible to make changes or another version in the OnlyM program so that we could use it in Assemblies and conventions?

Maybe separated by language, event, and  day for media .

Thank you

**Comment by AntonyCorbett** [comment]
@Luiz-Alphamicro Thanks for your interest in OnlyM for assembly use. There are several options. Perhaps the easiest is to to create a number of folders for each of the languages, days, etc and then just select the relevant one in the Settings.

**Comment by AntonyCorbett** [comment]
@Luiz-Alphamicro Implemented folder selection and drop-down list of recently-used folders

**Comment by regtec** [comment]
Boa tarde.
Irmão Antony, seria interessante se houvesse uma opção de o programa ler as subpastas, e na tela principal, aparacer como opção para alterar.
Ex: 
C:\Users\*****\Documents\OnlyM\Media\Sexta
C:\Users\*****\Documents\OnlyM\Media\Sábado
C:\Users\*****\Documents\OnlyM\Media\Domngo

E na tela principal aparecer os nomes como: Sexta, Sábado. Domingo.

![image](https://user-images.githubusercontent.com/39920734/40931499-bc3de7ac-6801-11e8-846f-a46251cb796e.png)

**Comment by regtec** [comment]
Seria interessante algo assim:
O programa ler as subpastas, e listar respectivamente:
Exemplo: 
C:\Users\reginaldo\Documents\OnlyM\Media\Sexta
C:\Users\reginaldo\Documents\OnlyM\Media\Sábado
C:\Users\reginaldo\Documents\OnlyM\Media\Domingo

![image](https://user-images.githubusercontent.com/39920734/40931654-33fde8dc-6802-11e8-95a7-3f5c7751e603.png)
