### ISSUE TITLE
Prevent mouse cursor on the media display

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#131]
This is not a feature request nor a bug report. Just wanted to get some feedback on the problem in subject.

As you may know, unlike SoundBox, JW Library allows system mouse cursor on the media display. 
Normally we don't want this to happen and distract audience's attention.
Is there any 3rd party software that you're using it to prevent this like "Dual Monitor Tools" or something similar or you just train the AV operators to be careful when handling the mouse during the meetings?
Thanks for your input.

**Comment by AntonyCorbett** [comment]
@LvDaniel there are a number of free tools that allow you to restrict mouse movement to your primary display (along with a quick key combination to free it up if required). I've not used any though.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for feedback.
