### ISSUE TITLE
Audio files not appearing or dragging into ONLYM

### ISSUE THREAD

**Issue by NorthwichVerdinPark** [AntonyCorbett/OnlyM#133]
**Describe the bug**

THE BUG 
Tried adding a WAV FILE (.wav) and an M4A FILE (.m4a) but it hasn’t worked. The files appear in the media folder but not on the application. 

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@NorthwichVerdinPark Both audio formats added in latest pre-release (1.2.0.8)
