### ISSUE TITLE
Proper key frames handling

### ISSUE THREAD

**Issue by optisamit** [AntonyCorbett/OnlyM#135]
Sometimes we show cut videos. And sometimes (depending on how exactly the video was cut - software, ffmpeg params etc) the video can start not with an `I-frame`, but with a `P-frame`. Video players like VLC handle this situation correctly: start with audio only and then display video as soon as they encounter first `I-frame`. OnlyM, on the other side, runs audio from the beginning and video starting *directly* from the first `I-frame`. The result is that video will outrun audio.
Can this be fixed please?

**Comment by AntonyCorbett** [comment]
@optisamit I have no control over the audio and video streams at a low level. The video players used (MediaFoundation and ffmpeg) simply take the relevent file as input parameter. There are several configuration options but AFAIK no means of compensating in the way you describe.

**Comment by optisamit** [comment]
I'm sure there should be a solution. If current players don't support it, maybe we can switch to another one eventually. But just in case a willing contributor finds the way to fix this - could you please leave this issue open?

**Comment by AntonyCorbett** [comment]
@optisamit I'll leave this open for a while, but I could do with some documentation / reading material so I draw up a proper set of requirements for it. If you can send me some references that would be helpful. Also if you know of any published media that demonstrates the issue that would be good.

**Comment by AntonyCorbett** [comment]
As far as an OnlyM solution is concerned I imagine it would be a matter of detecting the condition and then fixing the file using ffmpeg.

**Comment by optisamit** [comment]
It can be done, but not everyone even knows what the issue is. I'm a programmer and it took me a couple of misaligned videos on meetings to understand what's going on. And today I've downloaded a video with public talk from stream.jw.org and found out that it was trimmed improperly, too. The difference is not significant in this specific case, but it is still a potential problem. I understand that the issue lies in file, but the current way of handling it is faulty as well, technically speaking.

**Comment by optisamit** [comment]
While reproducing this issue I've found another one (infinite preloader instead of play button). I'd like to share a video file with you, but it's not public. Could you please give me an email where I can send the video?

**Comment by AntonyCorbett** [comment]
@optisamit 

>  I've found another one (infinite preloader instead of play button). 

Is it related to the current issue? If not please would you add a new issue and then I'll clean up the comments here. 

Thanks, Antony

**Comment by AntonyCorbett** [comment]
@optisamit I'm closing the issue for now as I really need an example as described above. Please feel free to reopen the issue if you have further information. Thanks for your feedback.
