### ISSUE TITLE
Thumbnail keep the aspect ratio

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#137]
Would be nice if the thumbnail of the image would have the same aspect ratio as the image itself.
Image below (2 noe) has ~15:9 ratio not ~17:9 as you might think if you consider OnlyM thumbnail.

Comparison with SoundBox which is accurate.
![image](https://user-images.githubusercontent.com/45002147/49704484-5cbd6500-fc1c-11e8-9d37-d2719072fbbd.png)

**Comment by AntonyCorbett** [comment]
@LvDaniel I'm not sure I understand the issue here. Both image thumbnails have the same aspect ratio.

**Comment by LvDaniel** [comment]
@AntonyCorbett sorry I wasn't to clear. You're right, the ratio isn't changed but I was expecting to have those black lines on the left & right not on the top & bottom, 
The thumbnail should look like how the image would be displayed to a 16:9 screen.

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks for clarification. So the request is that the OnlyM thumbnail border should have 16:9 aspect ratio. Can I suggest you create another issue please?

**Comment by LvDaniel** [comment]
Sure, I will and close this one. Thanks.
