### ISSUE TITLE
OnlyM thumbnail border to have 16:9 aspect ratio

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#139]
@AntonyCorbett This would be helpful as the thumbnail will look exactly as the image displayed on the screen. Thank you.

**Comment by AntonyCorbett** [comment]
> the thumbnail will look exactly as the image displayed on the screen.

@LvDaniel Not necessarily - it depends on the aspect ratio of the monitor and on any applied margins.

**Comment by LvDaniel** [comment]
@AntonyCorbett true, but I think most of us use 16:9 monitors.

**Comment by AntonyCorbett** [comment]
@LvDaniel I don't think this will ever be important enough to change. I understand the request and am always hesitant to turn down good ideas, but I need to be pragmatic too. Thanks for your continuing help and please keep the idea flowing!

**Comment by LvDaniel** [comment]
@richfrantz the image will be as it is, won't be changed. Just the border will be 16:9. Now the border has ~14:9 format.

**Comment by LvDaniel** [comment]
@AntonyCorbett you may have right. It's just a nice to have as most of the content is in 16:9 format. For me makes sense, but  I respect your decision. Thanks also.
