### ISSUE TITLE
A video won't play. Infinite progress bar

### ISSUE THREAD

**Issue by optisamit** [AntonyCorbett/OnlyM#141]
The video can be played with different players.
I can send you the video, but it cannot be publicly available. Please give me an e-mail to share it with. Thank you.

**Comment by AntonyCorbett** [comment]
Please open a ticket here:

https://soundbox.on.spiceworks.com/portal

It's only available to SoundBox techies.

**Comment by optisamit** [comment]
Done. Ticket #3487

**Comment by AntonyCorbett** [comment]
@optisamit Thanks. The library that I am using to read the video file metadata chokes on the Bulgarian(?) characters used in the file name. If you change the filename to "Test.mp4" all works ok. I will investigate.

**Comment by AntonyCorbett** [comment]
Now fixed, so should be available in next pre-release / release
