### ISSUE TITLE
playback position

### ISSUE THREAD

**Issue by namcir** [AntonyCorbett/OnlyM#150]
please brother can you add a feature remember video playback position when stopped so it will be easy to resume playback when accidentally stop
and when paused the video can be hidden on the screen monitor. thank you

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AntonyCorbett** [comment]
@namcir thanks for your suggestions. Please would add a single issue per request?
