### ISSUE TITLE
Scheduled activity

### ISSUE THREAD

**Issue by defran02** [AntonyCorbett/OnlyM#158]
Our congregation loved having the countdown clock in SoundBox. This week we officially migrated to WTL and OnlyM. Right away the friends missed our countdown clock. 

We have found a 5 min countdown video that we like.
Could we request an auto play or scheduled activation of a specific piece of media?
Or...could we incorporate a countdown function?

Many thanks for all your efforts.

**Comment by timjobutler** [comment]
@defran02 Please install OnlyT which has a built-in countdown function - see link below

https://github.com/AntonyCorbett/OnlyT

**Comment by AntonyCorbett** [comment]
@defran02 Closing the issue because - as @timjobutler states - there exists an option in OnlyT.  Thanks for your feedback.
