### ISSUE TITLE
Play and Pause Option

### ISSUE THREAD

**Issue by Roblinproductions** [AntonyCorbett/OnlyM#16]
Work so far on this needed option for external media playback in our halls is much appreciated
Not really a fault issue but the need to be able to play and leave the final frame on screen by pausing after playback. VLC is currently being used as this offers this option but users find VLC complicated. We would like to use this option for HLC training videos that work by leaving an image on screen for a seamless presentation. The simplicity this software offers is much appreciated by end users. 
Since Soundbox development was finished I never bothered to request the option but at this early stage in development of OnlyM it seems opportune to request this option we need in training with HLC material.

regards Robin

**Comment by AntonyCorbett** [comment]
@Roblinproductions thanks for feedback. The final frame of a video is often empty, so I'd welcome some thoughts about what the basic requirement is. Thanks, Antony

**Comment by AntonyCorbett** [comment]
@omaha4 - when I use the sign language app and set a video to "freeze" it does indeed stop on the last frame of the video which is empty - a black screen. How does this differ from what OnlyM already provides (the ability to revert to a black backdrop when the video finishes)?

**Comment by omaha4** [comment]
Ahh, lets say after paragraph 2 of the watchtower, or some other Sign language pub, there is a picture that is bookmarked, and in our group without cameras I need to hold on that picture and talk about it, I can do just that with freeze. Its like having an extra person, the freeze command was set before the meeting. To Robinproductions point, if his HLC training videos are not black on the last frame of the video, and indeed, have a picture on it, and they need to discuss it, then freezing, or pausing it would be the option they select, for that video. VLC can do this, but it is so deep in the options, you wouldn't know about it if you didn't read the branch's instructions, and even then, it is a universal option, not a case by case option. Remember, not all videos are going to be blank on the last frame.

**Comment by AntonyCorbett** [comment]
Thanks, that's useful. If I understand correctly, some videos (specifically some jw sign-language videos and perhaps some HLC videos) are designed to conclude with a still image (presumably shown in the last few frames) where the intent is that the video should be frozen at that point while further discussion continues. Furthermore, it's important to be able to specify in advance whether a particular video should be frozen at the end or allowed to conclude normally. Right?

**Comment by omaha4** [comment]
That's the main point. Sign Language videos have bookmarks that allow for complex customization in the playlist, but that is a topic for another day. But there are videos out there, hearing and deaf, that don't black out on the last frame ( I seem to remember this very subject almost burnt me in VLC a while back). It is for these videos, that being able to individually select, pause or stop, would be useful to some.

**Comment by AntonyCorbett** [comment]
Thanks. There are 2 sets of similar requirements here (HLC and Sign Language). Sadly, both are edge cases as far as the core purpose of OnlyM is concerned, and adding support for them risks feature creep (support for bookmarks, freeze to a specific frame, etc). I want to keep OnlyM simple and recognise that this will limit its application in some scenarios. I may add a per-video "freeze" option to allow the video to pause on the final frame, but that's as far as I think it will go. Thank for your valuable input.

**Comment by omaha4** [comment]
Indeed, I was using sign language as an example as an example of what could be done.  JW Sign language is doing an awesome job of filling our needs ( it actually took 4 years of patiently waiting for the customizable playlist feature to make it to JWSL :) ). If you use VLC for your videos, remember to have the

**Comment by Roblinproductions** [comment]
Appreciate you considering the option. A per video freeze function would solve our issue. Thank you

**Comment by AntonyCorbett** [comment]
#17 implemented
