### ISSUE TITLE
"Mirror" checkbox not translated

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#161]
If it's enabled from settings, the "Mirror" checkbox on the main window is not translated. I've checked this for several languages which are 100% translated in crowdin.com and this field is not translated.
![image](https://user-images.githubusercontent.com/45002147/50404404-29e4a680-07b0-11e9-8a84-9f0749fa4650.png)

**Comment by LvDaniel** [comment]
@AntonyCorbett You read my mind... Few seconds after I open this, I saw the "Mirror" text for translation in crowdin. I'm closing this.

**Comment by AntonyCorbett** [comment]
:)
