### ISSUE TITLE
Scroll scriptures in OnlyM

### ISSUE THREAD

**Issue by impac1** [AntonyCorbett/OnlyM#165]
**Describe the bug**
When we click on the play button a scripture that doesn't fit the 1st screen & requires another screen to finish it, or if there are 2 verses to be shown together but doesn't fit 1 screen, we can't figure out how to get it to the second screen. We cannot figure out how to get it to advance. We use OnlyV & save it & copy it to the OnlyM media folder. I will apologize in advance for my ignorance. Thank you!

**To Reproduce**
3. See error

**Expected behavior**
Advance the screen to the next screen to finish the scripture.

**Screenshots**
![2018-12-28_065539](https://user-images.githubusercontent.com/13416953/50516119-81b03580-0a6e-11e9-8b15-3ef46c627d2a.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@impac1 Drag and drop from OnlyV on to the OnlyM main window (not onto the media folder). This will create a single slideshow item.

**Comment by impac1** [comment]
Thank you so much Brother Corbett!
I hated to bother you seeing all the messages/requests you get.

I'll take this opportunity to thank for your years of hard work &
dedication to helping Jehovah's sheep!

I'm not sure if you will ever fully appreciate the full scope of help you
have been to the thousands, perhaps millions, of the friends.

You work no doubt through exhaustion, complex issues &, literally, God only
knows what.

You have never given up on us! Thank you. That's almost pointless &
powerless to say so I say, too: May Jehovah bless you & open the flood
gates of heaven on you & your family that shares you with us all!

-yb
Patrick A. Corrente
Burkburnett Congregation
Burkburnett, Texas

**Comment by AntonyCorbett** [comment]
@impac1 Many thanks for your kind words. Glad you can make use of the software!
