### ISSUE TITLE
The DELETE command does not delete the image from the list

### ISSUE THREAD

**Issue by tenisak** [AntonyCorbett/OnlyM#168]
**Describe the bug**
The DELETE command (in Command panel) does not delete the image from playlist. Nothing will happen. I've found that the image has a read-only attribute. 

**Expected behavior**
Delete the file (even if it has a read-only attribute). <-- Preferred solution
Or show some information why deletion has not occurred.

**Desktop (please complete the following information):**
 - Windows 10 1803

**Comment by AntonyCorbett** [comment]
@tenisak A message is now displayed in the notification bar if a file cannot be deleted (for whatever reason)
