### ISSUE TITLE
How do I view webpages?

### ISSUE THREAD

**Issue by tenisak** [AntonyCorbett/OnlyM#169]
The settings contain items for displaying webpages. But I do not know how to view the web page.
Where to write a url? I tried dragging a link from the browser, save the page as a file, ...
Can you please advise on how to do this?

**Comment by mbrakutt1** [comment]
Hello @tenisak firstly navigate to the OnlyM media folder, right click on an open space and the context menu appears, from there select new and then new shortcut. A a box will appear to enter a file path, copy the URL or web address of your choice into the text field and create shortcut.

After wards navigate to the OnlyM interface and see if it appears. 👍

**Comment by tenisak** [comment]
@mbrakutt1 thanks for the explanation! :-) It's quite non-intuitive... :-(

**Feature request:** Would you be able to add a site by dragging the URL into the OnlyM window? Or, create an icon to add URLs?

**Comment by AntonyCorbett** [comment]
@tenisak from the wiki:

> To present websites, use web page shortcuts (right-click in the Windows Explorer folder, select New => Shortcut...).

Please feel free to add a feature request issue.
