### ISSUE TITLE
Easier inserting URLs of websites

### ISSUE THREAD

**Issue by tenisak** [AntonyCorbett/OnlyM#173]
**Is your feature request related to a problem? Please describe.**
Inserting websites is not very intuitive. Without instructions it is not possible to figure out how to do it.

**Describe the solution you'd like**
Add a page to playlist simply by dragging url address into OnlyM window.
...or, create an icon to add URLs (via input box).

**Comment by AntonyCorbett** [comment]
@tenisak Completed. Please see latest pre-release

**Comment by tenisak** [comment]
@AntonyCorbett Thank you very much for your work! It works great!
