### ISSUE TITLE
View study bible videos 

### ISSUE THREAD

**Issue by jsquiggz** [AntonyCorbett/OnlyM#175]
Hi, the ability to mirror the websites is a great feature.

Is it possible to enable flash (or equivalent) in the Chromium browser so that the videos from the study bible notes eg "Battlement of The Temple" in Luke 4 can be played. At the moment the browser doesnt allow it to play

Jon

**Comment by AntonyCorbett** [comment]
@jsquiggz I think you can install pepper flash as a system installation.

https://bitbucket.org/chromiumembedded/cef/issues/1586/add-pepper-flash-plugin-support#comment-16898332

Perhaps you could try?

**Comment by blazer2004** [comment]
As an alternative, as of JWL 10.6, the Study Bible videos play on the second screen as well.
