### ISSUE TITLE
Websites and PDFs mirror function Issue 

### ISSUE THREAD

**Issue by MDS201** [AntonyCorbett/OnlyM#176]
![onlym mirror issue](https://user-images.githubusercontent.com/46344352/50633045-cd1c8500-0f41-11e9-9002-37d96e8a8f77.jpg)

As shown in the image attached our congregations laptop shows the mirror function as displayed. I tested it at home and I have no problem in this regard.

When you move about it only shows you this area of the website shown in the image (it is also the same with PDFs). Because of this we are having to follow along from the monitors on the other side of the main hall which can become a challenge especially when using JW.org. 

There is the magnifier option but would rather be using the mirror function.

Could you help in this matter.

**Comment by AntonyCorbett** [comment]
@MDS201 please check that the monitor scaling is set to 100% and try again.

**Comment by MDS201** [comment]
Thanks very much. Thats the issue sorted. 

The monitor was set as 150% scale as default.

**Comment by AntonyCorbett** [comment]
@MDS201 Yes, I need to get that fixed, but at least you have a work-around for now

**Comment by AntonyCorbett** [comment]
See #224

**Comment by robertkjr3d** [comment]
But on a 4K or something monitor (that the world is moving to).  You would never set it to 100% scaling.  It is not even the default.  It would seem that the code could be looked at.
