### ISSUE TITLE
Slideshow Manager allows saving when dwell time is invalid, field not populated

### ISSUE THREAD

**Issue by GrahamR-AU** [AntonyCorbett/OnlyM#185]
**Describe the bug**
Slideshow Manager allows saving a file when an invalid value is specified for dwell time. Also when an existing file is opened within which the "DwellTimeMilliseconds" field contains a non-zero value, the "Dwell time (secs)" field in the UI is not populated.

**To Reproduce**
1. Open Slideshow Manager
2. Open an existing slideshow
3. Note that the "Dwell time (secs)" field is not populated
4. Specify an invalid value for dwell time (I used 0.1). Side note: Perhaps this shouldn't be considered invalid as the json file stores the value as milliseconds?
5. Save the file
6. See error associated with the dwell time field
7. Inspection of config.json shows a value of 10000 msec has been saved

**Expected behavior**
I would expect that if any field contains an erroneous value that the file should not be able to be saved. When an existing file is opened within which the "DwellTimeMilliseconds" field contains a non-zero value, I would expect the "Dwell time (secs)" field to be populated with that value.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows version [Version 10.0.17134.472]
 - This is my home PC that I use to test things for the Kingdom Hall and Circuit Assemblies

**Comment by AntonyCorbett** [comment]
@GrahamR-AU Thanks. Fixed for next release. Additionally, any invalid value is replaced with the default (10000ms)
