### ISSUE TITLE
Resize window to smaller size

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#187]
I was just wondering if it's possible to resize OnlyM window to a smaller size (to have for example OnlyT width size), to occupy less space considering that OnlyT and JWL needs to be open in the same time.
If this complicates things, don't worry is not something very important, just a nice to have.
Thank you.

![jwl onlyt onlym](https://user-images.githubusercontent.com/45002147/51118019-02658480-1818-11e9-97f4-43d423d809f3.png)

**Comment by talkingdragon** [comment]
I agree it be helptful. We use a 15inch laptop and space is tight.. I was wondering if u can maybe make like a tab app. So that like u had in soundbox each function was in a diffrent tab. Hard to explain... Like a OnlyA that y can run te Only programs u want in it, with diffrent tabs.

**Comment by Blann** [comment]
@talkingdragon I know that Antony does not plan make an all-in-one app – the reason for this is that JWL is subject to constant updates with new features but it's not known what these will be. Keeping each function separate allows one or several to be gracefully dropped should JWL be updated with a corresponding function, without impacting the others.

As far as OnlyM goes, our approach is just to position and size it identically to JWL and switch between the two on the taskbar. Our reasoning is that you will never be using the two simultaneously (at least not in any scenario we've encountered), so they don't need to be visible simultaneously.

**Comment by blazer2004** [comment]
@LvDaniel , Have you looked into using Areo snap? It's a hold over from Windows Vista that is still very useful today. A similar but independent feature introduced with UWP in Windows 8 is the ability to UWP apps to reshape the contents when resized. JWL does this just fine, and there is a lot of unused white real-estate in the screen shot above.

**Comment by LvDaniel** [comment]
@blazer2004 yes, can be useful but unfortunately OnlyT is not Aero snap ready, just OnlyM.
And Aero snap takes a half or a quarter of screen and I want JWL window to be a little bit larger than that as sometimes there is more content (most often images) and if the window is tighter I need to scroll down so see all the content. However, thanks for the tip.

**Comment by GrahamR-AU** [comment]
@LvDaniel , looking at your screenshot, I'm wondering why you have the desktop icons showing on the left rather than using that part of the screen? Pinning any icons that may be needed to the taskbar will give you a lot more space!

I actually hardly ever have any icons on my desktop for the very reason that you can't see them when you have apps open!

Graham

**Comment by LvDaniel** [comment]
@GrahamR-AU the reason is that operators are used to open the apps (OnlyT, OnlyM etc.) from desktop.
Sometimes as we display the countdown timer before the meeting we need to close/open OnlyT if the operator forgets to leave OnlyT app active.
But I get your point, we can try to pin them to Start and teach the operators to start it from there. Thanks for your feedback.

**Comment by GrahamR-AU** [comment]
@LvDaniel , I found a program called [Groupy](https://www.stardock.com/products/groupy/download) (from Stardock) that would seem to be designed to do what you ask. Free 30 day trial then $4.99 (probably US$) to purchase a licence. I downloaded and installed it late last night, however I couldn't get it to group the OnlyX apps. Perhaps @AntonyCorbett knows how to make it work?

Graham

**Comment by LvDaniel** [comment]
@GrahamR-AU thanks anyway for your suggestion.

**Comment by AntonyCorbett** [comment]
@LvDaniel The only way to reduce the width of the OnlyM window by the amount requested is to reduce the size of the thumbnail image.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for feedback. Reducing the thumbnail would be fine from my perspective.
This will be reduced progressively depending on width or needs to have a fixed size?

**Comment by AntonyCorbett** [comment]
> reduction of the font size of the title text

The title is automatically trimmed as required. Slideshow items are the most constraining.

**Comment by LvDaniel** [comment]
Will be a nice option if doesn't complicates things.

**Comment by Chipperchap** [comment]
@LvDaniel - please, how did you create your PT theme title?

**Comment by LvDaniel** [comment]
> @LvDaniel - please, how did you create your PT theme title?

I've create it in PowerPoint. If you want I can share the template, just let me know.

**Comment by Chipperchap** [comment]
@LvDaniel :  Nice - thank you for that 👍

**Comment by LvDaniel** [comment]
@Chipperchap you're welcome.

**Comment by AntonyCorbett** [comment]
Resizing to smaller width / height is now possible. Closing

**Comment by LvDaniel** [comment]
Thanks Antony.
