### ISSUE TITLE
Scrubbing with arrow keys

### ISSUE THREAD

**Issue by strawberry-sundae** [AntonyCorbett/OnlyM#189]
It would be a huge help if the left/right arrow keys could scrub **in 1-second intervals** for more precise video start times.

The logical process to me is:

1. Use the mouse to go to the approximate time.
2. Now that the slider on your desired video has focus, use arrow keys to go to the exact time.

**Comment by AntonyCorbett** [comment]
All done

**Comment by strawberry-sundae** [comment]
Thank you!!
