### ISSUE TITLE
Windows support under Parallels on iMac?

### ISSUE THREAD

**Issue by jhalbrook** [AntonyCorbett/OnlyM#194]
Hi Antony, 

I cannot get OnlyM to run in Windows 10 under Parallels on our iMac running High Sierra.  When I run OnlyM.exe I see the CefSharp.BrowserSubprocess.exe process fire for just a second or two, then it ends, and OnlyM.exe does not run.

I turned off Windows Defender prior to installing and attempting to run, and added OnlyM.exe as an allowed program in Windows Defender. 

Any ideas? 

As always, thank you in advance, Antony!

Joe Halbrook
Jefferson City English Congregation - Jefferson City, Missouri USA

**Comment by AntonyCorbett** [comment]
@jhalbrook Please would you make sure you are using the latest release and then check in Windows event viewer for any error messages associated with trying to launch OnlyM? Thanks.

**Comment by jhalbrook** [comment]
Yes, using the latest release.  No events logged in System, Application, Security, or Setup event logs when trying to launch OnlyM.

**Comment by blazer2004** [comment]
@jhalbrook Interesting Approach. Curious, which mode of Parallels are you attempting to run it in? I looked up your congregation on JW.org and sure enough, your sharing your hall with ASL. I would think that until your Mac dies, it would be perfectly reasonable to use KH Audio 4 until ASL switches to Windows 10 down the road.

**Comment by jhalbrook** [comment]
KH Audio looks like an overkill for our needs (and a lot of work).  We’re just trying to play external (from JW Library) images and videos during our meetings.  As long as SoundBox plays well with JW Library, that will work for us.  Thank you, Antony.
