### ISSUE TITLE
MP3 Playback

### ISSUE THREAD

**Issue by Blann** [AntonyCorbett/OnlyM#20]
Hi Antony, I tried to import and play an MP3 file that was generated by the record function in SoundBox and OnlyM doesn't seem to be able to play it - when the play button is pressed, the pause button appears for a split-second, and the JWL media window flickers a bit (this doesn't seem to be consistent - sometimes the window disappears for a split-second and is then restored, sometimes it minimises and is not restored), but the file does not play.

Additionally, OnlyM is not reading the duration of the file correctly - on this particular file the duration is 36:08, where OnlyM is showing 08:02.

I've tried with a number of different MP3 files from different sources and the result is the same save for the duration issue - that doesn't always happen.

Not familiar with how OnlyM handles the files so is it possible that this is an issue with our PC configuration (codecs etc)?

**Comment by Blann** [comment]
Apologies, I think I've answered my own question, although I can't explain the answer! When running OnlyM by itself, playback is fine, but I was running it as part of an AutoIt script that launches a bunch of apps at once, and it seems when I run it that way, it can't play anything (videos included). Will stick to the standard shortcut!

Please close this issue.

**Comment by AntonyCorbett** [comment]
@Blann ok - thanks. Appreciate you reporting back. Regards, Antony
