### ISSUE TITLE
Resource string needs singular/plural version

### ISSUE THREAD

**Issue by AntonyCorbett** [AntonyCorbett/OnlyM#209]
The resource string "(contains {0} slides)" should be replaced with 2 strings (singular case and plural case)

**Comment by GrahamR-AU** [comment]
Hmm, why would you have a slideshow with only one slide??

**Comment by AntonyCorbett** [comment]
@GrahamR-AU Yes. A single timed image is the only application I can think of.

**Comment by GrahamR-AU** [comment]
I've tested this (just for fun really). It doesn't work, when the dwell time has passed the slide remains displayed, regardless of Auto-play being selected or not.

**Comment by LvDaniel** [comment]
I confirm. Would be nice if at the end of the dwell time the slide to stop if auto-play is configured.

**Comment by AntonyCorbett** [comment]
There is a new slideshow parameter "AutoClose" which can be applied to "AutoPlay" slideshows that don't loop. When enabled, the AutoClose setting ensures that the slideshow automatically closes at the end fo the final slide.

**Comment by LvDaniel** [comment]
That's perfect, thank you.

**Comment by GrahamR-AU** [comment]
Works well, thanks!
