### ISSUE TITLE
Fade - Setting NONE still has fade.

### ISSUE THREAD

**Issue by garethawhite** [AntonyCorbett/OnlyM#210]
I want to be able to turn FADE off for certain slide shows where I have a main image that is on each slide with extra text/bullet points appear with each slide. From the audience point of view they are seeing one image with bullet points appearing as the talk develops. [I produce the slideshow in Powerpoint and save the slides as a set of images.]
Obviously it is distracting to have the screen fade each time a new point is discussed. In SoundBox it was possible to switch off the fade between slides. OnlyM has a setting for Fade, but setting to NONE doesn't appear to stop the fade.
And thank you ever so much for all the work you have put into these tools. It is very much appreciated!

**Desktop (please complete the following information):**
 - Windows 10

**Comment by GrahamR-AU** [comment]
@garethawhite In OnlyM Slide Manager there are fade settings for each slide, click the "Edit Slide" button to reveal these settings.

Graham

**Comment by AntonyCorbett** [comment]
@garethawhite Works fine for me. What version of OnlyM are you using please?

**Comment by garethawhite** [comment]
Thanks Brothers,

I hadn’t noticed the settings for fade were in SlideManager. It works perfectly now.

Thanks for your prompt response. – The talk is in 50 minutes – so I can just finish my coffee and head off to the hall happy!

Your brother,

Gareth White
