### ISSUE TITLE
Ability to stream JW videos on extended display projector from shortcut in OnlyM

### ISSUE THREAD

**Issue by shbin1** [AntonyCorbett/OnlyM#214]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shbin1** [comment]
We want to be able to stream talks from stream.jw.org or tv.jw.org. When you try, it displays an error about the media not being available on the computer or network. They work fine when the displays are duplicated rather than extended from Windows display control. I guess it doesn’t know where to buffer the video as it is being streamed.

**Comment by AntonyCorbett** [comment]
Until jw.org drops flash in favour of html5 video, you need to install a flash plugin as mentioned in the wiki.

**Comment by shbin1** [comment]
Dear Anthony
Sorry, as JW videos play ok through JW Library I thought we must have that plugin already, I never checked.

By the way I really appreciate how well you have handled the sidelining of Soundbox, which we loved. You have filled the gaps well. Great humility.
Thanks

Your brother 
John Ashby
