### ISSUE TITLE
Video Seek / Pause

### ISSUE THREAD

**Issue by XionTech** [AntonyCorbett/OnlyM#215]
Prepared a video (seeking past unwanted intros) and paused it (queued). Used JWLib to play media and when ready for the queued video, pressing play did not actually play the video. The play status appeared to be progressing however the video was locked and did not actually play. Had to press stop and 'reseek' to get the video to work.

**Comment by AntonyCorbett** [comment]
What version of OnlyM please? Can the problem be reproduced?

**Comment by LvDaniel** [comment]
@AntonyCorbett & @XionTech I wasn't able  to reproduce this issue using the latest OnlyM version. 
I also seek and even keep it there for more than 1 hour before playing (in this time I was playing occasionally some content with JWL) but all works fine for me.

**Comment by XionTech** [comment]
Interesting.  Yes I was able to reproduce the issue.  Version 1.4.0.9. It was a meeting video so it's 1:43:57 long.

**Comment by LvDaniel** [comment]
@XionTech I tested with a small file, 3 minutes or so. Your file was a meeting downloaded from stream.jw.org?

**Comment by XionTech** [comment]
I will try to monitor closer.  I replicated the issue once and now I cannot. I do have to manually minimize the second JWL window each time when using pause/resume.

**Comment by AntonyCorbett** [comment]
@XionTech ok - please re-open the issue if needed.
