### ISSUE TITLE
MP3 Playback and Media Display

### ISSUE THREAD

**Issue by Blann** [AntonyCorbett/OnlyM#22]
Not an issue, more of an exploratory request - SoundBox is able to play audio files and display still images simultaneously. Is it possible to make OnlyM do something similar? It currently takes control of the media display when playing audio files which seems unnecessary to me, although I can understand if it's just a blanket policy for all files for the sake of simplicity.

Thanks in advance

**Comment by AntonyCorbett** [comment]
@Blann - done. Audio and Image items can now be played simultaneously,
