### ISSUE TITLE
JW Library not displaying song lyrics on second monitor

### ISSUE THREAD

**Issue by hullsquashboy** [AntonyCorbett/OnlyM#221]
We display a slide in Only M at the beginning of the meeting before the opening song, then blank the screen with Only M blank screen slide. The song is introduced and we play this in JWL. The sound is heard of the song but no lyrics are seen on the second monitor (its a 2 monitor setup, 2nd monitor is to the RHS of the main monitor). Stopping the song, then shutting down Only M makes no difference, still no lyrics. Shutting down JWL as well, restarting JWL, playing the song, still no lyrics!!! But the music is heard. Rebooting the PC sorts the issue out.

We are going to try using Only M at the beginning of the meeting for the slide, shut it down and run JWL and see if this clears the issue.

Today we had the same issue. Any ideas please as we use the same workflow every meeting but this intermittent issue seems to rear its head now and again.

Thanks Anthony for all your hard work in the applications which we find invaluable, as did we with SoundBox!!

Chris R

**Comment by Blann** [comment]
Don’t use the blank screen item. Just stop displaying the image you use at the appropriate time. Blank screen causes OnlyM to do what it says on the tin – blank the screen. You don’t want this active if you’re using JWL at the same time. You can remove it from the list altogether in the settings if it confuses the issue.

**Comment by LvDaniel** [comment]
@hullsquashboy have you tried to use [JwlMediaWin](https://github.com/AntonyCorbett/JwlMediaWin)?
This ensures "that the JW Library media window is not "lost" when using other applications to render media on the same monitor!" 
More details on [wiki](https://github.com/AntonyCorbett/JwlMediaWin/wiki).

**Comment by AntonyCorbett** [comment]
@hullsquashboy closing now but please reopen if needed.
