### ISSUE TITLE
Portable?

### ISSUE THREAD

**Issue by HubertMielcarz** [AntonyCorbett/OnlyM#225]
Hi Brothers,
Can this app be portable? We visit Kingdom Halls performing some trainings and not everywhere the app can be installed...
Regards

**Comment by blazer2004** [comment]
@HubertMielcarz, you could have your presentation on your USB stick available in a couple different formats, ready to go when you travel. Its not the most convenient, but it works.

**Comment by AntonyCorbett** [comment]
@HubertMielcarz Please see the following:

https://github.com/AntonyCorbett/OnlyM/wiki/Portable-Operation

There may be other refinements required for good portable operation but I've tested that the basics work ok.

**Comment by TizianoNoto** [comment]
@AntonyCorbett 
> There may be other refinements required for good portable operation but I've tested that the basics work ok.

Are the settings still stored in `%APPDATA%`? If so, it'd be a good idea to save them in the removable drive, maybe with an appropriate command-line switch (e.g. `--portable`).

If enough tests show that OnlyM works fine in portable mode a ready-to-use ZIP file could be made available for download.

**Comment by HubertMielcarz** [comment]
So far so good! We used several computers to test it - tests passed. We are going to use it in a "production environment" next week.
Thank you very much for your quick response, Brothers :)
