### ISSUE TITLE
Design OnlyM

### ISSUE THREAD

**Issue by davono** [AntonyCorbett/OnlyM#228]
Hello Antony
I would like to suggest you, but it's just my opinion :)

The application is absolutely cool, we use it for a group of sign language. He helps us very much, because at the same time we can work with JW Sign Language. I would just like to design aesthetically modified apps.
I really like the modern jwl mergle window. It is customized and looks like part Windows 10. OnlyM looks like a mirror of an older window, I would say windows xp. If you made the same graphics window as jwl merge or something similar, it would already be perfect.

It's up to you. Anyway, thank you for great work.

Sincerely, David

![jwlmerge](https://user-images.githubusercontent.com/48017820/53417947-f3f1b780-39d6-11e9-8668-874fd7b2d82a.jpg)

![onlym](https://user-images.githubusercontent.com/48017820/53417984-09ff7800-39d7-11e9-941a-84b5031fa3c5.jpg)

**Comment by AntonyCorbett** [comment]
@davono Thanks for feedback. Latest pre-release has a more modern-looking UI
