### ISSUE TITLE
Improvements in sound

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyM#231]
Hi Antony,
I wanted to ask you if there is the possibility of having sound improvements such as an equalizer and compressor.
Best regards.

**Comment by AntonyCorbett** [comment]
@gonzo041 Thanks for your suggestion. Sorry no, this won't be in the scope of the project. There are several good quality applications that focus on EQ and compression. Equalizer APO is one such that may be useful. https://sourceforge.net/projects/equalizerapo/

Utilities like Equalizer APO allow you to modify most aspects of the PC sound so could also be used - for example - to compress the recording channel for audio out to the conference system.
