### ISSUE TITLE
Crossfade instead of fade in on slideshow

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#234]
If I have a normal image displayed with OnlyM, when I'm trying to displaying an omslide file (without stopping the image currently displayed) images are crossfading (the image & the first slide of omslide file).
This is happening even if OnlyM fading style is set to "Fade in and fade out" and omslide file has "Fade in" option selected.
This is more visible when fading speed is set to Normal or Slow.

**Comment by AntonyCorbett** [comment]
@LvDaniel Sorry for the delay in responding. To clarify - you describe setting the image to **fade out** and the slideshow to **fade in**. This has the effect of cross fading whereas you expected to see the image fade to black and then the first slide to fade in. If you want the latter behaviour then you should stop the image first before starting the slideshow.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for the explanation.
