### ISSUE TITLE
Images on timer display

### ISSUE THREAD

**Issue by wildinocence** [AntonyCorbett/OnlyM#236]
Good morning, Only M its a fantastic resource for the meeting and extra media to display images.

One sugestion , and a feature that we use in the sound and media system its the feature present on sound box Images on timer display,  by display images to the  screen of timer, now with only M and Only T , its not possible to do the same, and using media foundation.

Any future add of this function?

It be great , because we only use one screen in front of the meeting speaker.

Thanks for all the great work.

**Comment by AntonyCorbett** [comment]
@wildinocence thanks for your feedback and kind words regarding OnlyM.

Please see here for a discussion:

https://github.com/AntonyCorbett/OnlyT/issues/234
