### ISSUE TITLE
Images not working. Play button grayed out. 

### ISSUE THREAD

**Issue by eetle** [AntonyCorbett/OnlyM#237]
For some reason videos work fine but images don't at all. I'll try to link a photo, but the thumbnail is there working but the play button is grayed out. I've uninstalled it installed older versions and it is still the same. Because of this I think it is a problem on the halls pc. Maybe a permission issue? I don't know.

**Comment by eetle** [comment]
https://drive.google.com/file/d/16UvyYv4Mx0ojcNrmPoq6lK4NmwvuXdEW/view?usp=drivesdk

**Comment by AntonyCorbett** [comment]
@eetle did you sort it out?

**Comment by eetle** [comment]
Yes. All it was, was that no monitor was selected
