### ISSUE TITLE
Backup system

### ISSUE THREAD

**Issue by buteman** [AntonyCorbett/OnlyM#239]
Sorry for jumping in here but cannot find how to get in touch now soundbox is no long available.
This is not about OnlyM but perhaps an idea for a fallback system
I have been concerned for some time that we have a PC at the Hall and an amplifier but nothing else. If the PC fails we have no way of playing songs or doing anything else. Apart from having to put up with that until the PC is fixed or replaced has anyone thought of anything else?
I have been playing with Raspberry Pi's for some time and think they could be used as a cheap backup system.

**Comment by scottys94** [comment]
You can consider using an Apple TV to mirror a mobile device if the computer fails.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richfrantz** [comment]
3.5mm male to 6.35 male
Similar to this
https://smile.amazon.com/dp/B00Y2LANNW/ref=cm_sw_em_r_mt_dp_U_FzQJCbTP900XY

And anyone with the audio portions and a headphone jack and you should be able to plug into your amp.

**Comment by buteman** [comment]
Well I could use a Linux laptop as well but the Raspberry Pi is £35 and even with cables, a case, keyboard and mouse it comes to less than £100 so it could be left plugged in and with the correct wiring in a few minutes it would allow all the songs, images and videos to be displayed on the screens almost as normal.  I have already written some python code which will run on it and do all that.

**Comment by richfrantz** [comment]
I meant plug into your mixer.
________________________________

**Comment by LvDaniel** [comment]
Or you can use an USB MHL to HDMI cable to connect your phone screen TV and use JW Library + an 3.5 jack to 6.35 jack / RCA for the sound. If you have the yeartext image saved on your phone, even better.

**Comment by buteman** [comment]
I can see most of the comments could work but with what I have already done all but the videos for the school and ones which are not yet available are already in place right through to June this year. 
What I would have in place is a cable with 2 HDMI outputs and 1 input. Unplug the 3.5 mm audio plug from the PC plug it into the Raspberry pi and the HDMI from the PC into the Raspberry PI.
The second HDMI output would go to a HDMI to VGA converter which would be connected to the PC screen.

**Comment by buteman** [comment]
I have attached a pdf of what it looks like at present
[screenshots.pdf](https://github.com/AntonyCorbett/OnlyM/files/2975679/screenshots.pdf)

**Comment by blazer2004** [comment]
I believe JW Library 11.0, mirrored thru an Apple TV or Apple AV adaptor, would be my back up tool of choice.

**Comment by buteman** [comment]
I'm thinking something which is ready to go in a few seconds not minutes or
hours. Unless the tablet / AppleTV /PC is there ready to go it would mean
at least one meeting severely  disrupted.

**Comment by blazer2004** [comment]
Having an Apple TV/AV adapter on hand is not a bad idea anyway. If you computer goes down, there will be a disruption anyway. If its wired correctly before hand, it can be ready to go in no time. Besides, why worry about maintaining the back and front ends of custom hardware/software when the branch has already done so.

**Comment by buteman** [comment]
So can you get jw.org  on Apple TV? I can get tv.jw.org on my Roku box which is great but  not jw.org so no images from workbook, Watchtower or Jesus the way. I know the python script is custom as was Soundbox but can you clarify why you think Raspberry Pi is custom hardware?

**Comment by blazer2004** [comment]
You been able to plug in an AV adaptor into an and iOS devices and get a year text second screen from JW Library for some time. But with JW Library 11, they have fixed the airplay issues, and we are now able to get the second screen over airplay, just like Windows 10. We have been doing this in our sign language group for years, but now, the purple app as we refer to it works just the same. You just have to go into JW Library settings and tell the app to turn on the second screen.

My point is simply this. We are talking about a back up system. How often is the computer going to crash (that is, a computer that is suited for the task and not one that should have never been bought in the first place.) Im just saying that rather than duplicating efforts, why not use what is already available and easy to train in case we kick the can, thats all.

**Comment by buteman** [comment]
So we need an IOS device and whatever is needed to connect it to the HDMI --> SDI interface and something to take the audio and feed that into the amplifier.
Is that correct? Any idea ow much that might cost?
Our PC has a 3.4 GHz quad core Intel processor with 16 GB Ram, 1TB hard disc and a video card with 3 outputs. It crashed once but that was a Windows 10 problem not hardware.

**Comment by blazer2004** [comment]
SDI to audio from a proper suppler is $160 US, MSRP, well worth the investment. With this device, any CO or trainer that comes wont have any SDI/audio issues if they bring there own device.

**Comment by buteman** [comment]
Oh this sounds as if it's getting complicated. So output  from the device is combined video and audio.
Our system has HDMI output from computer to an  HDMI to SDI box feeding a multiple output SDI driver  which goes to 3 SDI input connected screens.
Audio out from a USB connected audio card goes to the amplifier.

**Comment by blazer2004** [comment]
Your system isnt that complicated then, it sounds like only 1 video bus, which is pretty typical. The SDI to audio goes bewteeen the hdmi/sdi adaptor and the SDI distro amp. If your mixer is big enough, i.e., you have enough channels, you connect the sdi/audio to a spare channel(s) and you could leave the audio over usb hooked up if you wish. You would only open the SDI audio channel on the mixer if the connected device needs it. Thats pretty close to what we do.

**Comment by buteman** [comment]
Well all three of the video card's outputs are used. The HDMI goes as described. The DVI output is converted to VGA and feeds our timer screen. The VGA output feeds directly to the computer screen. Also HDMI output from the computer goes to a 1 in 2 out HDMI switch. One of these outputs feeds the projector we used to use regularly. So if any part of the SDI system fails we can at least switch HDMI to the projector.
The best price I have found so far for the SDI/audio gadget is £172!!

**Comment by blazer2004** [comment]
Theoretically, your HDMI will fail before the SDI will.  I can't tell you where you need to look for the SDI/Audio adapter because 1. Your in a different branch and 2. those arrangements are confidential anyway, and this is a public forum.

**Comment by buteman** [comment]
You might be right about the HDMI failure but both main screen SDI inputs have failed. I had to buy 2 SDI to HDMI adaptors. Good job the screens had USB connections to power them.

**Comment by blazer2004** [comment]
If the SDI was built into the TVs, that’s not the first time I’ve heard of that. I saw happen myself on a brand new TV! If you put in anything but monoprice, I doubt the new converters will go anytime soon. In our area, when we put in TVs and SDI, we switched the projector to SDI too.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by talkingdragon** [comment]
How about a amazon fire TV stick as a BKup? It now has a official jw broadcasting app. So u can then use that to play the videos etc. Good cheap easy BKup

**Comment by buteman** [comment]
@talkingdragon if you read earlier posts you will see why that's a poor backup overall.

**Comment by blazer2004** [comment]
@buteman Going back to your Raspberry Pi, idea, Today, JW Library 11 for Android was made available as a download from JW.org for sideloading. You could try loading Android on your Raspberry Pi and see how it works.

**Comment by talkingdragon** [comment]
True u could run android on the pi. With something like https://emteria.com/ and have it all pre setup

**Comment by SvenErikLarsen** [comment]
Have you guys tried asking your Local Design/​Construction Department for advice?
