### ISSUE TITLE
Select Screen

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyM#24]
Hi Antony,
When we use the Bible text image creator (BTIC) with SoundBox, it shows the selected Bible text image on the second (auditorium) screens nicely.  This can be done natively (from within BTIC using the 'Display' button) or by drag and drop into SoundBox media dialogue screen.  However, when SoundBox is not in use, BTIC will default to showing the generated Bible text image on the PC (booth) screen only.  I thought that I would open OnlyM as I am learning to use it, and thought now that it was open BTIC would now show images on the second (auditorium) screens, but alas, it doesn't integrate with OnlyM in that way.  Is there potential for this to occur?  In other words for OnlyM to 'tell' BTIC where to show the image?  
As many will be moving away from SoundBox I wondered if we might be able to still use BTIC with the newly available software (OnlyM).
The second potential advantage would be able to circumvent the need to extract individual images from a multiple image selection of verses (eg. Gen 1:1-5 which generates a 'folder' of verses) from within the storage folder to drop into the OnlyM dialogue screen as is currently necessary, by instead using the native BTIC functionality (using the arrows to advance to the next image for the next verses to display.)

**Comment by AntonyCorbett** [comment]
Thanks. Yes it's on my todo list. See #15
