### ISSUE TITLE
cannot display pictures

### ISSUE THREAD

**Issue by TimHamel** [AntonyCorbett/OnlyM#241]
**Describe the bug**
Today the C.O.  had pictures for his talk.  when clicking on the jpg picture the play button goes from play icon to the stop icon, but nothing appears on the screen.

**To Reproduce**
1. Open folder drag & drop pictures onto onlym window, 9 files copied message
2. click on picture, play icon changes to stop icon
3. no pictures display on designated monitor

**Expected behavior**
expected pictures to be displayed on designated monitor

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 latest
 - latest version of ONLYM

**Comment by AntonyCorbett** [comment]
@TimHamel The log file for teh date in question will provide the answer (Document\OnlyM\Logs). Would you mind posting it please?

Regards
Antony

**Comment by AntonyCorbett** [comment]
@TimHamel Any feedback on this please?

**Comment by TimHamel** [comment]
Yeah I got it resolved, From what I can tell another hall temporarily using our hall tried to install an additional monitor.  in short I had to remove all monitors and reinstall just the ones we use and all is working again.  Was just odd that it did not mater what monitor I picked it would not work.  Just glad all is well

**Comment by AntonyCorbett** [comment]
@TimHamel thanks for getting back to us. Glad it's sorted now - I'll close the issue.
