### ISSUE TITLE
How do I contribute a translation into a new language?

### ISSUE THREAD

**Issue by optisamit** [AntonyCorbett/OnlyM#243]
I can do a pull request, but idk what files should be translated

**Comment by AntonyCorbett** [comment]
@optisamit Thnaks for your kind offer. Please let me know the language and whether you also want to translate OnlyT. 

Please ceate an account in Crowdin.com and let me have your user name. I will create the project files for your chosen language and then invite you to manage that language translation.

**Comment by optisamit** [comment]
I'd like to translate into Bulgarian, only OnlyM for now.
My username: optisamit.
Thank you!

**Comment by AntonyCorbett** [comment]
@optisamit Thanks - I've sent the invitation

**Comment by AntonyCorbett** [comment]
@optisamit I will automatically include the language in subsquent builds which means that you can refine it over a number of weeks / months. You can also request me to build if you have done significant work or fixes. Thanks again!
