### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [AntonyCorbett/OnlyM#246]
Hi @AntonyCorbett  I am a graphic artist and i would like to design a logo for the project. if you are interested and will permit me, I'll start designing asap.Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by AntonyCorbett** [comment]
@Tobaloidee thank you for your kind offer but it's already changed twice in the project's short life so I'll leave the current logo in peace for the moment. Thanks again.

**Comment by Tobaloidee** [comment]
Okay Sir, Thanks again! 👍
