### ISSUE TITLE
view the third monitor on onlyM

### ISSUE THREAD

**Issue by KamilBac** [AntonyCorbett/OnlyM#249]
Please would you be able to view the third monitor on onlyM? And can I create an app to show song words on both the main monitor and the timer monitor? We do not yet have the original in the Czech language. Thank you Kamil Bacsó

**Comment by scottys94** [comment]
Are you just using the third monitor for a timer?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KamilBac** [comment]
Yes, we use a third timer monitor. And we would like to have lyrics and pictures with pictures - just like with SounBox.

**Comment by scottys94** [comment]
This method might work for you:
https://www.facebook.com/628386790598767/posts/1697938926976876?sfns=mo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
