### ISSUE TITLE
Image Display Size

### ISSUE THREAD

**Issue by GraemeWM** [AntonyCorbett/OnlyM#251]
Outputting images or video on display screen, images show at reduced size in top left of screen. Only way to reset is to toggle output monitor in settings. After toggling image plays full screen.

**Comment by AntonyCorbett** [comment]
Do you have any margins specified in the OnlyM options?

**Comment by AntonyCorbett** [comment]
On refelection, my question above is probably not applicable given that you resolve the issue by resetting the media window. Do you use the 'blank background' option? Is OnlyM started automatically at Windows boot? Can you fix the issue by closing and reopening OnlyM?

**Comment by GraemeWM** [comment]
Thanks for the thoughts Anthony.
No margins specified.
We do not use the blank background setting.
Only M is started manually.
Issue does not resolve when reopening OnlyM.
The projected image seems to be a 1280 x 720 image in a 1920 x 1080 frame.
Thanks again for your help,
Graeme

**Comment by AntonyCorbett** [comment]
Do you have display scaling set to anything but 100% for either monitor?

**Comment by GraemeWM** [comment]
Apologies for my ignorance. Where would this setting be?
G

**Comment by AntonyCorbett** [comment]
In Windows 10, it's Windows Display Settings => Scale and layout

**Comment by GraemeWM** [comment]
Thanks Anthony, I shall investigate this evening!
G

**Comment by GraemeWM** [comment]
Managed to check this out sooner. Displays set to 100% scaling. Interestingly, still images are playing full screen but the Special Talk mp4 came up reduced. I toggled the monitor and it played perfectly.

**Comment by GraemeWM** [comment]
Just closed the OnlyM window. Played mp4 when re opened. Reduced image. Then played still image. Reduced size.

**Comment by Spenser715** [comment]
You mentioned resolution earlier. What are the exact resolution settings for both your media and control displays?

**Comment by GraemeWM** [comment]
The screen is 1920 x 1080. The mp4 is 1280 x 720

**Comment by Spenser715** [comment]
Perhaps set your displays resolution to 720p as that has been the highest resolution available for videos from the branch historically. This may solve the issue.

**Comment by GraemeWM** [comment]
Thanks Anthony, appreciate your time and assistance.
I shall give that a try.
Warm regards,
Graeme

**Comment by AntonyCorbett** [comment]
I suspect an issue with the video driver and/or its compatibility with the latest Win10 update. You might try rolling back the video driver (or updating it if you find a newer one)

**Comment by GraemeWM** [comment]
Thanks Anthony,
Have to confess - I'm a Mac man! Never did understand Windows!
All the best,
Graeme

**Comment by GraemeWM** [comment]
Changed the display settings to 1280 x 720.
Seems to have worked.
Thank you all for your assistance.

**Comment by AntonyCorbett** [comment]
@GraemeWM glad it's sorted. I'm none the wiser :)
