### ISSUE TITLE
OnlyM doesn't work on second display

### ISSUE THREAD

**Issue by gaucho713** [AntonyCorbett/OnlyM#256]
**Describe the bug**
We have seen this behavior on multiple machines.  OnlyM works fine on all Windows versions up until the 1809 update is installed. Once installed, OnlyM doesn't display the images on the second screen as it should / used to.

**To Reproduce**
1. Open JW Library
2. Open OnlyM
3. Click on Image / Video and try to display
4. Image / Video does not display

**Expected behavior**
Image/Video display on 2nd screen

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 version 1809

**Comment by AntonyCorbett** [comment]
@gaucho713 Thanks for the report. I can't reproduce the issue on 1809 or later and haven't received any similar reports, so I wonder if it's configuration-specific. Some questions / requests:

1. Please attach a copy of your OnlyM log file for today (in Documents\OnlyM\Logs).
2. Does the image / video display ok if the primary display is selected?
3. Are all monitors successfully identified in the OnlyM, Settings => Display => Monitor drop-down list?
4. What happens to the Play button when you attempt to display an image on the 2nd monitor? i.e. does it indicate that the image is showing or does it remain in the same state?
5. Can you temporarily rollback the video card driver (Windows updates often install an unsuitable generic driver) and re-test?

**Comment by gaucho713** [comment]
Antony,

Thank you very much for your quick response.  I was able to dig into this a bit more. 

It looks like the 1809 update resets the Video Display Configuration.  Resetting the Monitor settings fixed the issue.

It is interesting that this consistently happened.  Microsoft must blow away some configuration when updating from 1803 to 1809.

Thanks again for your help and prompt response.
HG

**Comment by AntonyCorbett** [comment]
@gaucho713 thanks for reporting back. Unfortuantely it's common for Windows updates to mess with your video drivers.
