### ISSUE TITLE
Task bar is visible on second display

### ISSUE THREAD

**Issue by optisamit** [AntonyCorbett/OnlyM#257]
When playing video on second display, taskbar is partially visible. When I use JW Library, there's no taskbar. Can it be fixed?
Thanks

Open any video with OnlyM on second display (I opened mp4 from stream.jw.org)

**Expected behavior**
The same as JW Library: nothing except video is visible

**Screenshots**
https://imgur.com/a/JPSIxf5
https://imgur.com/57D9Px4

**Desktop (please complete the following information):**
Windows 10

**Comment by AntonyCorbett** [comment]
@optisamit I suggest you turn off the taskbar on secondary monitors.

**Comment by optisamit** [comment]
Thanks, the workaround worked!

**Comment by Spenser715** [comment]
@AntonyCorbett I'm wondering if there is another solution to this. At our hall we have the task bar set to show on all screens so brothers don't accidentally close our obs window on the timer screen. Having another way of covering the taskbar would help tremendously.
