### ISSUE TITLE
Second Display will not recover from no HDMI Signal

### ISSUE THREAD

**Issue by chadmbrown** [AntonyCorbett/OnlyM#258]
**Describe the bug**
When using an HDMI switcher to switch source inputs from a computer running OnlyM to another input (in our case a camera), OnlyM will ignore the Second Display setting and play content on the Primary display with HDMI signal. When the signal is restored to the Second Display the content stays on the Primary. If OnlyM fails to the Primary monitor with content playing, the OnlyM UI will not be available to stop playing content. (Issue #26) This problem is especially challenging if you have the task bar turned off on the Second Display. The bug was also reproduced by unplugging a second display and plugging it back in while content is playing. Looking at how the JWLibrary app deals with this scenario would be helpful.

**To Reproduce**
1. Use Second Display
2. Play content on Second Display
3. With content running unplug (or switch away from) second display
4. Re-plug or switch back to Second Display 

**Expected behavior**
Content will fail from Second Display to Primary. Depending on screen and taskbar configuration it may be impossible to manage the OnlyM.

**Desktop (please complete the following information):**
 Windows 10 Pro. Version 1803

**Comment by AntonyCorbett** [comment]
Re #26 just use Alt-tab to bring the OnlyM main window to the foreground

**Comment by AntonyCorbett** [comment]
The behaviour is by design and follows standard Windows guidelines. For example, open any application window (e.g. notepad) on a secondary monitor then unplug the data cable from the monitor. After a few seconds the windows appear on the primary monitor. AFAIK, most hdmi switchers have EDID support built in, but if you have problems you can purchase a small unit to retain the EDID data.

**Comment by chadmbrown** [comment]
We put an EDID solution in front of the HDMI switch to solve. Although low end KVMs have EDID, for some reason many entry level multi-input HDMI switches don’t. Yes, I agree it’s windows behavior. If purpose built for KH then the JWL behavior would be better. Regardless, problem solved for now. Thanks!
