### ISSUE TITLE
Wrong screen

### ISSUE THREAD

**Issue by Brent-Dorsey** [AntonyCorbett/OnlyM#259]
I cannot get the pictures/video to display on the second screen.  Your help section says that there is a setting under "display", but if you can see the attachment, you will see that there is no setting.
![Capture](https://user-images.githubusercontent.com/50811682/57989884-23acda80-7a6f-11e9-9cef-bb7319edb29c.JPG)

**Comment by scottys94** [comment]
What happens if you click the dropdown for “Generic PnP Monitor”? You should be able to choose another display from there.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Brent-Dorsey** [comment]
That did it.   Thanks

Brent Dorsey
Brent's Repair Service
386-872-1712

**Comment by scottys94** [comment]
Excellent!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
