### ISSUE TITLE
Using OnlyM on a thumb drive

### ISSUE THREAD

**Issue by KenFrantz** [AntonyCorbett/OnlyM#262]
I don't know that I would call this a bug, the app is working as designed. The issue is this:
I installed OnlyM on a thumb drive so I could use images in my talks without having to rely on sound board personnel to copy my images to their media player or risk having them possibly delete images from my thumb drive or put the images in the wrong location. I loaded my images to my drive and tested everything on my home PC. Works great. To be safe, I took my drive to the KH and plugged it in. I started OnlyM and my images were not there. Well, they really were but the KH PC assigned a different drive letter to the thumb drive so OnlyM couldn't find my images. I had to go to Settings and reset the media folder to the same folder with the different drive letter. Windows does not always assign the same drive letter to portable media. It used to assign the next available drive letter and make adjustments automatically, but that can't be relied on anymore.

I would like to see OnlyM default to using a media file that is located within the OnlyM folder rather than rely on a drive letter and file structure to locate it's media files. The same mechanism could be used as is in place now for selecting a folder on the PC, if the user so desires. But the default would be to use it's own folder unless specifically told otherwise by the user's having selected a different location. So, if it finds the Media Folder selection box to be empty, it would use it's own internal folder location. For my test, I created a "My Media" folder in the OnlyM folder on the thumb drive and put my images in that location. It works perfectly well, as long as the drive letter doesn't change. But that can't be relied on.

I've tried creating a shortcut to OnlyM that uses relative addressing but that only works for starting the app and it requires renaming the OnlyM folder to something else that would not be found on the KH PC. That's hard when you are not familiar with the PC at someone else's Hall.

Thanks, Ken

**Comment by AntonyCorbett** [comment]
Did you follow the "Portable Operation" instructions in the wiki? In particular did you specify the media folder on the command line and using a relative path?

**Comment by TizianoNoto** [comment]
A relative path in the shortcut's _Destination_ field should do the trick.

However, it still saves the settings in the host system and not in the portable drive. A command-line switch to choose if settings must be portable as well could be a nice addition.

**Comment by AntonyCorbett** [comment]
@KenFrantz @TizianoNoto I have updated the instructions to work around the problem described.
