### ISSUE TITLE
Some PDFs don't display

### ISSUE THREAD

**Issue by MPWinVA** [AntonyCorbett/OnlyM#267]
PDFs created on a Mac (image of properties attached) only display as a white screen

**To Reproduce**
1. Open OnlyM
2. Drop PDF (attached) on window
3. Click Play

**Expected behavior**
PDF should display on second monitor

**Desktop (please complete the following information):**
 - Windows version 10 1803
 - Other important information
PDF downloaded from JW.org works properly

![2019-07-16 21_59_32-Document Properties](https://user-images.githubusercontent.com/52985523/61342197-6264d400-a817-11e9-8bd0-45cc1e9f7bda.png)
[03-FW PROJECT #2.pdf](https://github.com/AntonyCorbett/OnlyM/files/3399802/03-FW.PROJECT.2.pdf)

**Comment by AntonyCorbett** [comment]
@MPWinVA there is something not right which I need to fix, but here's a workaround - before copying it into OnlyM rename the file so that the first period "." and the pound symbol "#" are both removed (e.g. rename it "03-FW Project 2.pdf")

**Comment by MPWinVA** [comment]
Thank you very much, Br. Corbett. This will make my Circuit Overseer happy! I greatly appreciate all the work you do to support the brotherhood.

 

Regards,
Mark

**Comment by AntonyCorbett** [comment]
@MPWinVA Just an update here. There is an upstream bug in the Cef browser that prevents display of files with a '#' symbol in the name.
