### ISSUE TITLE
Scrubbing using a textbox

### ISSUE THREAD

**Issue by AnsNie** [AntonyCorbett/OnlyM#270]
**Is your feature request related to a problem? Please describe.**
In small congregations where JW Stream recordings (or parts of those) are used each week is a problem that every time when operator moves the video to the right position, it takes some time out of the real meeting time and also disturbs audience, as they can see the video position being searched.
Clipping the video is not option in many cases as it needs a powerful pc, or a lot of time (which brothers in small congregations usually don't have - they just download the stream and show parts of it).

**Describe the solution you'd like**
The video time teaxt could be user modifiable, so that operator could just click on "00:00:00" and input the time he wants.

**Describe alternatives you've considered**
Alternatively this could be a separate box on the right side of the real video timer. Also this could be optional setting to keep the design simple by default.

**Comment by AntonyCorbett** [comment]
@AnsNie Please can you elaborate on this? In particular, why does the current scrubbing function not work for you? E.g. just move the slider to teh start position before clicking "Play".

**Comment by AntonyCorbett** [comment]
But also see #275

**Comment by yjenb** [comment]
@AntonyCorbett the current way of scrubbing works fine for video up to ~10 or maybe 15 minutes. The bar is long enough to find a specific time.
But if you are a foreign language group or congregation and you need to use portions of the streaming video, this is quite difficult.
So maybe you start live with song, prayer and opening words, than you switch to the stream for the talk. Switch back for the gems and reading. Again video for one presentation, than your live presentations. Again song and the 15 min before being live again with the study. With scrubbing (searching a point in a video using visual tools), it is hard to find the perfect fitting second - even with VLC player and having a bar all over the screen.
Some streams use chapters, but in general not for each part of the meeting, only 3 parts - so also chapter support would not solve the problem. But you can note down the exact timestamp and if you could jump to it, just typing it in this would be really great.
So I guess, this would be a function small language groups or small congregations would benefit from.

**Comment by AntonyCorbett** [comment]
@yjenb thanks for the useful feedback. So the operator would need to know in advance of the meeting the starting offset(s) of the various sections - right?

**Comment by AnsNie** [comment]
@AntonyCorbett Yes, @yjenb already gave the answer to your first question very well. In this case brothers check the times beforehand so that it is easier to start videos on correct moment. So yes, this is a compromise between actually clipping video and using the current bar.

**Comment by AntonyCorbett** [comment]
@AnsNie @yjenb Please see latest pre-release. There is now a small button to teh right of the playback time.

**Comment by yjenb** [comment]
I love it! Thank you Antony!
