### ISSUE TITLE
Crossfade and loss of HDMI sync

### ISSUE THREAD

**Issue by lazer321** [AntonyCorbett/OnlyM#271]
This last Sunday our visiting speaker had 35 jpg slides, all properly sized to 1280x720. Three times during his talk, switching from one slide to the next in OnlyM caused the monitors to loose hdmi signal lock and resync. This could be seen as a black screen for about 2-3 seconds then the slide would appear with the monitor displaying the input info box in its top corner with the usual HDMI1 and resolution info.

After examination, we found that going back and forth between a mostly black slide and a mostly white slide would cause a loss of hdmi sync about 10-15% of the time with a sample size of about 50 transitions. When the crossfade was turned off, 100 transitions were performed with no sync loss at all.

Obviously, we'll now be running it with the crossfade turned off, but I just wanted to make you aware that there might be an issue. I've attached a sample of 2 jpgs that were causing an issue. Our system is a HP Pavilion 510-p026 Desktop PC with 12Gb memory, i5 processor, and Intel 530 graphics. We are feeding a 720p hdmi video signal to a hdmi to sdi converter, then a sdi splitter to converters located at the monitors. 

Thank you for all your hard work, both with the Only-series and SoundBox before that!

Your Brother,
       - Kevin McCabe.

![Slide06](https://user-images.githubusercontent.com/8248426/62086522-97682200-b22c-11e9-859b-b1fa7055623a.JPG)
![Slide07](https://user-images.githubusercontent.com/8248426/62086523-97682200-b22c-11e9-9ac2-dd5ddcca5eb1.JPG)

**Comment by GrahamR-AU** [comment]
I realise that this is off topic here, but, really? 35 slides in a 30 min Public Talk?

**Comment by AntonyCorbett** [comment]
@lazer321 thanks for the detailed report. The usual advice is to start by checking connections and cable lengths (hdmi cables should be limited to 6m). You might also check that the resolution of the monitors are set to that of the video card output. If the problem remains, then it should be possible to identify the failing component by elimination. (I assume that displaying on a monitor directly connected to the PC is ok.) Disconnect one of the 2 sdi-hdmi converters and re-test. Test with just the other converter. Swap out the hdmi cables, etc.

**Comment by AntonyCorbett** [comment]
@lazer321 if you search online for similar issues, there are some which mention a video involving transition from one colour to another, and discussion is about the hdmi-sdi converter. What make and model are you using please?

**Comment by lazer321** [comment]
Thank you both for your comments!

@GrahamR-AU  - Yea, between switching the images locally and switching the video stream between the slides and the camera shot of the podium, I was kept pretty busy that morning. :) It was a fascinating talk though, and the brother did a fine job!

@AntonyCorbett  - Yes. The hdmi cable is 1m. The converter is a Monoprice micro. Both were checked by substitution without improvement. As to the converter, specifically, switching with a Blackmagic Design unit with no effect.

I have the privilege of working with the local LDC audio-video team. (Somewhat ironically, I had just returned from a trip up north, fixing a totally dissimilar hdmi sync issue another congregation was having with the Teaching videos. - In their case, it was a marginal hdmi cable.) Hardware issues were the first ones that were eliminated as culprits.

It has been an interesting problem, both marginal and intermittent. I tried converting the images to png to see if it mattered, no effect. I even adjusted the white and black levels to make the images broadcast safe, again with no significant improvement. But once I turned off the crossfade it was rock solid.

**Comment by Spenser715** [comment]
I had a similar issue to this that we discussed in the following issue thread. Something there may help you.
https://github.com/AntonyCorbett/JwlMediaWin/issues/8

**Comment by lazer321** [comment]
@Spenser715 Thank you Spencer! I'll try that and report back. We do like the crossfade transition, so if there is a way to circumvent the issue that allows us to keep the transition in place, that would be great. 

Just as an aside, the thread mentions the Nvidia Control Panel setting to keep the resolution constant. In the Intel Control Panel, there is a Display tab and the setting to use is Maintain Display Scaling. This will lock the resolution to the value selected, regardless of content.

**Comment by lazer321** [comment]
Ok. I tried the different suggestions in the other threat to no avail. I found that swapping computers had not effect. However, slowing the crossfade down, increased the failure rate to about 50%, which was useful in that I didn't have to wait as long for it to fail.

At this point, I decided to do what you always do when you are stumped. Take a step back, (if it's a theocratic project, pray again,) and ask yourself what assumptions am I making and start proving they are valid. The false assumption I was making is that the problem has something to do with the hdmi side. I was shocked to discover that the sdi splitter was the culprit. Placing the splitter as a simple in-out device in any leg caused the issue to appear in that leg.

So that ends this little adventure. It's now up to the operating committee to decide whether the replace the splitter or run it for now without crossfade and wait to see if there are any other abnormalities. I have a feeling it's likely the latter. In any case, thank you all for your fine suggestions and being a wonderful sounding board!

**Comment by sitehost** [comment]
Greetings My brothers,we do alot of liver streaming and in setting up several congregations system, i have seen this issue happen alot, especially with the standard setup, HDMI out of the computer, to splitter to multiple monitors, even when converting it to SPI,  The issue has been the Screen refresh rate, it takes time for some of the TV monitors in the system to catch up, to fix:  Right click on Desktop, Select Monitor Resolution, Select the Monitor OUT you are using, and then click on List Modes, and select 1280x720 40hz and apply.     

Try lower refresh, rates, if your tvs are flickering then to low..  Most will have options of 40 or 60.. The lower the refresh rate, the tv monitors across splitters, will recover.  Else between changing between graphics and video, Jw Library and the TVs will go blank.

**Comment by AntonyCorbett** [comment]
@lazer321 thanks for providing feedback - it will be valuable to other users. I guess that the problem may also occur with some video content, not just image transitions, so it may be worthwhile pursuing it further. Interesting observation from @sitehost

**Comment by lazer321** [comment]
I'll try dropping the refresh rate to see if it makes a difference. In my experience, there is a definite advantage to dropping the resolution from 1080p to 720p. It reduces the scaling required as most of our source material is 720p, which can result in less artefacting and thus better quality, and it cuts the effective data rate required in half from 4.455 Gbps to 2.23 Gbps. Most of the equipment we are using locally has a max resolution of 1080p. Running at 720p gives some room for error. 

I know that 720p@60, 1080i@60, and 1080p@30 all have the same bandwidth requirements. But I have to admit I haven't tried 40 fps. See, now you have me curious again... ;)

**Comment by lazer321** [comment]
I took a look after service. On our system, there is no option for 40 fps. There is 30 and below and 59 and above, but nothing in between. At 30 fps, there was a very slight drop in the smoothness of the video, but no effect on the original issue. 

As it happens, we have two sdi feeds leaving the sound cabinet and the Monoprice converter has 2 sdi out connectors. Even though it's just using a passive network internally to split it, it seems  to work fine.
