### ISSUE TITLE
Zoom image

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyM#272]
Hi Antony,
I do not know if they have already requested it, but would it be possible to zoom the image to be projected? It would be something similar as we could do in the old SOUNDBOX.
Thank you.
Best regards.

**Comment by Tdanforth** [comment]
Hello,

This has been requested in #88. Here is Antony's reply: https://github.com/AntonyCorbett/OnlyM/issues/88#issuecomment-452242918

I keep SoundBox on the laptop as a backup and for the image zoom feature if it's ever needed.

**Comment by AntonyCorbett** [comment]
@gonzo041 Thanks for your suggestion. Please refer to the disucssion #88
