### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by sdavis5299** [AntonyCorbett/OnlyM#273]
I am able to download to only m slide manager and I can load pictures, but I have no option to play or display.

my JW Library works just fine.

I've
![only m](https://user-images.githubusercontent.com/54240699/63225598-2c5c9c00-c197-11e9-9be9-20c01bc99a1c.PNG)
 uninstalled and reinstalled and shut down and restarted my computer.

Same result.

**Comment by yjenb** [comment]
Hey sdavis5299,

the main tool is OnlyM. This is the tool, to display images, videos, pdf-files and websites. Also it can display SlideShows you generated using the OnlyM Slide Manager. So please, have a look to the main tool, I guess this solves your problem ;-)

Many love and regards,
Benjy

**Comment by AntonyCorbett** [comment]
@sdavis5299 as mentione by @yjenb you need to use OnlyM to display the slides.
