### ISSUE TITLE
Allow slide activation during video playback

### ISSUE THREAD

**Issue by crispycritter54** [AntonyCorbett/OnlyM#277]
Currently if you are playing a video the rest of the slides cannot be played. This way you cannot accidentally interrupt a playing video. You must stop the video or wait for it to end or freeze. This will cause the desktop wallpaper (year text) to appear when you stop the video. In this case during your public talk. 

A solution could be a check box in settings to allow for slides to be active allowing the video to be interrupted. This would make a smooth transition from the video back to the speakers slides. Another option might be to activate the slides if the video is paused. This would also allow for a smooth transition back to the slides.

**Comment by yjenb** [comment]
Technically I do understand your question and it might be a nice feature. But as far as I know, there is still the direction, that we should not display any moving video footage, unless directed by the organisation (except Sign Language).
So, I'm not sure in what context we could use this feature while sticking close to this direction. Can you help me, to understand it better? Thanks!

**Comment by crispycritter54** [comment]
I’m sorry I was not aware of this direction. Thanks very much for pointing it out. I was using the spinning globe as a back drop during a certain part of my talk. I’ll switch that back to a slide per the direction you have indicated.

Thanks
ajm

**Comment by AntonyCorbett** [comment]
@crispycritter54 @yjenb good point regarding the direction. I guess there may be times when the feature would be useful (e.g. using OnlyM for LDC presentations, training scenarios, etc), but it's certainly outside of the normal scope ATM so I'll close for now.

**Comment by ColinAAvey** [comment]
Hi,

Out of interest, can someone provide a reference (Date & Title) regarding the media guidelines please? I don’t have access myself although I am sure I saw a copy a couple of years ago. The question has been raised again recently here.

Thanks
Colin

**Comment by yjenb** [comment]
@ColinAAvey: there was a letter some years ago, but an Elder told me, it is also now in the Shepherd-Book and it is easy to remember: it's Chapter 20, Paragraph 20.
