### ISSUE TITLE
Accept filename argument

### ISSUE THREAD

**Issue by jomast** [AntonyCorbett/OnlyM#28]
It would be nice if OnlyM would accept a filename as an argument. This would allow:
* dragging files on to the OnlyM icon
* setting the default app for media types as OnlyM, thus allowing double clicking of files that would launch OnlyM with the file listed in the queue.

In fact it would be even better if it could accept multiple files or even directories.

**Comment by AntonyCorbett** [comment]
@jomast thanks for your feedback. I have added a command-line option to override the media folder ("/source=..."), but I won't be adding support for handling particular file extensions or opening individual media files as this complicates the design which is based on the presence of a "media folder". Thanks again! Antony
