### ISSUE TITLE
Image not projecting

### ISSUE THREAD

**Issue by HappyValleyKH** [AntonyCorbett/OnlyM#289]
With or without JWL open image will not project to target screens.

Opened JWL and OnlyM. Dropped two images in OnlyM. Neither the the image or the preset black screen will project. Updated OnlyM then uninstalled and reinstalled again. Tried shutting each program down and restarting separately. Also shut computer down and restarted. Dropped video in OnlyM and the sound would play but no image.

OnlyM version 1.5.0.19
JWL version 11.3.93
Windows 10 completely updated. (Sorry forgot to get the actual build number).

Thank you for all the hard work that goes into this project.
Bro. Stonkey

**Comment by yjenb** [comment]
Hey,

just a short question: Have you checked the Settings-Page and looked which sreen is selected? Maybe there is no screen or only a virtual screen selected? Please can you check this?

Thank you so much.

Many regards,
Benjy

**Comment by AntonyCorbett** [comment]
@HappyValleyKH Is there anything to report on the question from @yjenb please?

**Comment by HappyValleyKH** [comment]
Sorry for the delay. We've had power outages this hole week. Screen selection in JW Library is set properly. It projects properly. I do not see a setting in OnlyM. We have had a second issue come up that may or may not be related. It seems we have an issue with our HDMI Audio splitter. The tv projection pauses and skips on the projection screens. The computer itself runs fine. We have always had a problem with the TV screens flicking off and on, just for a split second. Is there a screen selection in OnlyM?

**Comment by HappyValleyKH** [comment]
Some how the screen selection did get changed and I missed the drop down menu looking through the settings. Thank You for help and hard work.

**Comment by AntonyCorbett** [comment]
@HappyValleyKH Glad it's sorted.
