### ISSUE TITLE
Português

### ISSUE THREAD

**Issue by regtec** [AntonyCorbett/OnlyM#29]
Boa tarde.
Tem previsão de traduzir para o português.
Podemos auxiliar na tradução?

**Comment by AntonyCorbett** [comment]
@regtec - thanks for your offer. I will eventually localise the applications, and will let people know about the work on twitter and facebook.

**Comment by regtec** [comment]
Qual facebook?

**Comment by AntonyCorbett** [comment]
https://www.facebook.com/soundboxsoftware/
