### ISSUE TITLE
Files not sorted alphabetically

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyM#293]
For some reason, one file (.jpg) is not alphabetically sorted by file name as it should.
Can you please check if this is an OnlyM bug or if the file has an issue?
[Files.zip](https://github.com/AntonyCorbett/OnlyM/files/3804081/Files.zip)

![Windows Explorer](https://user-images.githubusercontent.com/45002147/68123019-7fcbc400-ff14-11e9-8d46-11b586e72e43.PNG)
![OnlyM](https://user-images.githubusercontent.com/45002147/68123022-82c6b480-ff14-11e9-8a1c-96a6093287de.PNG)

**Comment by AntonyCorbett** [comment]
@LvDaniel Yes, it's an unusual bug

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for your prompt response and fix!
