### ISSUE TITLE
ONLYM-JWLIB

### ISSUE THREAD

**Issue by stevetruss59** [AntonyCorbett/OnlyM#294]
**Describe the bug**
when we have JWLIB started and have ONLYM(used for announcements on the screen before the meeting has started) we close ONLYM display and go to play the song and JWLIB crashes.

Our setup is 3 Display Units.

**To Reproduce**
1. Go to ONLYM and click on image
2. Start JWLIB
3. end ONLYM IMAGE 
4.start SONG
5.JWLIB crashes

**Desktop (please complete the following information):**
PC is Windows10
1 Projector screen and 2 TV Screens

**Comment by AntonyCorbett** [comment]
@stevetruss59 A couple of questions please: Is JWL compatibility mode enabled? Are you using JwlMediaWin?

**Comment by stevetruss59** [comment]
Hi Antony
Thanks for the quick reply. I will check these settings tonight at the hall.

Regards

Steve Truss
Senior Technical Specialist – IBM POWER SYSTEMS
Domestic and General
Tel:- +44 (0) 208 879 8558
Mob:- +44 (0) 7557743492
Email:- stephen.truss@domesticandgeneral.com<mailto:stephen.truss@domesticandgeneral.com>

**Comment by stevetruss59** [comment]
Hi Anthony 
yes settings are checked and we are usinhg jwlmediawin

**Comment by AntonyCorbett** [comment]
@stevetruss59 I can't reproduce the behaviour. Here are my actions (with JwlMediaWin running and 2 monitors connected, _Display 2_ being the media display). I'm trying to follow your description:

1. Configure OnlyM (v1.5.0.21) as follows: _Monitor_ = Display 2, _Permanent backdrop_ disabled, _JWL compat mode_ disabled (not needed with JwlMediaWin, but also behaves the same enabled).
2. Display Image from OnlyM (it appears on Display 2).
3. Run JWL (v11.3.93 (46846).
4. Note that JWL displays the year text for a few seconds on Display 2 and then JwlMediaWin "fixes" the JWL window and the OnlyM image is redisplayed.
5. Close the OnlyM image (the year text is redisplayed).
6. Start the JWL video. It plays successfully on Displays 1 and 2

Please check that I'm not missing any steps and that the configuration is as expected. I should mention that it's difficult to see how OnlyM would be the primary cause of the crash and I've not had any similar reports.

Kind regards
Antony

**Comment by stevetruss59** [comment]
Thank you Antony for looking at this. I will try to document each step as it happens and get back to you. If you have no other reports it must be a local issue.
Regards
Steve

**Comment by AntonyCorbett** [comment]
@stevetruss59 Hi. Is there anything further to report on this issue please?

**Comment by stevetruss59** [comment]
Hi Antony
Sorry for not getting back to you. I applied latest fix for soundbox and I now cannot reproduce the error.
I think this can be closed now.
Thankyou for your assistance
Regards
Steve

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AntonyCorbett** [comment]
@stevetruss59 good news!
