### ISSUE TITLE
New look -  recommendation

### ISSUE THREAD

**Issue by davono** [AntonyCorbett/OnlyM#296]
Hello,
this is a suggestion for a better app look. If you have extra time, you can be inspired.
The new look has the following principles:

![design](https://user-images.githubusercontent.com/48017820/68421612-e401b880-019e-11ea-8d17-f2d16642f300.png)

- more simplicity
- sharper edges
- more modern look (inspired by JW Library)
- new, more modern icons

Thank you for a great job. The program is perfect even for those who do not know well technical and computer programs.

Sincerely, David

[Icons.zip](https://github.com/AntonyCorbett/OnlyM/files/3821380/Icons.zip)

**Comment by AntonyCorbett** [comment]
@davono Thanks for your input and kind words. OnlyX apps currently use Google Material Design - it's fairly flat but does employ some skeuomorphism. MD is quite widespread and generally well thought of. I'd need a compelling reason to spend a lot of time changing the UI framework.

Thanks again for your feedback.
Antony
