### ISSUE TITLE
It takes several sets of "double clicks" to get OnlyM to come up on our Kingdom Hall computer

### ISSUE THREAD

**Issue by BroReeves** [AntonyCorbett/OnlyM#297]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@BroReeves I assume you are double-clicking a desktop icon to launch OnlyM. Once is all that is required unless you are not able to double-click reliably, in which case click once to highlight the icon and then press the RETURN key. If it doesn't load after a few seconds open the task manager and see if the OnlyM process has started. The application should start eventually (without the need to attempt to launch it multiple times), but if it takes a long time, review other processes in Task Manager to see what else may be happening to impede it.

**Comment by BroReeves** [comment]
Thank you brother.  We double click and the little blue circle shows then
stops and we wait and wait.  Then we try it again.  It usually starts in
three attempts but sometimes it takes another one or two.  I will check out
what you suggested.
Bob Reeves
Elko, NV  USA

**Comment by AntonyCorbett** [comment]
@BroReeves Hi. Is there anything further to report on this issue please?

**Comment by BroReeves** [comment]
Thank you brother.  We still have to try several times before the app comes
up.  I have started the app and quickly gone to task manager and see that
it is working but then suddenly it disappears and I try again.  I have done
this several times.
Bob Reeves

**Comment by AntonyCorbett** [comment]
@BroReeves Please would you send the log file?

OnlyM maintains a log (a simple text file) of activity which can be useful if you run into problems. The log is stored in the "Documents\OnlyM\Logs" folder.

**Comment by BroReeves** [comment]
Will do brother.  Tomorrow.
Thank you very much

**Comment by BroReeves** [comment]
Thank you for your patience my brother.  I found the problem.  Someone
changed the mouse action from double click to single click and didn't
inform us.  So we were stopping the app with the second click.
Bob Reeves
Elko, Nevada

**Comment by AntonyCorbett** [comment]
Thanks for clearing this up.
