### ISSUE TITLE
No sound with video file

### ISSUE THREAD

**Issue by cwlarson55744** [AntonyCorbett/OnlyM#298]
**Describe the bug**
Tonight while trying to play the video “walk in the way of safety” we had no sound using Only M
Video would play but no sound
Tried other videos they had sound
Video file would played from VLC just fine
Any ideas?

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@cwlarson55744  thanks for your report. Some additional information as follows please:
1. OnlyM rendering engine
2. OnlyM version
3. Windows version

**Comment by cwlarson55744** [comment]
I know it’s windows 10, and just downloaded the latest version of onlym, and the default rendering engine we never changed anything.
Thanks

**Comment by AntonyCorbett** [comment]
@cwlarson55744 I don't think I can be of much help with this one. I have tested on a few platforms and with a combination of settings and the audio plays fine (mwbv_E_201911_04_r720P.mp4). I have also asked around to see if anyone else has experienced the problem you describe and there have been no similar reports. My only suggestion would be to ensure that the video and audio drivers are up-to-date on your system.

**Comment by AntonyCorbett** [comment]
@cwlarson55744 There is one important difference between the audio stream on this video and that on othjer jw videos - the sample rate is 96kHz rather than 48kHz.

**Comment by evwilksjr** [comment]
Ran into this same issue. Our KH has an English and Spanish congregation. The English video played just fine in ONLY M, the Spanish file had the same problem where the video played but there was no audio. I changed the rendering engine from Media Foundation to ffmpeg and then the sound worked! The weird part is that I can duplicate the issue by switching it back to Media Foundation, but it only happens on the Spanish file. The English file continues to play just fine whether using Media Foundation or ffmpeg. Like mentioned before VLC player works fine.

**Comment by AntonyCorbett** [comment]
@cwlarson55744 @evwilksjr I believe this problem is to do with the codec used in encoding the audio. As I mentioned above, 96kHz sampling rate is used for the audio stream. The codec is the same as that used in other jw.org videos (AAC LC mp4a-40-2) but uses 96k rather than 48k. The solution is to update audio drivers or download codecs. The reason it works ok in OnlyM fmpeg mode or VLC is that the decoding is done independently of the drivers.
