### ISSUE TITLE
Audio/Video Sync Capability

### ISSUE THREAD

**Issue by edjksn** [AntonyCorbett/OnlyM#299]
Possible to add audio/video sync capability in some way? VLC currently has this feature to a limited degree. This feature will help with some downloaded streamed files that probably lack sophisticated recording.

**Comment by AntonyCorbett** [comment]
@edjksn It would take considerable refactoring to do this so I'm afriad I'll have to reject the request at this stage. Thanks for your feedback and sorry I can't be more helpful. Regards, Antony
