### ISSUE TITLE
OnlyM icon has an Administrator shield, and won't open

### ISSUE THREAD

**Issue by bcrandal** [AntonyCorbett/OnlyM#301]
Hi Brothers!
We cannot run OnlyM since an update. The OnlyM icon (both shortcut and .exe file) has the administrator shield on it and running it brings up the 'Allow this to make changes' box. Clicking "Yes" doesn't do anything, the box remains. The Slide Manager icon does not have the shield and it works fine. 

We've repeated the download and installation process (twice) but no change. Setting security properties to 'full control' made no difference.

I cannot access the log file right now, but the program does not even start, so I don't expect anything has been logged. I will request the log file, it's just that the computer is on the east coast of Canada and I'm on the west coast of Mexico (a happy story).

Thanks!
Bill

**Comment by AntonyCorbett** [comment]
@bcrandal OnlyM doesn't require elevation and I haven't heard of this issue before. However, there are many reports of similar behaviour in the online forums so it may be worth investigating there. I'll leave the issue open as others may be able to assist further.

**Comment by bcrandal** [comment]
The log files are attached.
[Logs.zip](https://github.com/AntonyCorbett/OnlyM/files/3945627/Logs.zip)

**Comment by AntonyCorbett** [comment]
@bcrandal Thanks. The most recent log file is dated June 2019. When did you begin to get this issue?

**Comment by bcrandal** [comment]
Yes, I noticed that about the log files I was sent. I would expect it has been used since June.
The issue just occurred with the last update they said, but I don't know if the update really caused the change. 
I did a remote desktop and changed security settings, but I'm not sure I looked at the "Run as Administrator" checkbox, I was focused on permissions just then. I'll get them to look at that checkbox next.

**Comment by bcrandal** [comment]
The "Run as Administrator" checkbox is now unchecked, but the file still will not run. About the log file, they tell me that the last time the software ran was back in June.

**Comment by AntonyCorbett** [comment]
@bcrandal thanks. I'll leave this open for a few weeks in case anyone can help but I suspect that there's something amiss with the environment.

**Comment by bcrandal** [comment]
I've had the Brothers uninstall OnlyM and delete its folders under Documents. Re-installation with the current .exe (1.5.0.23) has removed the shield icon, but it still does not run. The log file is empty.

**Comment by AntonyCorbett** [comment]
@bcrandal Perhaps try turning off Anti Virus before installing.

**Comment by bcrandal** [comment]
The Brothers turned off the firewall and anti-virus and re-installed, but OnlyM will still not run. The installation seems to proceed normally, and the Slide Manager works fine. The log remains blank.
[OnlyM (1).zip](https://github.com/AntonyCorbett/OnlyM/files/3969865/OnlyM.1.zip)

I will have them try to run it from a USB stick. Thanks for all your work on this software!

**Comment by bcrandal** [comment]
OnlyM is now working again. The anti-virus software was the culprit, as suspected.

Although the anti-virus software did not visibly flag OnlyM as a virus, it still wouldn't let it run. While attempting to run OnlyM from a USB stick, the anti-virus opened a window asking if we wanted to allow the program to run. This window had not appeared before. After giving it permission, it ran fine from the stick. Those same files were then copied onto the C: drive and a shortcut made. Running it from the C: drive raised the same permissions window, which was then set to allow OnlyM to run. All is well.

Thank you for your input Antony!
