### ISSUE TITLE
Audio and video not in sync

### ISSUE THREAD

**Issue by vincentllora** [AntonyCorbett/OnlyM#303]
We are in a foreign language congregation with few public speakers and we play a video talk about once a month. These videos are downloaded from JW Stream. When played with OnlyM, the audio is about 0.5 to 1.0 sec ahead of the video.

**Comment by AntonyCorbett** [comment]
@vincentllora which OnlyM rendering mode do you use please?

**Comment by Jibbs94** [comment]
@AntonyCorbett we have the same issue in our Congregation. Would it be at all possible to add an Audio desynchronization compensation option to the app to be able to make up for any delays in audio?

**Comment by vincentllora** [comment]
> @vincentllora which OnlyM rendering mode do you use please?

@AntonyCorbett I'm afraid I don't know much about the app. The computer is stored at our Kingdom Hall, so I would need to check on what you mentioned before our next meeting. Can you tell me how to check this please? Thanks!

**Comment by LvDaniel** [comment]
@vincentllora plase go to Settings and under Videos & Audio chech the Rending engine

**Comment by AntonyCorbett** [comment]
> Would it be at all possible to add an Audio desynchronization compensation option to the app to be able to make up for any delays in audio?

See #299 and #49
