### ISSUE TITLE
Option: PDF-Viewer > Start pages in full screen

### ISSUE THREAD

**Issue by tomtailor1983** [AntonyCorbett/OnlyM#304]
Option in settings: Start pages in PDF-Viewer per default in full screen. So, you don't press the button manually.

**Comment by AntonyCorbett** [comment]
@tomtailor1983 thanks for feedback. Please would you elaborate. The viewer is already shown full screen.

**Comment by tomtailor1983** [comment]
Right, the viewer is shown in full screen, but not the pages in the viewer as default. I have to press the button "enlarge to view" (i don't know the right caption - but i mean the scale button above the zooming buttons, plus and minus) in the viewer, to see only one full page per screen.

**Comment by AntonyCorbett** [comment]
Implemented in latest pre-release (see Command panel of PDF media item)

**Comment by tomtailor1983** [comment]
Thank you! 😊
