### ISSUE TITLE
IAFF

### ISSUE THREAD

**Issue by lingodingobat** [AntonyCorbett/OnlyM#306]
Trying to use IAFF audio format, and it doesn’t work. 
Currently I convert it to WAV to use. But can IAFF support be built in at all? 
Thanks for you hard work!

**Comment by AntonyCorbett** [comment]
@lingodingobat Do you mean "AIFF"?

**Comment by AntonyCorbett** [comment]
Added support for common types of AIF and AIFF audio files (available in v1.5.0.25)
