### ISSUE TITLE
language

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyM#31]
Is it planned in future updates to include different languages for the new OnlyM application, for example Spanish?

**Comment by AntonyCorbett** [comment]
@gonzo041 yes, eventually, but probably towards the end of the 2018

**Comment by AntonyCorbett** [comment]
@gonzo041 Have started localisation of OnlyT, so will mnove on to other applications shortly

**Comment by Stevo984** [comment]
I can help with translation into Slovak. My nick on Crowdin is the same as here.

**Comment by AntonyCorbett** [comment]
@Stevo984 thanks. I'll send an invitation soon.

**Comment by josslamberti** [comment]
Happy to help again with French!

**Comment by AntonyCorbett** [comment]
@josslamberti thanks. I'll send an invitation later

**Comment by AntonyCorbett** [comment]
@TizianoNoto Yes @manuelvita96 has signed up.  It's ok to have 2 or 3 assigned to a language so long as they communicate and work well together!

**Comment by TizianoNoto** [comment]
@AntonyCorbett Happy to contribute and know if the work done in my fork can be useful.

**Comment by AntonyCorbett** [comment]
@TizianoNoto thanks. Just sign up on Crowdin and let me have your Crowdin user name

**Comment by JohannesKreuzer** [comment]
@AntonyCorbett thanks for your work. I’d help with translating to German.

**Comment by manuelvita96** [comment]
@TizianoNoto possiamo tradurre insieme senza problemi, anzi se puoi dare un'occhiata anche ad OnlyT e vedere se qualcosa non torna possiamo aggiustarlo

**Comment by TizianoNoto** [comment]
@AntonyCorbett Signed in, same user name

@manuelvita96 Volentieri. Stasera ho l'adunanza quindi guarderò domani.

**Comment by AntonyCorbett** [comment]
@TizianoNoto I have sent invitation to you for the Italian translation of OnlyT and OnlyM

**Comment by AntonyCorbett** [comment]
If you want to participate in localisation, please create a Crowdin account then send me your Crowdin user name and the language you would like to work on.

**Comment by josslamberti** [comment]
@AntonyCorbett small note about the French translation: due to busy schedules, the translation work will start next week.

**Comment by josslamberti** [comment]
@AntonyCorbett I think the actual logging levels options are missing from the translation files.

**Comment by tenisak** [comment]
Hi, I can help with translation into Czech. My nick on Crowdin is tenisak.

**Comment by vangquan** [comment]
Hi, I can help with translation into Vietnamese. You can find me on Crowdin as **vangquan**

**Comment by AntonyCorbett** [comment]
@vangquan Thanks - I've sent an invitation to all 4 OnlyX projects, but feel free to pick any or all! Kind regards, Antony
