### ISSUE TITLE
OnlyM still not opening

### ISSUE THREAD

**Issue by KRJprint** [AntonyCorbett/OnlyM#313]
Hello,

I am running Parallels on a mac and after installing the latest version of OnlyM.  OnlyM will not open. I have attached my log file
[log-20200204.txt](https://github.com/AntonyCorbett/OnlyM/files/4156286/log-20200204.txt)

**Comment by AntonyCorbett** [comment]
Please would you delete the Documents\OnlyM\Database folder and try to launch again?

**Comment by KRJprint** [comment]
I did that several times . . uninstalled and reinstalled at least twice as well.

Bob Schiro
708-369-8884 C
krjgraphic@me.com

**Comment by AntonyCorbett** [comment]
@KRJprint After you delete the "Documents\OnlyM\Database" folder and the restart OnlyM, is the folder recreated? If so, what does it contain please?

**Comment by KRJprint** [comment]
It Creates an empty folder.

Robert J. Schiro
KRJ Graphic Services
1070 Star Lane
New Lenox, IL 60451
708-449-8881	
Fax 206-600-5913

**Comment by KRJprint** [comment]
Robert J. Schiro
KRJ Graphic Services
1070 Star Lane
New Lenox, IL 60451
708-449-8881	
Fax 206-600-5913

**Comment by AntonyCorbett** [comment]
Can you try running OnlyM elevated (i.e. as Administrator) please?

**Comment by KRJprint** [comment]
It asked if I wanted to allow changes to the system . . I clicked “Yes” and it still didn’t open. Database file still empty.

Robert J. Schiro
KRJ Graphic Services
1070 Star Lane
New Lenox, IL 60451
708-449-8881	
Fax 206-600-5913

**Comment by AntonyCorbett** [comment]
Is the Documents folder on a network drive?

**Comment by KRJprint** [comment]
It’s on “This PC”

Robert J. Schiro
KRJ Graphic Services
1070 Star Lane
New Lenox, IL 60451
708-449-8881	
Fax 206-600-5913

**Comment by AntonyCorbett** [comment]
@KRJprint Please would you try installing the latest pre-release? I don't have the environment to test on Mac so I'm just going on some suggestions seen in the relevant forums.

**Comment by KRJprint** [comment]
Hi Antony,

Thanks for trying to resolve this . . . is the correct build OnlyM 1.5.0.23 <https://github.com/AntonyCorbett/OnlyM/releases/tag/1.5.0.23> . . I think that is what I installed.

Robert J. Schiro
KRJ Graphic Services
1070 Star Lane
New Lenox, IL 60451
708-449-8881	
Fax 206-600-5913

**Comment by AntonyCorbett** [comment]
https://github.com/AntonyCorbett/OnlyM/releases

Select the latest pre-release.

**Comment by KRJprint** [comment]
I was able to open the program and play a video and view a jpeg file  as well as a png file. . it seems pdf files open to a blank screen. 


Robert J. Schiro
KRJ Graphic Services
1070 Star Lane
New Lenox, IL 60451
708-449-8881	
Fax 206-600-5913
