### ISSUE TITLE
Only M won't play to second monitors

### ISSUE THREAD

**Issue by kenthephoneman** [AntonyCorbett/OnlyM#316]
I went down to our Hall today to preview the midweek meeting videos and while there I went to check the OnlyM app. 
I checked the APP because I was having trouble getting our front monitors which are set up as extended monitors to see the PC feed. After a PC reboot and switching off and on our switching gear (Evolution brand switcher which feeds a simple multiport HDMI switch) things were workng fine on just the plain JW App. I even powered everything off two more times to make sure that the basic operations were OK.
I then went to the OnlyM App and found that while it loaded and would act like normal when I clicked a picture it would not play on our front monitors. All the settings were like they have been. I uninstalled it and even found an older version and on our PC and installed it but I had the same problem. I reinstalled the latest version but it still wouldn't play the pictures, I did not try a video. Both versions wouldn't work even when I didn't bring up the JW library. 
There was a Windows 10 update that loaded Sunday afternoon so I don't know if that is my problem or something else.
I have checked my home computer with win 10 pro and find that I have the same problem. It too had a win 10 update on the 12th.

Any ideas will be appreciated
Ken

**Comment by AntonyCorbett** [comment]
Did you specify the correct media monitor in OnlyM settings?

**Comment by kenthephoneman** [comment]
I selected the JW Library compatibility mode. I didn't see any other monitor option. I believe that's the way it was always set when it worked.
Ken    On Monday, February 17, 2020, 04:44:06 PM EST, Antony Corbett <notifications@github.com> wrote:  
 
 
Did you specify the correct media monitor in OnlyM settings?

**Comment by AntonyCorbett** [comment]
OnlyM requires you to specify a media monitor in the Settings page. From the guide:

Display => Media Monitor - OnlyM lists all of the display devices attached to your PC. Select the one you want to display media on.

**Comment by kenthephoneman** [comment]
I brought up the VLC app and it worked with or without the JW Library app running. I'm just not fond of it because of it's complexity when you have assistants that just can handle JW library. I say that in a nice way, I have a several good brothers that work with me.
Ken
    On Monday, February 17, 2020, 04:44:06 PM EST, Antony Corbett <notifications@github.com> wrote:  
 
 
Did you specify the correct media monitor in OnlyM settings?

**Comment by kenthephoneman** [comment]
That fixed my home problem so I'll check the Hall tomorrow. I am curious about the Hall because until I reloaded the app it had worked just fine and no one that I know of would change it.
I did have an issue with the front monitors not seeing the PC until I reset some hardware. Is it possible that OnlyM could have defaulted to no monitor in the meantime?

Either way, my home device is working so thanks for the help.

Ken

**Comment by AntonyCorbett** [comment]
If you have changed the video drivers then your monitor identification values will also have changed, so OnlyM won't recognise any of them and revert to the default (no media display). The situation is different for JWL where you can't select a secondary monitor - it authomatically chooses one for you.

**Comment by kenthephoneman** [comment]
Thanks, all I know is that everything is working now plus I'll know what to look for if it comes up again.
Ken
    On Tuesday, February 18, 2020, 03:41:26 AM EST, Antony Corbett <notifications@github.com> wrote:  
 
 
If you have changed the video drivers then your monitor identification values will also have changed, so OnlyM won't recognise any of them and revert to the default (no media display). The situation is different for JWL where you can't select a secondary monitor - it authomatically chooses one for you.
