### ISSUE TITLE
Audio and Video out of synch

### ISSUE THREAD

**Issue by anddaley** [AntonyCorbett/OnlyM#317]
Video lags behind the audio when watching talks

**Comment by AntonyCorbett** [comment]
Please search for "sync" and read the other issues. There are very many causes and possible solutions.

**Comment by anddaley** [comment]
I asume you are saying to search Github right?

**Comment by AntonyCorbett** [comment]
@anddaley Yes, search here on the issues page. There are many useful comments/suggestions. 

Kind regards
Antony
