### ISSUE TITLE
Closed issues  # 88

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyM#318]
Hi Antony:
For the elapsed time and taking into account that JWL did not implement support for images, it will now be possible to develop it in ONLYM (# 88) ?.
Sorry for the insistence, but it is a very useful tool to see the details of the photographs that the faithful slave presents for each meeting.
Thank you
Best regards
Sergio

**Comment by AntonyCorbett** [comment]
This request refers to the ability to pan and zoom displayed images. @gonzo041 Sorry, I won't implement this feature for the reasons discussed.

Thanks for your feedback.

Kind regards
Antony
