### ISSUE TITLE
OnlyM refusing to load.  

### ISSUE THREAD

**Issue by brucedungey** [AntonyCorbett/OnlyM#319]
Previously installed OnlyM simply does not load at all now.  Possibly after an update.  Not generating a log file. (documents/onlym/logs)

Have reinstalled several times with no results.

**Comment by AntonyCorbett** [comment]
Perhaps your anti malware product is interfering

**Comment by brucedungey** [comment]
I am not running one, other than properly updated Microsoft Defender or
whatever they call it now.

--------------------------------------------------------------
*BRUCE DUNGEY*
*backroom.space <http://backroom.space>*

*Australian Support*
(03) 90051760 (Melbourne)

*US & Canadian Support*
1-631-488-9439 (NY)

*Address:*
Unit 204, Macris Building, San Sebastian Lopez Jaena Sts.
Bacolod City - Barangay 31 (Pob.)
Negros Occidental, Philippines
Ph:  +639958340886 (Globe)

There is no limit to what a man can do so long as he does not care a straw
who gets the credit for it.
    ~ Charles Edward Montague (1922)

**Comment by AntonyCorbett** [comment]
Are there any Windows event viewer entries associated with it?

**Comment by brucedungey** [comment]
Yes here;

Log Name:      Application
Source:        Application
Date:          29/02/2020 1:47:03 am
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-9JQ3NFC
Description:
The description for Event ID 0 from source Application cannot be found.
Either the component that raises this event is not installed on your local
computer or the installation is corrupted. You can install or repair the
component on the local computer.

If the event originated on another computer, the display information had to
be saved with the event.

The following information was included with the event:

Could not find file 'C:\Users\bruce\Documents\OnlyM\BrowserCache'.

The message resource is present but the message was not found in the
message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-02-28T17:47:03.371091800Z" />
    <EventRecordID>21724</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-9JQ3NFC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Could not find file
'C:\Users\bruce\Documents\OnlyM\BrowserCache'.</Data>
  </EventData>
</Event>

--------------------------------------------------------------
*BRUCE DUNGEY*
*backroom.space <http://backroom.space>*

*Australian Support*
(03) 90051760 (Melbourne)

*US & Canadian Support*
1-631-488-9439 (NY)

*Address:*
Unit 204, Macris Building, San Sebastian Lopez Jaena Sts.
Bacolod City - Barangay 31 (Pob.)
Negros Occidental, Philippines
Ph:  +639958340886 (Globe)

There is no limit to what a man can do so long as he does not care a straw
who gets the credit for it.
    ~ Charles Edward Montague (1922)

**Comment by AntonyCorbett** [comment]
"Could not find file 'C:\Users\bruce\Documents\OnlyM\BrowserCache'" seems to be the problem. My guess would be that OnlyM is unable to create that folder or write to it perhaps because access rights have been hardened.

**Comment by brucedungey** [comment]
Yes, I see that thanks.  Fault in windows install system or updates.
Thanks.

**Comment by AntonyCorbett** [comment]
I'll modify the code so that this is caught and reported. Thanks for your help.

Regards
Antony
