### ISSUE TITLE
does not recognize .jfif (JPEG) files 

### ISSUE THREAD

**Issue by onefellsloop** [AntonyCorbett/OnlyM#320]
**Describe the bug**
We noticed that when we put .jfif(JPEG Interchange) files in the media folder, they do not show up in the main OnlyM window .

If we rename each of the file extensions to .jpg they then show up in the media window.
This is a quick fix but it takes time and above average computing skills. 

**To Reproduce**
1. Download a JFIF file. We noticed that these are typically exported from Google Slides or PowerPoint Online presentations.
2. Try to load them into OnlyM
3. Rename the extension to .jpg

**Expected behavior**
It would be nice if this file type were supported and would be recognized by OnlyM without modification.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 b1809
- OnlyM 15.0.23

**Comment by AntonyCorbett** [comment]
@onefellsloop Thanks. Will be available in next pre-release (today I hope)
