### ISSUE TITLE
Play .m4a audio files

### ISSUE THREAD

**Issue by JDigitalInk** [AntonyCorbett/OnlyM#322]
**Is your feature request related to a problem? Please describe.**
During the COVID-19 lockdown we are having congregation publishers record comments to be played/streamed to the congregation. Many use their Apple iPhones and iPads. Files sent are .m4a format.

**Describe the solution you'd like**
Please add support for the .m4a format

**Describe alternatives you've considered**
Currently using VLC to play. May try converting using Audacity or similar.

**Additional context**

**Comment by AntonyCorbett** [comment]
@JDigitalInk you haven't stated which version you are using but support for m4a was added 18 months ago in v1.2.0.8 Current version is v1.5.0.30

Please update and let me know if you still have problems.

**Comment by JDigitalInk** [comment]
Thank you for the response.
Hope you and family are doing well with all the concerns facing us today.

Version is 1.5.0.30 (I went ahead and reinstalled anyway, same issue)

When we place the .m4a in the folder it appears but never gets to the point
where we can play.
This happens both at the hall and on my personal computer. Files are being
created in the Voice Memos app on iphone and ipad then sent to me.

The sample file I sent is about 5 minutes, but I am having the same issue
with shorter files.
Thanks for your help

[image: image.png]
[image: image.png]

**Comment by AntonyCorbett** [comment]
@JDigitalInk Please would you send a sample file.

**Comment by JDigitalInk** [comment]
Antony,

The previous email should have had a file attached.

Here is another one.

Thank you very much.

[image: photograph]
Mike Janess
Janess Digital Ink LLC
p: 775.423.2227
e: mike@janess.net
80 S. Allen St.
Fallon, NV 89406
janessink.com
[image: facebook icon] <https://www.facebook.com/janessdigitalink>

**Comment by AntonyCorbett** [comment]
@JDigitalInk Thanks, but attachments are ignored if you reply to a GitHub issue via email. You must add them into the GitHub issue itself. Please ensure the file does not contain sensitive data.

Regards
Antony

**Comment by JDigitalInk** [comment]
That makes sense. 
My apologies. This is my first time using Github. 
File should now be uploaded. 
I placed in a .zip file so that it would be accepted.

Thanks,

[Testing.zip](https://github.com/AntonyCorbett/OnlyM/files/4364208/Testing.zip)

**Comment by AntonyCorbett** [comment]
@JDigitalInk Thanks. The log file shows the problem - OnlyM can't read the file's metadata caliming that it's missing something. I'll investigate further.

**Comment by AntonyCorbett** [comment]
@JDigitalInk Fixed in latest release

**Comment by JDigitalInk** [comment]
Thank you for fixing this issue. It is greatly appreciated.
