### ISSUE TITLE
Option to select the Audio Device for output

### ISSUE THREAD

**Issue by juninholiveira** [AntonyCorbett/OnlyM#326]
Now that we are using Zoom to conduct our meetings, we had a problem. It's impossible to use OnlyM with VoiceMeeter + OBS. To be able to broadcast the audio from a Video Player, like VLC for example, i have to change the Audio Device from the Default Option to VoiceMeeter (which acts like a virtual Mixer). The problem is that OnlyM doesn't have an option to change the audio output, so it's impossible to hear any sound from it.

The solution I see is add the option to change the output audio device. How doable is it? Thank you brother.

An example of VLC Player of changing the Audio Device.
![VLC Example](https://user-images.githubusercontent.com/10757100/78735093-4a426100-7920-11ea-857f-73f676431d87.jpg)

**Comment by juninholiveira** [comment]
Adding to the topic: I was able to make it work by changing the Default Output Device in Control Panel (Windows 10). This way, OnlyM works. Looks like it uses the default audio device. I can consider the problem solved for now, but i will leave the issue open because it would still be a good ideia to have the option to change Audio Device inside OnlyM. But you can close it if you like. Thank you.

**Comment by AntonyCorbett** [comment]
@juninholiveira Open OnlyM and then use the Windows Sound Settings applet => Advanced sound options to set the audio device for each app separately. Unfortunately, there is no way to change the audio device used in the video rendering engines used in OnlyM
