### ISSUE TITLE
Single screen with Zoom

### ISSUE THREAD

**Issue by BenElliottUK** [AntonyCorbett/OnlyM#328]
We are using an additional laptop to run media during Zoom meetings and are trying to unify the apps playing media outside JW library, hence using onlyM.

In settings we do not have the option to output media to a window, hence all media is shown full screen and we cannot see the controls to close media. This means only the first image or video can be played as we cannot stop it taking the whole display. Is there a work-around?

**Comment by AntonyCorbett** [comment]
@BenElliottUK Please use the latest pre-release version of the software

**Comment by BenElliottUK** [comment]
Sorted. Thanks. I hadn't realised that windowed was beta and I hadn't spotted the additional resources. Thanks.

**Comment by timjobutler** [comment]
#329
