### ISSUE TITLE
Transition from image to video causes videos not to play (version 1.6.0.3)

### ISSUE THREAD

**Issue by timjobutler** [AntonyCorbett/OnlyM#329]
**Describe the bug**
When an image is displayed and then a video is play (either image display is stopped first or video is played while image is displayed), the video fails to play.

**To Reproduce**
1. Play an image
2. Stop an image
3. Play a video but output window disappears
4. Press Play again and output window returns except with black screen only
5. Unable to stop video output and only method to stop is to delete the video file from the OnlyM Media folder

I tried switch from an active image to a video but the same result as listed above occurred.

**Expected behavior**
Video to play when the Play button is pressed

**Screenshots**
- Screen recording of the steps to reproduce the bug
- [OnlyM issue.zip](https://github.com/AntonyCorbett/OnlyM/files/4459146/OnlyM.issue.zip)

**Desktop (please complete the following information):**
- Windows 10 Home 1909
- OnlyM version 1.6.0.3 (pre-release version)
- [Logs.zip](https://github.com/AntonyCorbett/OnlyM/files/4459159/Logs.zip)

**Comment by timjobutler** [comment]
**UPDATE**

Videos will not play at all in this pre-release even after uninstalling and reinstalling OnlyM

**Comment by gabeluci** [comment]
I am not having any problems playing videos. I've tried various ones downloaded from jw.org. I can switch between videos and images and back without issue.

- Windows 10 Pro 1909
- OnlyM 1.6.0.3

**Comment by timjobutler** [comment]
@gabeluci Thanks for the feedback. After several restarts, OnlyM is functioning normally. Since it was a pre-release version, it seemed like a bug but simply user error 🤣

**Comment by timjobutler** [comment]
@getabc Please add your comments here

**Comment by AntonyCorbett** [comment]
@timjobutler Are you still having problems with this? You seem to indicate above that the problem is resolved. I can see the issue in the screencast you sent. I can't reproduce it.

**Comment by timjobutler** [comment]
@AntonyCorbett I am not having problems at the moment but it was very random and sporadic. I reopened this issue due to the comments @getabc made in #323.

**Comment by AntonyCorbett** [comment]
@timjobutler Is it only in "windowed" mode?

**Comment by timjobutler** [comment]
Yes. It is the only mode I use OnlyM in at the moment.


Kind regards,
*Tim Butler*

**Comment by AntonyCorbett** [comment]
This appears to be related to the known bug in Microsoft's WPF implementation when rendering to a secondary display. OnlyM uses a workaround when displaying full screen but cannot use it when the media window is in "windowed" mode. The bext fix ATM is to use FFMPEG or to use the "--nogpu" command-line switch.

**Comment by getabc** [comment]
Can we please add the workaround information to the wiki page?

**Comment by AntonyCorbett** [comment]
@getabc - added this:

NOTE: When using windowed mode, OnlyM will fail to render the H.264 video codec on some display drivers when the media window is enitrely outside of the pimary display device. This is caused by a bug in the Microsoft WPF framework and it can mean OnlyM crashes when playing mp4 files in windowed mode on a secondary monitor. If you experience this, a solution is to launch OnlyM with the "--nogpu" command-line parameter.

**Comment by timjobutler** [comment]
@timjobutler Just to clarify for my benefit:

> This is caused by a bug in the Microsoft WPF framework and it can mean OnlyM crashes when playing mp4 files in windowed mode on a secondary monitor.


I use windowed mode on my primary monitor without a secondary monitor connect. Does this bug cover this scenario as well?

**Comment by AntonyCorbett** [comment]
@timjobutler the bug only affects display of a window on a secondary monitor. Your usage is fine.

**Comment by timjobutler** [comment]
@AntonyCorbett Thanks Antony
