### ISSUE TITLE
not a real issue, a question

### ISSUE THREAD

**Issue by richfrantz** [AntonyCorbett/OnlyM#330]
I've been running dual monitors a long time, so this was never an issue for me, but a brother in my Hall, new to OnlyM, is running it from a laptop. When you display an image, the OnlyM panel is buried underneath.
How do you get it back? I could have sworn there was a key combination  to do that.

I was not able to find this answer on the wiki.

**Comment by sitehost** [comment]
Alt + tab

**Comment by richfrantz** [comment]
I know that. And that's what I told him. He said it didn't work. As we were communicating over Zoom, I have no way of knowing that he did it correctly. Let's try another question. Is there a keystroke to stop the display of an image? Which would have the same effect and bring him back to the control panel of onlym

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by AntonyCorbett** [comment]
Alt+Tab will always work. There is no key combination to close the media window (this is a precaution against accidentally closing it).

**Comment by richfrantz** [comment]
Thank you, yes. It was a training issue.  He was not "alt tabbing" correctly.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by sitehost** [comment]
More often i use teamviewer and watch the issues. It helps in training and
also troubleshooting.  Bro bret littlefield 18503870685
