### ISSUE TITLE
Media Folder

### ISSUE THREAD

**Issue by EfreAvilaJr** [AntonyCorbett/OnlyM#331]
Not really a problem but rather a question. Is there a way to change the folder where the media is located??? From the default location ("Documents\OnlyM\Media") to a Google Drive folder for example. Theres times when I've been out of town where I was emailed a pic/video to be shown at the meeting (No usb available) and I need to drop the file directly to the media folder remotely as I used to do with Soundbox.

Thx

**Comment by AntonyCorbett** [comment]
@EfreAvilaJr Yes. Please see the wiki. Regards, Antony

**Comment by EfreAvilaJr** [comment]
I apologize for my ignorance Antony, I have read the wiki but I'm unable to change it from the default location. I've tried copy/paste etc to no avail. How exactly do I change it???

**Comment by EfreAvilaJr** [comment]
How's exactly do I change it??? Sorry for my ignorance Antony.

I've tried what the wiki says to no avail, the only option in the drop-down is the default location.

Efren Avila Jr

________________________________

**Comment by AntonyCorbett** [comment]
@EfreAvilaJr Don't worry - it's not always obvious :)

In the Settings page, "Media Files" section, click the folder button next to the "Media folder" dropdown. Select the folder you want to use.

Regards,
Antony
