### ISSUE TITLE
Return to "play" Blank Screen item after video finished

### ISSUE THREAD

**Issue by supportsobaka** [AntonyCorbett/OnlyM#334]
Please implement "Return to 'play' Blank Screen item after media stopped" feature either as a checkbox in DISPLAY section next to "Include 'Blank Screen' item" or as checkbox "Resume playing this item after another one has stopped" below the Blank Screen item itself.

**Comment by yjenb** [comment]
Hey, just opt out the JW Library compatibility mode. This option is for displaying the JWL Year Text and Media while OnlyM is showing nothing. If you want OnlyM return to the Black Screen, just don't opt this function in. 😉
Many regards,
BenjyW

**Comment by AntonyCorbett** [comment]
@supportsobaka Select the "permanent backdrop" option.
