### ISSUE TITLE
Optional borderless window in windowed mode

### ISSUE THREAD

**Issue by strawberry-sundae** [AntonyCorbett/OnlyM#335]
Sharing a window on ZOOM shares the window border too.

Is it possible to add an option for a borderless media window? And could a borderless window be easily dragged around and resized?

*Currently, when sharing a media item on ZOOM with OnlyM, I’m sharing a portion of my screen, positioning the rectangle around the OnlyM media window, but inside the window border. I’m just saying that in case anyone is looking for ideas.*

**Comment by AntonyCorbett** [comment]
@strawberry-sundae Are you using the latest pre-release? It features borderless window that can be dragged.

**Comment by strawberry-sundae** [comment]
There must have been another release since I last used it. Thanks for your reply. 😅

**Comment by strawberry-sundae** [comment]
Actually, I am using the latest prerelease. I’ll have to have another look at the settings next time I use the meetings laptop.

**Comment by rdalam** [comment]
Hi, I am using version 1.5.0.31, which as far as I can tell is the latest version. The release notes say that it has the feature of a borderless window but I can't see this option in settings. Please help

**Comment by timjobutler** [comment]
@strawberry-sundae Download the setup file from [this link](https://github.com/AntonyCorbett/OnlyM/releases/tag/1.6.0.3) and tick the _Windowed_ option in **Display** settings.

See screenshot below for illustration.

![OnlyM - Windowed setting](https://user-images.githubusercontent.com/37101212/79850252-f8610700-8406-11ea-9a43-907df3081fb5.png)

**Comment by strawberry-sundae** [comment]
Thank you @timjobutler. Turns out I was using 1.6.0.2 when I created this issue. That’s why my media window had a border.

Thank you for your advice.
