### ISSUE TITLE
Force Topmost property to true for media window when running in windowed mode

### ISSUE THREAD

**Issue by jarednlivingston** [AntonyCorbett/OnlyM#337]
When running in windowed mode, other windows can inadvertently cover part of the media window, and this typically results in the content being partially blocked for remote viewers.

To prevent content from being obscured by other windows partially covering the media window, force the Topmost property of the window to true.

An alternative would be to make the Topmost property configurable (similar to the main window). 

Care would still need to be taken by users so that the main window doesn't get dragged over the media window if both have the Topmost property set to true.

**Comment by strawberry-sundae** [comment]
I agree this should be optional. On a single screen it could become an annoyance, otherwise.

Alternatively, is it possible to add an option for the media window’s _stay on top_ property to be activated **only** during media playback?

**Comment by timjobutler** [comment]
@strawberry-sundae Your suggestion:

> Alternatively, is it possible to add an option for the media window’s stay on top property to be activated only during media playback?

I love it! It is feasible to implement, this would be a huge assistance.

**Comment by AntonyCorbett** [comment]
> Alternatively, is it possible to add an option for the media window’s _stay on top_ property to be activated **only** during media playback?

@strawberry-sundae Hi. Can you elaborate on this please? It could be argued that whenever the media window is open then it is "playing" media - even if it's just an image or the black backdrop.

**Comment by strawberry-sundae** [comment]
During our meetings, I keep OnlyM (with *permanent backdrop* enabled) open behind my ZOOM window. When it is time to display media, I tell ZOOM to share the OnlyM media window. Once the empty media window is being shared, I begin video playback.

Having the media window always open enables this distraction-free method of sharing media.

During most of the meeting, enabling *stay-on-top* would make the media window a nuisance. But once I press the play button in OnlyM’s main window, I definitely don’t want something unexpected to cover the media window. So it would make sense to then enable *stay-on-top* until playback of the current media item ceases.

**Comment by strawberry-sundae** [comment]
Did my previous comment make sense?

**Comment by AntonyCorbett** [comment]
@strawberry-sundae yes, I understand the requirement. In OnlyM, media is being rendered whenever an image, video, etc is "playing". Does this also include the "Permanent Backdrop" or the "Black Screen"? In some cases users may want "stay on top" enabled in different situations. The latest release provides a "stay on top" option for the media window. In Zoom you can set up what you need by deselecting the permanent backdrop, then showing an image in the OnlyM media window and selecting it as Zoom's share. Now whenever you play media it will be shared and whenever you stop media it will pause the share.

**Comment by AntonyCorbett** [comment]
Closing now. I don't think I will be making further changes to this feature. @strawberry-sundae thanks for your help.
