### ISSUE TITLE
windowed mode not an option

### ISSUE THREAD

**Issue by jayfarr** [AntonyCorbett/OnlyM#338]
Hi, 

I do not have the tick box option for a windowed mode, this is all I have :

![onlym](https://user-images.githubusercontent.com/36538284/80607317-455b6380-8a2d-11ea-98c0-6225c8f336de.jpg)

help would be amazing and help our brothers who are using zoom from a single monitor....

many thanks

**Comment by strawberry-sundae** [comment]
Hi Brother,

As this feature is in a “pre-release” version, an update alert does not yet show in the app.

Instead, you can download the new version (1.6.0.3) from [the Releases page](https://github.com/AntonyCorbett/OnlyM/releases). This version has the feature you require.

**Comment by AntonyCorbett** [comment]
@jayfarr closing. Please see previous comment,
