### ISSUE TITLE
opening onlyM

### ISSUE THREAD

**Issue by Pault2411** [AntonyCorbett/OnlyM#341]
Recently downloaded the app, very useful for complementing JW library, trialled it with a pic, all fine.  then added the 5 min countdown timer, the app now won't open, I've checked security settings, makes no difference, I've deleted and reinstalled..  still nothing.  I can see it opening as 32 bit when I have task manager up, but it then disappears.
It did work fine, the picture I added came up on another screen, looked perfect, since then I have tweaked zoom settings, otherwise no changes.

My system is i7 920@2.67GHz 6GB Ram, Windows 10  64 Bit

**Comment by AntonyCorbett** [comment]
@Pault2411 Please would you send the log file? It is in the Documents\OnlyM\Logs folder. The likely explanation is that Windows is not allowing access to the application's database folder which is in Documents\OnlyM\Database. If this is the case then you should modify the "Controlled Folder Access" settings in Windows to allow OnlyM to access the folder.

**Comment by Pault2411** [comment]
[log-20200507.txt](https://github.com/AntonyCorbett/OnlyM/files/4592795/log-20200507.txt)

**Comment by Pault2411** [comment]
It is blocked in the area you mention Antony, but my system doesn't seem to be allowing it even after I have said to.
![snip](https://user-images.githubusercontent.com/64960969/81292668-ebc5eb00-9063-11ea-8f98-3dcca3fe9c73.JPG)

**Comment by AntonyCorbett** [comment]
@Pault2411 The log file shows that folder access is not the problem. It looks like OnlyM is crashing when it tries to convert a previously generated thumbnail image. Please would you delete the Documents\OnlyM\Database folder and its contents and then try again?

**Comment by Pault2411** [comment]
OK, removing DB didnt fix it, but then i deleted the file in media, that resolved it.  Ive subsequently tried another video (original songs music video), it too fell over and wouldnt restart until i removed it.   any ideas why?    thanks for your help

**Comment by AntonyCorbett** [comment]
@Pault2411 Please send em a link to the one of the videos

**Comment by Pault2411** [comment]
Not  sure how, I cant send it here, but it may help to say it runs on others systems, and in fact it ran on mine when i first downloaded it, so I dont think its a problem with the video file, its something that peculiar to my system.  i can manage as I have several screens, so can run another video player for the file, but it would be nice to resolve it if we can, others are using the same file without a problem.

**Comment by AntonyCorbett** [comment]
@Pault2411 I assume it's one of the JW original song videos. You're at liberty to post a web link.

**Comment by strawberry-sundae** [comment]
> @Pault2411 I assume it's one of the JW original song videos. You're at liberty to post a web link.

That a placement, ist it? 😂

**Comment by AntonyCorbett** [comment]
@Pault2411 Have you installed any other software recently, e.g. an image viewer? The error seems to be related to one of the image codecs.

**Comment by Pault2411** [comment]
Not loaded anything new since Tuesday this week when it was working.  Ist been off (still working with pics ok)   the link, I could add but its any video, tried several, I think the actual vid file would be a red herring.

**Comment by Pault2411** [comment]
Bit hectic yesterday, but I did manage to run the media ok, thankfully I have a third screen so I put a video up on there for sharing the timer.  The benefit of your software of course is that it can be used on the same screen and not knockout the JW library link.
In terms of the video, I'm sure if you linked to it, all you would say is that it works fine, so that's not the issue, hence my comment on that being a red herring.
I'd like to get onlyM working properly, I'm not sure where to look for codecs, I'll start researching, but any hints or direction greatly appreciated.  Hopefully if resolved it might be helpful for other users, It's not likely that I'm the only one affected by whatever the issue is.
Thanks for your support, much appreciated.  -  Paul Turner - Somerset UK

**Comment by AntonyCorbett** [comment]
@Pault2411 Yes, I'm sure you're right about the link. The error is an unusual one. WINCODEC_ERR_WRONGSTATE - it means that the codec may be corrupt. Have you tried several images to see if it associated with a particular image format?

**Comment by Pault2411** [comment]
Seems to be all of the ones I have, Format wise,  MP4 is the 18MB 5 minute timer, any other MP4 also won't play, AVI same thing, MOV same thing, VLC it won't recognise.  
I'm reading a lot, but so far no clear line of sight on which action to take on my system.

**Comment by AntonyCorbett** [comment]
You might try the k-lite codecs:
https://codecguide.com/download_kl.htm

**Comment by Pault2411** [comment]
Thanks for that.  Downloaded and installed the mega pack.  ran onlyM, added a freshy created in movie maker, 20 second mp4 video, saved for iphone size to keep it small..  it fell over again.  I've rebooted, still the same, have attached the log.  I've completely removed the documents folder too.
[log-20200508.txt](https://github.com/AntonyCorbett/OnlyM/files/4601065/log-20200508.txt)
I've downloaded a fresh copy, and the same situation occurs, no issues until I load a video.
I'll copy another log over.  
[log-20200508.txt](https://github.com/AntonyCorbett/OnlyM/files/4601086/log-20200508.txt)

**Comment by Pault2411** [comment]
just as a nail in the coffin of the file being a problem, I've also tried with this weeks "Are you prepared for natural disasters video, I can get to it in windows 10 videos in file explorer, its mp4, 1208*720 1486/1608kbps 29.97 franes/second 2 channels...

**Comment by AntonyCorbett** [comment]
@Pault2411 Does the "Are you prepared video" play or not?

**Comment by Pault2411** [comment]
Sorry No..  I wish..

**Comment by Pault2411** [comment]
Also, just another thing to scrub off the list, I've run through a load of updates on my windows 10, so its all up to date. 10.0.18363   again, rebooted, deleted onlyM & document files, re downloaded.  same problem.  I've attached a view of codecs showing on video..   thanks in advance.   P
![snip](https://user-images.githubusercontent.com/64960969/81447596-da203880-9174-11ea-9009-94a27af2f423.JPG)

**Comment by AntonyCorbett** [comment]
Try turning off the controlled folder access completely.

**Comment by Pault2411** [comment]
Tried that this  morning but sadly, no change, same problem.  Thanks for trying though, any other suggestions gratefully accepted.   I hate to ask, but is there another 'library compatible' product out there?  thanks

**Comment by AntonyCorbett** [comment]
The JwlMediaWin tool will tame the JW Library media window making it easier to use VLC and other media players.
