### ISSUE TITLE
Videos recorded in portrait/vertical are auto-rotated to landscape/horizontal

### ISSUE THREAD

**Issue by findel** [AntonyCorbett/OnlyM#342]
We've recently been accepting some comments as pre-recorded videos which can be played on zoom if the participant can not themselves join zoom. We've noticed an issue with OnlyM that if the video is recorded in portrait, that when OnlyM plays it, it rotates it to horizontal which means the brother/sister commenting is sideways. 

**Expected behavior**
Could this be an optional setting to stop it from happening when we don't want it to?

**Desktop:**
 - Windows 10
 - Using OnlyM to play on a second screen and only sharing that screen via Zoom.

**Comment by AntonyCorbett** [comment]
@findel Yes, this is a problem with the Media Foundation engine which plays the video as it is presented without taking into account the embedded rotation data. They should play ok if you choose the FFMPEG rendering engine.

**Comment by findel** [comment]
@AntonyCorbett That's great, thank you. I've just tried that and it works as described. 

I'm sure there's probably a very good reason for "Media Foundation" to be the default rendering engine, but if not, maybe it would be worth considering making FFMPEG the default.

**Comment by AntonyCorbett** [comment]
@findel Media Foundation is more performant.

**Comment by AntonyCorbett** [comment]
@findel - fixed in latest pre-release

**Comment by findel** [comment]
@AntonyCorbett Thank you for the ping. 😄
