### ISSUE TITLE
Comandi durante la riproduzione

### ISSUE THREAD

**Issue by AlainDema** [AntonyCorbett/OnlyM#345]
Buon giorno è possibile avere i comandi nel video proiettato, usando un solo monitor se si avvia la riproduzione di un video i comandi scompaiono e diventa difficile recuperarli in breve tempo. Specialmente il problema si presenta se viene utilizzato il programma Zoom Meeting che purtroppo non riconosce durante la condivisione dello schermo la funzione estesa sul secondo monitor (stessa cosa avviene se con il programma Zoom si vuole proiettare l'estensione di Jw Library) automaticamente scompare l'estensione e rimane lo sfondo dello schermo

**Comment by AntonyCorbett** [comment]
@AlainDema I am closing the issue now. Please feel free to reopen if the comments of @Nickyes didn't answer your query.
