### ISSUE TITLE
Can't turn off Always On Top

### ISSUE THREAD

**Issue by JamesSwift** [AntonyCorbett/OnlyM#347]
The main control window is always on top, regardless of what state the setting is in. I have tried restarting the application. Is this a regression?

**Comment by AntonyCorbett** [comment]
@JamesSwift No. The behaviour is unchanged, The wiki states: 

"Miscellaneous => Main window always on top - If checked, the OnlyM window remains on top of others. Note that OnlyM automatically remains on top when media is being displayed."

So if the media window is open then the main window stays on top.

**Comment by JamesSwift** [comment]
In fullscreen mode, without jw library compatibility, when no media is being displayed, the main window still remains on top. This may be due to the `Permanent backdrop ` mode being enabled.

Can I suggest that this behaviour is undesirable. If you uncheck the by-default-checked `Miscellaneous => Main window always on top` option, then you would expect to be able to bring other windows to the top.

**Comment by AntonyCorbett** [comment]
The rationale is two-fold. 
1. When OnlyM is rendering content (even a black screen) you need ready access to the application to remove the content.
2. If the application window is not on top there is a danger that the media window  (which is on top) may be displayed over part or all of the application window making it impossible to access the application window quickly (there's no way to bring it to the top).
