### ISSUE TITLE
only M settings

### ISSUE THREAD

**Issue by geostanko** [AntonyCorbett/OnlyM#348]
when I'm using Pause in OnlyM it happens freeze of video content so JW Library don't work, ie video file from JW Library is not showing...this has not happened before ! should I change settings ? thank you and greetings to you *

Laptop Lenovo V155
 - Windows 10

**Comment by geostanko** [comment]
I have disabled Pause in settings and now it works correctly...

**Comment by AntonyCorbett** [comment]
@geostanko Thanks for reporting back. I would suggest you try using JwlMediaWin if you get further issues: https://github.com/AntonyCorbett/JwlMediaWin

**Comment by geostanko** [comment]
thank you for answer b.Antony  greeting from Croatia 

    On Sunday, May 24, 2020, 4:43:05 PM GMT+2, Antony Corbett <notifications@github.com> wrote:  
 
 


@geostanko Thanks for reporting back. I would suggest you try using JwlMediaWin if you get further issues: https://github.com/AntonyCorbett/JwlMediaWin
