### ISSUE TITLE
OnlyM refuses to play any video on KH laptop

### ISSUE THREAD

**Issue by David-in-Taiwan** [AntonyCorbett/OnlyM#350]
**Describe the bug**
We have had and used OnlyM on our KH laptop (an Asus) since it was released, and have no problem showing images. But it has never ever been able to play a video. We have Windows 10, fully updated, and OnlyM latest version. We are in Taiwan so normally the laptop uses Chinese Traditional version Windows., but I have tried it set to English Windows using English file names, same result. The same videos will play no problem on my laptop at home (also an Asus).
When you drag a video either onto OnlyM or into the cache folder, the video timeline immediately moves to 100% and the spinner keeps spinning. The only way to stop it is to delete the file from the folder. Same happens with every video large or small, whatever the file name, ie English or Chinese.
Please suggest any other tests or information I can give you. Would really appreciate your help!
![72293](https://user-images.githubusercontent.com/65818033/82732975-3ffaeb80-9d43-11ea-968b-217bafd69810.jpg)
[72292.zip](https://github.com/AntonyCorbett/OnlyM/files/4671907/72292.zip)

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
Further info on the problem - the log file shows repeated "VideoFileInUseException" exceptions (from MediaMetaDataService line 88). This is while OnlyM is trying to open the file to read meta data (video duration, etc). However, no processes appear to have the file handle open. The original exception is raised by Unosquare.FFME.MediaEngine.RetrieveMediaInfo (line 69 in the same source file).

**Comment by AntonyCorbett** [comment]
@David-in-Taiwan - did you manage to try it using an account name with English characters as suggested?

**Comment by David-in-Taiwan** [comment]
I've finally had time, just been to the hall, added another user account using just English characters. I opened OnlyM, copied a small mp4 video from a USB drive into the OnlyM folder, and it saved and played no problem. I then changed to the usual KH user, did exactly the same, copying the same file into OnlyM, but it faulted again (wouldn't finish copying, just the spinner continuing to spin. This was without first opening any other programs, not even JWL. So your hunch seems to be correct! Now we just need to know why. I wonder if any other congregations in non-English languages have had a problem? Thank you!

**Comment by AntonyCorbett** [comment]
Just to document the source of the bug: 

There is a bug in fmpeg (https://trac.ffmpeg.org/ticket/819) and I have a workaround (FFmpegUtils.FixUnicodeUri). This workaround causes the issue experienced with some file names.

**Comment by David-in-Taiwan** [comment]
Hello Antony,

Thanks for keeping working on this, and for letting me know you found 
the answer. There's no rush of course, as we're not using the hall at 
all at the moment, but what do I need to do? Is the instruction on your 
Github site?

Actually, as I told you, there's no problem on my laptop, so the last 
time I did the AV from home for Zoom, I used OnlyM instead of JWL and 
found it much easier!

Hope you're keeping safe and well!
David

------ Original Message ------

**Comment by AntonyCorbett** [comment]
The FFMPEG issue  (https://trac.ffmpeg.org/ticket/819) has been fixed and so I have backed out my workaround (FFmpegUtils.FixUnicodeUri).

**Comment by timojinking** [comment]
Brother Corbett. I had this same issue with our KH machine. Our setup consist of 4 big screen tv's and 1 small tv and an ultra wide monitor. We are using HDMI splitters. We have an HDMI switch that has to be on in order for OnlyM to pick it up. It was not active. So it appeared that the Application wasn't working. It actually was user error. I would direct our Brothers to make sure they are looking in the settings to first see which monitors are showing up there. If they don't see all the monitors or the HDMI splitter located in there, then they need to turn on the HDMI splitters and monitors for the computer to register them in the allotment of Display monitors to choose from.
![ONLYM](https://user-images.githubusercontent.com/61660270/236932204-d07ee26f-6b5f-45a7-860a-bc6f398696fc.png)
