### ISSUE TITLE
Support for subfolders inside Media folder

### ISSUE THREAD

**Issue by rguerreiro** [AntonyCorbett/OnlyM#351]
**Is your feature request related to a problem? Please describe.**
To me personally, sometimes, it would very helpful to have my videos distributed between folders, specially when I need to show the same videos in several meetings, over and over.

**Describe the solution you'd like**
This could be an option enabled in the settings. The UI could be the same but have a "+" sign that collapses when clicked, when the program founds a folder.

**Describe alternatives you've considered**
I need to keep copying and pasting the videos before each meeting. Having all the videos together isn't an option.

**Comment by AntonyCorbett** [comment]
@rguerreiro Thnaks for your suggestion. Please see #14
