### ISSUE TITLE
Vertical red line in the middle of display

### ISSUE THREAD

**Issue by djbillyd9849** [AntonyCorbett/OnlyM#355]
Today, and only today, I was setting up for the midweek meeting, and there is a red line, in the middle of the screen, vertically. It isn't in the monitor, or the system. I have 4 monitors and the red line goes with OnlyM. What is that, and how can I remove it?

![Screenshot (31)](https://user-images.githubusercontent.com/59811816/89853516-379e9980-db57-11ea-979f-31f8a31594fc.png)

**Comment by AntonyCorbett** [comment]
@djbillyd9849 You don't say whether it is only when playing videos or if it is also shown when rendering other media. I'm guessing video only. This is likely a video driver issue and there are questions about it on various tech forums, e.g. https://borncity.com/win/2017/02/13/video-playback-shows-a-vertical-redgreen-line/
