### ISSUE TITLE
Unable to Drag-and-Drop Media Files

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyM#358]
I am using version 1.6.0.6 of OnlyM. My OS is Windows 10 version 1909. When I attempt to drag any type of media file (.jpg, .mp4, etc) from my Desktop into OnlyM, a message appears in the application stating "There was an error!" After that, when I open the OnlyM Media folder in my Documents, I notice random files with invalid extensions. I notice that a new random file is generated each time I attempt to drag-and-drop a media file into OnlyM. I attached screenshots for your reference. If I put my media files directly into the OnlyM Media folder in my Documents, they appear in OnlyM normally, and I am able to play them. The issue only occurs when I try to drag-and-drop them into the application.
![Error Message](https://user-images.githubusercontent.com/46166330/94330381-102e4f80-ff92-11ea-87cc-71d1c8228b64.jpg)
![Invalid Files](https://user-images.githubusercontent.com/46166330/94330402-3ce26700-ff92-11ea-9112-a54fdce36a9a.jpg)

**Comment by AntonyCorbett** [comment]
What does the log say please?

**Comment by scottys94** [comment]
I checked the Logs folder, but the last file is from July. No other logs have been captured since then.
![Log Files](https://user-images.githubusercontent.com/46166330/94344877-6f22b180-fff0-11ea-96a6-e9365f93b809.jpg)
[log-20200711.txt](https://github.com/AntonyCorbett/OnlyM/files/5286947/log-20200711.txt)

**Comment by AntonyCorbett** [comment]
@scottys94 If there are no logs files it sounds like Windows controlled folder access has been enabled for OnlyM. That would also explain the problem of being unable to drag and drop.

**Comment by scottys94** [comment]
Sure enough, the problem was coming from my Avast Anti-Virus. When I disabled it and re-opened OnlyM, I was able to drag-and-drop media files into it. The log files are also being generated now. Very interesting - I wonder why Avast would start blocking the app all of a sudden. But thanks very much Antony for your help in isolating this issue.
