### ISSUE TITLE
GoTo Time

### ISSUE THREAD

**Issue by KovalevArtem** [AntonyCorbett/OnlyM#360]
![VLC_-_go_to_time](https://user-images.githubusercontent.com/36500228/94416358-6b756300-0187-11eb-80e6-e63900b177a1.png)
I would like to have a feature that is implemented in many video players (including VLC - Ctrl+T).
Go to the desired point on the timeline ...

**Comment by AntonyCorbett** [comment]
![image](https://user-images.githubusercontent.com/24551146/94420829-9efec000-017c-11eb-9412-f21499461390.png)

Does the existing OnlyM "Media Start" function help?

**Comment by AntonyCorbett** [comment]
Just make sure "Allow position seeking" is checked. Then click the Ellipsis next to the display video duration.

**Comment by AntonyCorbett** [comment]
@KovalevArtem I assume this answered your question so will close the issue. Please get back to me if needed.
