### ISSUE TITLE
How do I remove the OnlyM Green Outline when sharing screen in Zoom

### ISSUE THREAD

**Issue by erskinerobin** [AntonyCorbett/OnlyM#362]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AntonyCorbett** [comment]
@erskinerobin You don't say if the green outline appears locally or on the remote zoom screens. If locally, there is a zoom setting (Share Screen => Advanced => Show green border around the shared content)
