### ISSUE TITLE
Only M wont play any videos

### ISSUE THREAD

**Issue by JavierO-1** [AntonyCorbett/OnlyM#364]
**Describe the bug**
I being using Only M for a few months now and it was working perfectly until recently. It won't play any videos it won't let me click on the play button to start the video I tried uninstalling the program and installing it again but still doesn't work I'm not sure what the problem can be any ideas?
**To Reproduce**
3. See error

**Expected behavior**
Grammarly is Now Active

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@JavierO-1 If the Play button is disabled you probably have no Monitor specified in Settings => Display

**Comment by AntonyCorbett** [comment]
@JavierO-1 I assume this fixed the issue, but please get back to me if needed.

**Comment by JavierO-1** [comment]
Hello! Yes the issue was fixed thank you so much for your help I can't
believe it was that simple i was trying for about 3 days to figure it out
😂 I'm sorry I forgot to respond to your message thank you again keep up
the good work!
