### ISSUE TITLE
OnlyM will not start on surface pro 6

### ISSUE THREAD

**Issue by SaolDan** [AntonyCorbett/OnlyM#367]
**Describe the bug**
V 1.5.0.3 works but anything newer will not run on a surface pro 6. It wont load. 

**Expected behavior**
start program

**Desktop (please complete the following information):**
 - Windows 10 Pro 19041.572

**Comment by AntonyCorbett** [comment]
@SaolDan Thanks for the report. It may be your anti-virus tools (either preventing a correct download of the installer or preventing it from running). It may be worth trying without. Failing that please would you post the log file? Thanks, Antony

**Comment by AntonyCorbett** [comment]
@SaolDan I will close for now as there is no further response. Please feel free to reopen if necessary.
