### ISSUE TITLE
Suggestion and other

### ISSUE THREAD

**Issue by JWprogrammer** [AntonyCorbett/OnlyM#37]
Hello, dear brother! :) Thanks for your work! SoundBox was the best application! Thank you for making new applications (for guidance in a letter from the brothers).

There is a suggestion: Combine into one in the future three applications (OnlyT, OnlyR, OnlyM).

And another suggestion: add in OnlyM the ability to delete files from the list directly in the application (without opening the folder)

I have already translated OnlyM into my language.

When you need help in translating programs into Russian and Ukrainian languages, then please contact.

email: dyatsura1@gmail.com
phone: +380685240684

:)

With love
Brother from Ukraine
Beginner programmer (Html ​​/ Css, JavaScript / jQuery, C# (WinForms, WPF))
Dan Yatsura (13 years old)

**Comment by AntonyCorbett** [comment]
@JWprogrammer thanks for your feedback and kind words about SoundBox! @Blann has responded to some of your suggestions. Regarding language translation, I hope to get started in the next few months and will alert brothers via facebook and twitter. Thanks for your willingness ro help.

Kind regards
Antony
