### ISSUE TITLE
Main window always on top bug

### ISSUE THREAD

**Issue by samuelmacdg** [AntonyCorbett/OnlyM#370]
**Describe the bug**
The main window stays always on top even after the setting is unticked.

**To Reproduce**
1. Go to Settings
2. Untick 'Main window always on top' under Miscellaneous.
3. Main windows still stays on top of other windows no matter what.

**Expected behavior**
The main window should go under other windows.

**Screenshot**
![image](https://user-images.githubusercontent.com/58158209/102007315-e1d73980-3d62-11eb-86dc-1cc010198798.png)
The main window is still on top even though the browser is the one in focus and 'Main window always on top' is unticked

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎9/‎12/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by AntonyCorbett** [comment]
@samuelmacdg You are probably rendering OnlyM media. From the wiki:

"Miscellaneous => Main window always on top - If checked, the OnlyM window remains on top of others. Note that OnlyM automatically remains on top when media is being displayed."

**Comment by samuelmacdg** [comment]
Thank you for the response. No media is being played at the time but it might be rendering the media window which I've to always be displayed. Thanks again for the great work. We highly appreciate it.

**Comment by AntonyCorbett** [comment]
Yes, if the media window is open then that will enforce the "on-top" behaviour. I'll close the issue for now. 
Regards, Antony
