### ISSUE TITLE
OnlyM stuck when playing same video twice

### ISSUE THREAD

**Issue by HP2H** [AntonyCorbett/OnlyM#377]
**Description**
When playing the same video twice, the second time the media screen becomes blank and no video is played, while onlyM shows that the video is playing.

**To Reproduce**
1. Play a video and wait until it ends / stop it
2. Play the same video again
3. OnlyM is now stuck

**Screenshots**
Here is a video showing the issue:
https://youtu.be/7WT1VLX_x5g

**Desktop (please complete the following information):**
 - Windows 10 20H2
 - It was fine until today. I did not change anything meaningful on my PC.
 - Same bug happens to another brother (OnlyM never worked correctly for him)

**Comment by AntonyCorbett** [comment]
What version of OnlyM please?
Is the rendering mode Media Foundation or ffmpeg?
Does it work ok if the media window is displayed on the main monitor?

**Comment by HP2H** [comment]
Version 1.6.0.6
Rendering mode was on Media Foundation. I put it on ffmpeg and it is working properly now, thank you very much for pointing that out!

**Comment by AntonyCorbett** [comment]
This is caused by a documented Media Foundation bug and has been reported here several times. It would be good if we could get a fix for it! Sorry for your inconvenience.

**Comment by HP2H** [comment]
Glad to know there is a simple and easy workaround. Keep up the good work!
