### ISSUE TITLE
Can't display on 2nd screen after 20H2 Win10 update

### ISSUE THREAD

**Issue by philscotland** [AntonyCorbett/OnlyM#384]
Hi Antony
I am on a Dell E7450 laptop.
Run the Zoom meetings with a dual-screen setup to offer a cleaner experience, similar to what we did at the hall. 
Has an Nvidia 840M and an integrated Intel 5500 GPU.
Before, you could select in Nvidia control panel where you wanted to run an application. This has now changed and it is done in Windows. I suspect the issue could be in there. 
Windows 10 Pro, just patched to the 20H2 release - that is what triggered the problem. 
Run OnlyM 1.6.0.6.
Used OnlyM successfully for a while now, never had any problems. 

When I try to display something on the 2nd screen, it just doesn't. If I run in Windowed, I can get a window to display on the second screen. 
The big issue though is, I don't get the Display => Media Monitor selection box anymore even though I have both screens attached and they are working correctly.
If I press  FN-F8 button on my Dell, it correctly displays the various options with Extended selected, so this looks all ok. And as mentioned above, the JW library displays on the 2nd screen. 
I am a bit stuck here, don't really know what to do next. 
Any help with this would be greatly appreciated as I don't want to loose this highly valuable tool.
Thanks very much for your help.
Warm regards
Phil

**Comment by AntonyCorbett** [comment]
@philscotland It sounds like OnlyM is not detecting the second monitor. Please would you send the log file? Documents\OnlyM\Logs

**Comment by philscotland** [comment]
> @philscotland It sounds like OnlyM is not detecting the second monitor. Please would you send the log file? Documents\OnlyM\Logs

Hi Antony
please accept my slow reply, I have been a bit busy over the last few days as we all were I guess.
I did a full review of the HW issues I was experiencing after the 20H2 and realised that there were some fundamental issues with the whole graphic setup. This was certainly not caused by OnlyM. Not much worked properly anymore, sometimes I couldn't even find the external screen even though it was plugged in. 
So, despite this being a rather old laptop, I checked the Dell website and indeed found a new Intel video driver set and a new BIOS. I am pleased to say that after the BIOS update, OnlyM was able to see my 2nd screen again which is fab.
I will need to do some further testing to see if I can trust this setup for meeting hosting again, but I believe I am on the right track.
Thanks for your help and your great little program. Your hard work is very much appreciated.
Kind regards
Phil
