### ISSUE TITLE
in mode windowed : "OnlyM Media window" close when video set to 00:00:00..

### ISSUE THREAD

**Issue by georges-fr** [AntonyCorbett/OnlyM#385]

**Comment by AntonyCorbett** [comment]
@georges-fr Do you still need help with this? I notice the title has been deleted

**Comment by georges-fr** [comment]
Hi Antony,
Thank you for your mail.
In fact, i still need help, but i wasn't shure to use the good procedure, so i have deleted my message

The problem i have :
I  and use OnlyM in windowed mode with zoom.
For images, it'ok. I can start image in window, then use it with zoom.
For video, if i want to preset the file to the begining, the window close automatically.

1- I start the vidéo : file is displayed in window
2- I pause the vidéo : The window is still active
2- I move the cursor to begining 00:00:00 . The video stop and the window is closed.

Question : Is it possible to start the video in windowed mode and preset it to 00:00:00 with the window still active ?

Thank you for your help.
Best regards
Georges

**Comment by AntonyCorbett** [comment]
@georges-fr Sorry for the delay in responding. Have you tried the "Permanent backdrop" option in the Settings => Display section? (Ecran noir permanent). Does that help?

**Comment by georges-fr** [comment]
I tried this option.
It works fine.
Thr "OnlyM Media window" keeps active anytime.
Thank you for your help.
