### ISSUE TITLE
Blank Screen Resize Issue

### ISSUE THREAD

**Issue by Harbspan** [AntonyCorbett/OnlyM#392]
System is Windows10 on Surface Pro4 with external monitor as extended display. 

I use OnlyM on laptop screen with "Blank Screen" enabled. When using "Zoom" it is displayed on external monitor. 

**Expected behavior**
Normally, prior to starting a "Zoom" session, I load media into OnlyM. With OnlyM running on laptop screen, I select "Blank Screen" "Play" button. A small blank screen appears at top left of laptop screen. I then select and drag this onto the external monitor and resize to suit. I then select the "Stop" button on the "Blank Screen" in OnlyM to close the blank screen. Thereafter when on zoom I can share media using the blank screen feature and not have distracting desktop task bars and other icons appearing on my shared screen.

**Describe the bug**
I have noticed since last windows10 update (July 6, 2021—KB5004945) that the "Blank Screen" function is not behaving as usual. When I select the "Play" button in OnlyM, the laptop screen goes to full blank screen with no way to be able find corners to resize and can not select and drag onto external monitor no matter where I click or try to select. Thus all other functions I have for running Zoom on the laptop screen are hidden under the blank screen. I uninstalled and reinstalled OnlyM, but nothing has changed.

**Comment by AntonyCorbett** [comment]
@Harbspan can you confirm that "Windowed" mode is still selected in OnlyM Options => Display?

**Comment by Harbspan** [comment]
Hi Antony. Yes it is. That's one of the first things checked.
LesH.



Sent from my Samsung Mobile on the Telstra Mobile Network



-------- Original message --------
From: Antony Corbett ***@***.***>
Date: 13/7/21 11:54 pm (GMT+10:00)
To: AntonyCorbett/OnlyM ***@***.***>
Cc: Harbspan ***@***.***>, Mention ***@***.***>
Subject: Re: [AntonyCorbett/OnlyM] Blank Screen Resize Issue (#392)


@Harbspan<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHarbspan&data=04%7C01%7C%7C071429716a40485b5cb708d94605c7ef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637617812927550729%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2pCXPTFnPtHtZk%2F%2FdwpMVKVzIaBiG%2BinhVo9BHtViL0%3D&reserved=0> can you confirm that "Windowed" mode is still selected in OnlyM Options => Display?

**Comment by AntonyCorbett** [comment]
@Harbspan Thanks. I can't reproduce the problem (I have KB5004945 installed). What version of OnlyM are you using please? Would you send a copy of the log file, please?

**Comment by Harbspan** [comment]
Hi Antony.
Thanks for following this up for me. Just tried it again with song 38  same problem. Blank screen opens full frame on my laptop screen but cannot move resize to external monitor. Song plays full frame on laptop only.
Version is 1.6.0.6
Log file attached.

LesH.

**Comment by AntonyCorbett** [comment]
@Harbspan Sorry, I should have asked you to adjust the logging level first - In Settings, Miscellaneous, please set the Logging level to "Verbose" and then send me another log file.

**Comment by Harbspan** [comment]
Here you go...
LesH.

**Comment by AntonyCorbett** [comment]
@Harbspan Please would you let me have a copy of your options.json file? It contains your settings and is found in the following folder:

`%AppData%\OnlyM\1`

Also, please indicate the pixel resolution of your monitor.

Thanks for your patience!

Regards
Antony

**Comment by Harbspan** [comment]
Hi Antony.

Here's the info.

Laptop screen is 12.3 inch 2736x1824 pixels.
Monitor is HP 24MQ 23.8 inch 2560x1440 pixels.

Hope that helps.

LesH.

**Comment by AntonyCorbett** [comment]
@Harbspan Thanks. The options,json file is missing.

**Comment by Harbspan** [comment]
Sorry Antony...but it is attached on my end here. Just checked my sent folder and it is there and opens ok???
Will try again here.

**Comment by AntonyCorbett** [comment]
@Harbspan - that file type is not supported for upload on the GitHub issues page. Please rename it options.txt

**Comment by Harbspan** [comment]
OK...Here we go. Hope this works.
LesH

**Comment by AntonyCorbett** [comment]
@Harbspan The screen coordinates for the media window are out of range but you still be able to drag the window with the mouse and then resize it. Failing that, please try deleting the options.json file or editing the media window placement entry as follows:

`  "MediaWindowPlacement": "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><WINDOWPLACEMENT xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><length>44</length><flags>2</flags><showCmd>3</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>100</Left><Top>100</Top><Right>500</Right><Bottom>600</Bottom></normalPosition></WINDOWPLACEMENT>",`

**Comment by Harbspan** [comment]
Hi Antony.

Still trying, here’s what’s happened.
1/ I cannot select and drag the window from deskop on laptop to external monitor to resize, just nothing happens.
2/ Deleted the options.json file but as soon as I open OnlyM it creates a new one.
2/ Tried deleting and replacing with the new options.json file, but as soon as OnlyM is opened again it overwrites with a new one with the same operating issues.

Les Harbour.

**Comment by Harbspan** [comment]
Huh... In desperation I repeated something that I did in the outset before raising the issue. I uninstalled OnlyM... and reinstalled again (Same version???). Bingo!!! It's now working as before perfectly.

Thanks for persisting Antony.
LesH. (Harbspan)
