### ISSUE TITLE
Manual Fixed window size allows v large size

### ISSUE THREAD

**Issue by AntonyCorbett** [AntonyCorbett/OnlyM#397]
The Media window "fixed size" mode allows you to enter very large numbers that crash the application.

**Comment by drothmaler** [comment]
Good Point... What do you think would be a reasonable max. size? 8192 x 6144 would be 4:3 8K (don't think anybody will ever need more than 1080p, but you never know...

**Comment by AntonyCorbett** [comment]
@drothmaler Yes, that sounds reasonable. Would you like to have a go at it please?
