### ISSUE TITLE
Slide show titles not displaying in Only M 2.0.0.8

### ISSUE THREAD

**Issue by Gaza84** [AntonyCorbett/OnlyM#402]
Hi, 

first of all thank you so much fo your invaluable tools!! they are a tremendous help. 

i have just updated to the latest version on Only M (2.0.0.8) and i am noticing that the file name is no longer displaying in the Only M window for slideshow (.omslide) Files, ive attached a comparison between the old and new versions of the application. 

![Only M](https://user-images.githubusercontent.com/79219893/128615528-a7d340c6-30a4-429b-a85d-e0c893c12918.png)

i did install microsoft windows desktop runtime x86 5.0.8

please let me know if you need more info. 

thanks, 
Garth

**Comment by AntonyCorbett** [comment]
@Gaza84 Thanks for the bug report. Now fixed.

**Comment by Gaza84** [comment]
Thank you its working wonderfully now :)
