### ISSUE TITLE
Fade Out/In Image to Video

### ISSUE THREAD

**Issue by Flasher404** [AntonyCorbett/OnlyM#410]
**Describe the bug**
After install v2.0.0.9 noticed a switching glitch.  When showing an image and attempting to click and fade and play a video, sometimes the video fails and screen reverts to background.  Click image and sometimes it fails again requiring a third click to get the video playing.  This is intermittent, sometimes it works.

**To Reproduce**
1. Go to 'display an image'
2. Click on 'video image button below'
3. See error 'fade-out smooth but video fails to play (intermittently)

**Expected behavior**
Expect a clean fade-out of image and immediate playing of video occurred
on previous version before update to 2.0.0.8 and 2.0.0.9.  Since video starts
quickly, one cannot very well start, freeze, share screen, then play.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 21H1 Build 19043.1083  on  Dell Inspiron 3847
 - Other important information about your environment
Two monitors, Samsung 27" hdmi (No.1), Viewsonic VA2055 20" vga (No.2)
Displaying onlyM menu on screen 1 and shared content on screen 2.
Also, because of screen real-estate and running Zoom on screen 1,
I run JWLibrary on screen 2. Not had any conflict before so didn't
see the need to have screen 2 blank (because able to use the
blank item then click to play video).

**Comment by AntonyCorbett** [comment]
@Flasher404 Thanks for the report. I haven't been able to reproduce the issue. Some questions:

1. What is the Images => Fading Style?
2. What is the Videos & Audio => Rendering Engine?
3. Does a change in any of the above settings fix the problem?
4. Do you experience problems when you manually "stop" an image before starting the video?
5. If the media window is rendered on your primary monitor, does this fix the problem?
6. Can you supply a log file associated with the issue?

Thanks for your help.

**Comment by AntonyCorbett** [comment]
@Flasher404 Closing for now, but please reopen if you can respond to the questions. Thanks.
