### ISSUE TITLE
Sideways Images

### ISSUE THREAD

**Issue by kelbev** [AntonyCorbett/OnlyM#43]
Used at our meeting tonight. Played video great. However, a brother had pictures uploaded from one of the special conventions. They showed right side up in the computer file, but several displayed sideways, not all. Any simple way to fix this, such as a rotate feature for each individual file. Would be nice when brothers bring their own images to display. Thank  you.

**Comment by AntonyCorbett** [comment]
@kelbev This applies to photos that have been taken using the camera in different orientations. The photo file contains some metadata (called "exif" data) that records the orientation in which it was taken. Unlike Windows Explorer, OnlyM does _not_ currently re-orient photos; it displays them as they are. The code to do this is in place but causes some issues so it's work-in-progress atm. The workround is to re-orient the photos using another tool before display, but that's not so helpful! Thanks for feedback.

**Comment by AntonyCorbett** [comment]
@kelbev There is now an option "auto-rotate" in the Images settings. See teh latest pre-release

**Comment by n8y8sLSdrmr** [comment]
This is happening on our Kingdom Hall pc right now.  A visiting speaker had 6 images to share that were all taken using his iPhone - 3 in landscape mode and 3 in portrait mode.  The 3 images in landscape mode all displayed correctly; and 1 in portrait mode displayed correctly.  However, two of the photos that were in portrait mode would not display correctly - they would keep displaying sideways in landscape mode, turned counter-clockwise.  The "auto rotate" feature was disabled.  For kicks, we enabled the auto rotate feature, and it would still rotate it.
We then used the native photo editor (Windows 10) to manually rotate it to the right, hoping that the OnlyM app would then rotate it counter-clockwise to the correct orientation... but no go.  It would still keep the image in landscape mode, but this time turned to the right as we had manually manipulated it.  
We tried renaming the image, and deleting and re-importing, but nothing would work.  
We even installed the update that our app needed, all to no avail.
Any suggestions ?
Thanks

**Comment by AntonyCorbett** [comment]
Thanks for the report. With the auto-rotate option off, OnlyM displays the image unaltered which is why some were displayed with a different orientation depending on the rotation of the camera when the photo was taken. With the setting on, OnlyM uses the file's Exif rotation metadata to rotate the image before display. It modifies the image and then removes the Exif rotation data. So once added to OnlyM (with auto-rotate on) the image contains no rotation metadata - if you manually rotate it in another application, OnlyM will display it as is.
