### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Grewcock** [AntonyCorbett/OnlyM#432]
Hi, how do I erase media from ONLYM? I have allot of media stored from past meetings and it's a bit cluttered but I can't find a way to delete old media.

**Comment by richfrantz** [comment]
Look in the wiki. The words you are looking for are "command panel"
________________________________
From: Grewcock ***@***.***>
Sent: Saturday, December 18, 2021 4:03 PM
To: AntonyCorbett/OnlyM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AntonyCorbett/OnlyM] Delete (Issue #432)


Hi, how do I erase media from ONLYM? I have allot of media stored from past meetings and it's a bit cluttered but I can't find a way to delete old media.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAntonyCorbett%2FOnlyM%2Fissues%2F432&data=04%7C01%7C%7C670114cd165847ab9ec508d9c27aa390%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754654248222992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HZ33LCbhRokfYlGlOl9KOHDiZn4VgnthhYUcabiBvLs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINW6PIRUYYPH4OICZ3VR7TURUHM7ANCNFSM5KLFJHBA&data=04%7C01%7C%7C670114cd165847ab9ec508d9c27aa390%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754654248222992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=O9JiXWGG5tvuAY9MgS%2Fe8jQ0KFYB33DDuJ5fitNlqYA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C670114cd165847ab9ec508d9c27aa390%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754654248222992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pNCo33RfPeGj6BBDJltk1A3Alo8BTwzN2n4TJihn%2B2I%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C670114cd165847ab9ec508d9c27aa390%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754654248222992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UUq0Cg7QXJ8NBabu0pfNj%2FM0ct3vlJo1ieoVnR%2BJHTg%3D&reserved=0>.

**Comment by AntonyCorbett** [comment]
@Grewcock You're right - it's not obvious is it? The Wiki suggests that you manage media files using Windows Explorer. Just click the folder icon at the bottom of the OnlyM window and then delete files as required from there.

**Comment by timjobutler** [comment]
@AntonyCorbett Perhaps the _[General](https://github.com/AntonyCorbett/OnlyM/wiki#general)_ subheading in the **Operation** section could be renamed to _File Management_?

**Comment by AntonyCorbett** [comment]
@timjobutler I've done as you suggested - thanks!

**Comment by timjobutler** [comment]
I didn't think the suggestion would be accepted so quickly.

@Grewcock - does the change of subheading make it to find the information you needed?

**Comment by Grewcock** [comment]
I'm not sure what you meant, change of subheading. I just wanted to know if
I can delete old pics and videos from the onlym file. i tried right click
but, nothing. I tried dragging to trash bin, nope. It seems like there
should be an easy way to delete media that I don't need anymore, no?

**Comment by AntonyCorbett** [comment]
Please manage media files using Windows Explorer. Just click the folder icon at the bottom of the OnlyM window and then delete files as required from there.

**Comment by Grewcock** [comment]
Well that was easy, thank you very much. I know it probably was a dumb
question but I'm not very computer savvy, yet.
