### ISSUE TITLE
List or detailed overview of media

### ISSUE THREAD

**Issue by sewru** [AntonyCorbett/OnlyM#44]
Hi Antony, Is it possible to have a list or detailed overview in the media pane. With probably more metadata of the the file shown. Maybe also the ability to have the fonts resized. 

Thanks.

**Comment by AntonyCorbett** [comment]
@sewru Thanks for this. Please would you provide some more detail about the meta data you need? Also, perhaps you would open a separate issue regarding fonts and supply as much info as you can. This just helps to provide justification for any new requests and allows others to provide better feedback. Thanks! Antony

**Comment by AntonyCorbett** [comment]
@sewru closing as no response. Please feel free to respond and reopen.
