### ISSUE TITLE
OnlyM

### ISSUE THREAD

**Issue by geostanko** [AntonyCorbett/OnlyM#442]
**Describe the bug**
I can't use OnlyM anymore with JwLibrary...can't open full screen

**To Reproduce**
3. See error

**Expected behavior**
full screen on second window

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - JwLibrary play video on second screen

**Comment by AntonyCorbett** [comment]
@geostanko Can you describe what _does_ happen, please? e.g., does the media window fail to open, or does it open as a smaller window? Have you checked to see that the OnlyM Display Settings are correct?

**Comment by geostanko** [comment]
first apologies, my english is not exactly the best   media window open as a smaller window and I can't open it to full size  I have settings from 2020. and don't know if I have to change something...can you send me correct Display settings  thank you for answer 

    On Monday, April 11, 2022, 10:38:10 AM GMT+2, Antony Corbett ***@***.***> wrote:  
 
 


@geostanko Can you describe what does happen, please? e.g., does the media window fail to open, or does it open as a smaller window? Have you checked to see that the OnlyM Display Settings are correct?

**Comment by AntonyCorbett** [comment]
@geostanko Thanks for the extra information :) In Settings => Display Settings uncheck the **Windowed** setting and select a monitor from the **Monitor** drop-down box.

**Comment by geostanko** [comment]
ok, I'll do it and mail you back...bye
   On Monday, April 11, 2022, 11:11:39 AM GMT+2, Antony Corbett ***@***.***> wrote:  
 
 


@geostanko Thanks for the extra information :) In Settings => Display Settings uncheck the Windowed setting and select a monitor from the Monitor drop-down box.

**Comment by geostanko** [comment]
yes , that's it  solved...I lost settings during Covid-19, somehow . projector was unplugged...one suggestion : word "Monitor" write with larger font in Settings ! thank you very much
still, how to display second monitor in Zoom ? I see only the first monitor for share  


    On Monday, April 11, 2022, 11:11:39 AM GMT+2, Antony Corbett ***@***.***> wrote:  
 
 


@geostanko Thanks for the extra information :) In Settings => Display Settings uncheck the Windowed setting and select a monitor from the Monitor drop-down box.

**Comment by geostanko** [comment]
what's new in new .exe for onlyM ? should I download it ? greeting

    On Monday, April 11, 2022, 11:11:39 AM GMT+2, Antony Corbett ***@***.***> wrote:  
 
 


@geostanko Thanks for the extra information :) In Settings => Display Settings uncheck the Windowed setting and select a monitor from the Monitor drop-down box.

**Comment by geostanko** [comment]
ok  how to display second monitor in Zoom share screen ? 

    On Monday, April 11, 2022, 08:59:54 PM GMT+2, Antony Corbett ***@***.***> wrote:  
 
 


The Release page provides a brief description of changes for each release.

https://github.com/AntonyCorbett/OnlyM/releases

**Comment by geostanko** [comment]
dear Antony, is there any solution to display video on Zoom share screen from OnlyM ? or to be satisfied that we can watch in the Hall, and those present through Zoom to be able to listen ?
   On Monday, April 11, 2022, 08:59:54 PM GMT+2, Antony Corbett ***@***.***> wrote:  
 
 


The Release page provides a brief description of changes for each release.

https://github.com/AntonyCorbett/OnlyM/releases

**Comment by geostanko** [comment]
the solution for my problem was so simple...I just needed to share second screen! :)

**Comment by AntonyCorbett** [comment]
@geostanko glad you're sorted
