### ISSUE TITLE
Play button faded out

### ISSUE THREAD

**Issue by Ben9790** [AntonyCorbett/OnlyM#446]
The play button for all types of media file is 'greyed out' so I cannot play media. 

![image](https://user-images.githubusercontent.com/105588539/168469629-5287e129-c460-451f-8451-d4321b4a0482.png)

 - Windows version

**Comment by scottys94** [comment]
@Ben9790 Do you have a monitor selected in the settings of OnlyM?

**Comment by Ben9790** [comment]
> @Ben9790 Do you have a monitor selected in the settings of OnlyM?

I do now. Thank you.
