### ISSUE TITLE
Make JW Library Compatibility Mode aware of other windows

### ISSUE THREAD

**Issue by JamesSwift** [AntonyCorbett/OnlyM#448]
**Is your feature request related to a problem? Please describe.**
In our setup, we have the JW Library media window on the second screen. We also have the Zoom "multi-monitor" window on the same screen, and we switch between these two as needed using the task bar. However, when we also use OnlyM to display pictures on that screen, if "JW Library Compatibility Mode" is enabled, once we stop the media in OnlyM, it always brings JW Library to the front, regardless of whether Zoom was in front previously. 

**Describe the solution you'd like**
It seems as if "JW Library Compatibility Mode" is solving the problem of JW Library minimizing its media window when something else is fullscreen, by always restoring it when media is no longer playing - which is a great solution. Would it be possible though for it to be aware of which window was "on top" when the media is started, and then restore _that_ window when the media is stopped?

**Describe alternatives you've considered**
At the moment, we have to manually disable "JW Library Compatibility Mode" if we are trying to display media on top of zoom, then remember to turn it back on afterwards.

**Additional context**

**Comment by AntonyCorbett** [comment]
Hello James, you might try disabling the "JW Compatibility mode" and using the JwlMediaWin tool instead.

https://github.com/AntonyCorbett/JwlMediaWin

**Comment by JamesSwift** [comment]
Thanks, I'll try that out 👍

**Comment by JamesSwift** [comment]
For anyone else having problems combining zoom and JW library, you might find this tool I wrote useful: https://github.com/JamesSwift/AutoHotKey-Zoom-Wrangler
