### ISSUE TITLE
Ability to Zoom in/out

### ISSUE THREAD

**Issue by athornfam2** [AntonyCorbett/OnlyM#454]
**Is your feature request related to a problem? Please describe.**
No - N/A

**Describe the solution you'd like**
Particularly during our meeting tonight we had JHA and TIC images to show. Our friends (both younger and older) are having a hard time viewing the image at its native size. We have to go outside of OnlyM to use Microsoft photos which interrupts the flow during the meeting.

**Describe alternatives you've considered**
It would be nice to have a plus or minus but to zoom in/out on media (PNG, JPG, PDF, etc..).

**Comment by mtdvlpr** [comment]
Hi @athornfam2, have you considered [meeting-media-manager](https://github.com/sircharlo/meeting-media-manager)? It has a zoom in feature with a lot of other nice features.

**Comment by AntonyCorbett** [comment]
@athornfam2 Thanks for your suggestion, but I don't think this will ever be supported in OnlyM
