### ISSUE TITLE
Using OnlyM with 3 screens (laptop, second monitor and Hall screens)

### ISSUE THREAD

**Issue by AllanChes** [AntonyCorbett/OnlyM#455]
We are using a small screen laptop and are trying to use a second monitor to give more screen space at the Sound Desk. So that the JW Library will display on the Hall Monitors, we have had to choose the second Sound Desk monitor as the "main screen" for the laptop, otherwise the JW Library displays on the second monitor, as does OnlyM.  However, when we choose the second monitor as the "Main screen", the Library is fine and displays on the hall monitors but OnlyM's second screen disappears. When you mouse over OnlyM on the task bar, it is showing a second screen but it is just white and the second monitor loses it's image but nothing is displayed. If you click on the mouseover thumbnail nothing happens - the image does not appear on any screen.
Is this a 'bug' or is there some other way to get it to operate with 3 screens?
Thanks for any advise. 
Allan, Nuriootpa Congregation, South Australia

**Comment by AntonyCorbett** [comment]
@AllanChes Sorry for the very late response to this query! Have you resolved the issue now? I suspect it is just a matter of specifying the relevant monitor in OnlyM's settings, but please say if the problem remains.

**Comment by AllanChes** [comment]
Hi Anthony We completely revised the whole setup and the problem did not reappear, so all OK.Thanks,AllanF. Allan ChesneyUnit 1, 4 Schilling St, Angaston. South Australia 5353 Ph: 0417 963 921Sent from my Samsung Galaxy Z Fold 3
-------- Original message --------From: Antony Corbett ***@***.***> Date: 29/7/23  1:06 am  (GMT+09:30) To: AntonyCorbett/OnlyM ***@***.***> Cc: AllanChes ***@***.***>, Mention ***@***.***> Subject: Re: [AntonyCorbett/OnlyM] Using OnlyM with 3 screens (laptop, second monitor and Hall screens) (Issue #455) 
@AllanChes Sorry for the very late response to this query! Have you resolved the issue now? I suspect it is just a matter of specifying the relevant monitor in OnlyM's settings, but please say if the problem remains.
