### ISSUE TITLE
windows 11 issue

### ISSUE THREAD

**Issue by KBrooks904** [AntonyCorbett/OnlyM#460]
just replaced computers with new ones which now have windows 11. when we try to share an image on zoom, onlym makes the display monitor the main one and we
lose the ability to have the zoom controls on the desktop. when we exit onlym
it reverts back to main desktop as 1 and the 2nd monitor as 2.

**Comment by AntonyCorbett** [comment]
Hello. Please would you provide some more detailed information? OnlyM doesn't modify the order of monitors reported by Windows.

**Comment by KBrooks904** [comment]
Everything works fine when using JW Library in displaying videos, pictures, etc.Desktop monitor is main display and shows as 1. Wall monitor is 2nd display andshows as 2.When we go to use OnlyM (or VLC Media Player) then the wall monitor becomesmain display 1 and desktop monitor is now 2. Hope this helps.

    On Thursday, October 6, 2022 at 11:59:51 AM EDT, Antony Corbett ***@***.***> wrote:  
 
 


Hello. Please would you provide some more detailed information? OnlyM doesn't modify the order of monitors reported by Windows.

**Comment by AntonyCorbett** [comment]
@KBrooks904 Can you explain what you mean by "monitor 1" and "monitor 2", please? When you go into Windows Display Settings and click the Identify button are you saying that the monitor numbers are changed depending on whether OnlyM is running?

**Comment by AntonyCorbett** [comment]
Perhaps you mean that OnlyM displays media on a different monitor to JW Library. If so, just go into the OnlyM settings and change the Media Monitor. Please see the OnlyM Wiki for more information on Settings if needed.

**Comment by KBrooks904** [comment]
monitor 1 is the computer desktopmonitor 2 is the monitor on the wall to display to the audience.When using JW Library is used everything is fine.When we use OnlyM then the displays are switched and the monitoron the wall becomes 1 and the computer desktop is the secondary monitor.I will check OnlyM WikiThanks

    On Friday, October 7, 2022 at 12:07:01 PM EDT, Antony Corbett ***@***.***> wrote:  
 
 


Perhaps you mean that OnlyM displays media on a different monitor to JW Library. If so, just go into the OnlyM settings and change the Media Monitor. Please see the OnlyM Wiki for more information on Settings if needed.

**Comment by AntonyCorbett** [comment]
@KBrooks904 Is there still a problem here or have you resolved the issue, please?

**Comment by KBrooks904** [comment]
Yes issue resolved thanks 


Sent from Yahoo Mail for iPhone


On Friday, July 28, 2023, 11:33 AM, Antony Corbett ***@***.***> wrote:




@KBrooks904 Is there still a problem here or have you resolved the issue, please?
