### ISSUE TITLE
ONLYM and ONLYT not working since 22H2 update

### ISSUE THREAD

**Issue by 2Badgers** [AntonyCorbett/OnlyM#461]
Our Kingdom Hall’s workstation runs Windows 11 Pro and this week it has been updated to Windows 11 22H2.  Prior to the update ONLYM and ONLYT worked fine (many thanks for this excellent tool).  Since the update ONLYT counts down on the workstation monitor but does not show on the timer monitor.  ONLYM is similar, it does not display the images on the two main large format screens.

Would it be best to uninstall ONLYM and ONLYT and reinstall?

Does the software work with Windows 11 22H2?

Any thoughts on how to fix this?

**Comment by AntonyCorbett** [comment]
@2Badgers There are no reported issues with Win 11. I suspect it's just a case of specifying the correct monitors in the Settings pages. Please would you check and let me know if you are still struggling. Please see each application's wiki for further info on settings.

Kind regards
Antony

**Comment by 2Badgers** [comment]
All now working fine – Thanks.

I checked that the timer monitor and image monitors was set correctly, which they were.  So, I uninstalled the software and reinstalled, then set the monitors as appropriate and all worked well.

Thanks for your wiki suggestion, which were followed.  Thanks again.

**Comment by shane-smith** [comment]
Hello! We're encountering the same problem after the 22H2 update, which we installed earlier this week.

1. Updated to 22H2
2. OnlyM launched but no longer displayed the image on the other screen, it seemed like the play button wasn't doing anything. So we switched to using VLC for now as a workaround.
3. Today, I tried to fix it by installing the latest version of OnlyM. But when it gets to the point where it tries to install the .NET framework, it fails, and I need to either abort installation or ignore that step and continue.
4. If I ignore the .NET framework, OnlyM installs over the top of what we had before, but now it doesn't launch the application at all. It reports needing .NET framework to be installed. Confirming this prompt then launches Microsoft's download page for the .NET 5.0 Desktop Runtime (v5.0.17) - Windows x86 installer. But that download is consistently failing.

This is the link it directs us to: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x86-installer?cid=getdotnetcore

If I look at the .NET official support lifecycle - https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core - it indicates that .NET 5 is no longer supported (end of support was May 10th this year).

Can we use .NET 6 with OnlyM instead? It didn't seem to detect it.

Thanks for any assistance you can provide on this :) Happy to provide additional information if it would help - let me know what you need.

**Comment by AntonyCorbett** [comment]
@shane-smith I can download .NET 5 from that link. I suspect there was a temporary issue connecting to the download or your network configuration prevents it. Although it's out of support, MS won't remove the download.

**Comment by shane-smith** [comment]
Thanks for the quick response!

In that case I'll reattempt .NET 5 from that URL again soon.

**Comment by AntonyCorbett** [comment]
@shane-smith Have you been able to resolve this issue, please?

**Comment by shane-smith** [comment]
Sorry, I'll take another look soon.

**Comment by shane-smith** [comment]
Unfortunately continuing to have problems with the link from the hall - using both Edge and Chrome.

I'll try using a VPN from home, see if it's a routing issue.

![image](https://user-images.githubusercontent.com/943942/203524250-ae30d9d8-d7a6-4e86-9c9f-71626ce3289b.png)

**Comment by AntonyCorbett** [comment]
@shane-smith Closing now (assuming all is well), but feel free to reopen if needed.
