### ISSUE TITLE
Usb Compatible

### ISSUE THREAD

**Issue by talkingdragon** [AntonyCorbett/OnlyM#48]
It be grate to run from a USB as then speakers can use it when they go to do a talk at another hall.
If it has keyboard keys option (as mentioned in another post) it can then be adapted to work on a powerpoint remote (as all they do is hit a keyboard key)

**Comment by AntonyCorbett** [comment]
@talkingdragon thanks for feedback. OnlyM can be run from a USB drive if the distribution files are copied to it. But I think it would be problematic running other software on a "guest" system. Regarding keyboard control note that the current instructions state that the speaker should _not_ control media.

**Comment by AntonyCorbett** [comment]
@talkingdragon 

https://github.com/AntonyCorbett/OnlyM/wiki/Portable-Operation
