### ISSUE TITLE
Unable to delete previously used media

### ISSUE THREAD

**Issue by FowlerColorado** [AntonyCorbett/OnlyM#481]
**Describe the bug**

I am unable to delete used media from one particular day. I am able to hide the media, and am able to add new media and delete the new media, but able to delete 5 photos. 

**To Reproduce**
1. Add media
2. Click on delete 
3. See error "Cannot Delete File!

**Expected behavior**
To be able to delete the media

**Screenshots**
I have included a screenshot of the error. 

![OnlyM Error Photot](https://github.com/AntonyCorbett/OnlyM/assets/138336067/cb286419-deb5-4371-ba26-5448ee04657b)

**Desktop (please complete the following information):**
 - Windows version 11
 - No other info about my environment.

**Comment by FowlerColorado** [comment]
I also uninstalled the program and reinstalled it to make sure I had the updated version and the photos were still in the program after uninstalling it from the computer and reinstalling it.

**Comment by AntonyCorbett** [comment]
@FowlerColorado Perhaps you don't have permission to delete the images. Can I suggest you open the media folder and see if they can be deleted from there? Proceed as follows: Click the folder icon at the bottom right of the OnlyM window to open the File Explorer window. Try to delete the relevant images from within File Explorer noting any error messages.

**Comment by FowlerColorado** [comment]
We have been able to delete files for the past 4-6 months. It is only these 5 images that we cannot delete. I can add more images and delete them ok. And even hide the undeletable images and add new ones and show and then delete those. However I will attempt your suggestion today and see if it works!Sent from my iPhoneOn Jul 2, 2023, at 6:59 AM, Antony Corbett ***@***.***> wrote:﻿
@FowlerColorado Perhaps you don't have permission to delete the images. Can I suggest you open the media folder and see if they can be deleted from there? Proceed as follows: Click the folder icon at the bottom right of the OnlyM window to open the File Explorer window. Try to delete the relevant images from within File Explorer noting any error messages.

**Comment by AntonyCorbett** [comment]
@FowlerColorado Did you manage to resolve this issue, please?

**Comment by AlainDema** [comment]
Salve anche a noi in Sala si presenta lo stesso tipo di problema con 2 foto e un video che si possono nascondere nonostante nella cartella non sia presenta alcun tipo di file. A casa ho il programma e non mi succede.

**Comment by FowlerColorado** [comment]
So I finally was able to delete the photos from the OnlyM program. And the way I was able to was I had to delete the photo’s from the computer itself in files, and then after I did that the photos disappeared from the program.

**Comment by AntonyCorbett** [comment]
@FowlerColorado Thanks - that's the way most users manage the media files, i.e. in Windows File Explorer (which you can access via the folder button bottom right in OnlyM).
