### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by flopcat** [AntonyCorbett/OnlyM#482]
**Is your feature request related to a problem? Please describe.**
OnlyM should support displaying webp. Sometimes brothers have brought in several WebP images and aren't aware that these images can't be displayed; as you know websites can optionally serve WebP images instead of png/jpg.

**Describe the solution you'd like**
WebP images get treated the same as jpg/png.

**Describe alternatives you've considered**
We run webps through krita, but if they're many images this can take more time than we have.

**Additional context**
This may be fairly straightforward because OnlyM already bundles ffmpeg.

**Comment by AntonyCorbett** [comment]
@flopcat webp and webm compatibility available in the latest pre-release
