### ISSUE TITLE
Jwlibrary extension

### ISSUE THREAD

**Issue by MarceloJrdaLuz** [AntonyCorbett/OnlyM#483]
Hello brother. I would like to ask a question related to the program. Recently, we received a notice from the organization that says: The terms of use of the JW Library app do not allow the creation of any software, application, tool, or technique beyond those provided by the organization. This means that no type of extension (also known as an add-on or plug-in) should be installed to work alongside JW Library. Therefore, use VLC Media Player to display images or videos that are not directly available in the JW Library app, as instructed in paragraph 1 of this document. I would like to know if OnlyM falls under this description, or if the way it was created would not violate the terms of use of JW Library. 

Thanks

**Comment by AntonyCorbett** [comment]
@MarceloJrdaLuz Hello. OnlyM is simply a media player and would not be considered an "add-on" or "plugin" It offers similar functions to VLC although VLC has greater functionality. OnlyM does not violate the JW Library terms of use. However, the notice you quote seems to me to either lack context or misrepresent the JW Library terms (which explicitly _allow_ for the creation of other applications in some circumstances). Having said that, if you have received direction from your branch to _only_ use VLC for media playback at meetings, then the wise course is to follow the instructions.

Thanks for your question. I hope my observations seem reasonable.

Regards
Antony

**Comment by MarceloJrdaLuz** [comment]
Thank you very much for your consideration. Your response has already been helpful. It's possible that our branch has given this instruction because there are other applications that are adding some type of plugin to Jw. Your response has helped me see that this is not the case with OnlyM.

With this new update of the JW Library, which includes the playlist feature, it has become much easier to do everything through JW Library. However, there are still several utilities that OnlyM provides. So I will continue using it when necessary.

Regards
Marcelo
