### ISSUE TITLE
JPEG DPI OnlyM Black Screen

### ISSUE THREAD

**Issue by epixscott** [AntonyCorbett/OnlyM#485]
Some newer JPEG images on JW.ORG have a DPI set to 2397x2397:
![image](https://github.com/AntonyCorbett/OnlyM/assets/73084932/2072a0a5-005f-4e20-a5bc-dcfb4a0c42b8)

For example:
https://cms-imgp.jw-cdn.org/img/p/202023407/univ/art/202023407_univ_cnt_1_xl.jpg

These images don't want to display in OnlyM. When clicking play, OnlyM just displays a black screen.

Simply reducing the image DPI allows them to display.  I've tried as high as 1200x1200 DPI and they display fine in OnlyM:
![image](https://github.com/AntonyCorbett/OnlyM/assets/73084932/d7284970-8bdd-46fe-b651-fdf21afe4f84)

To Reproduce
1. Download a JPEG image with a DPI of 2397x2397
2. Try to display in OnlyM
3. Reduce the DPI
4. Display in OnlyM

Desktop:
 - Windows version 10
 - OnlyM version 2.1.0.6
 
Same behavior on multiple computers

**Comment by AntonyCorbett** [comment]
Thanks. The DPI values (2397x2397) in the jpeg metadata are fairly meaningless, and usually correspond to the target medium. In this case, the very large values are causing OnlyM a problem somewhere - I'll investigate.

**Comment by AntonyCorbett** [comment]
@epixscott Fixed now.

**Comment by epixscott** [comment]
Great! Thank you.

I understood the DPI to have nothing to do with video display. Just curious, how did that affect OnlyM?

Thanks for all the work on this project.
