### ISSUE TITLE
Windows 11 Compatibility

### ISSUE THREAD

**Issue by mpjohn3** [AntonyCorbett/OnlyM#488]
Is the latest version of OnlyM compatible with Windows 11? If not, is there a plan for an update or patch that will be compatible?
We recently upgraded our PC to Windows 11, but now OnlyM no longer works. The program opens, but it is no longer functional.
None of the buttons to display images work any longer. We have tried rebooting the PC and reinstalling OnlyM. Same results...

**Comment by AntonyCorbett** [comment]
There are no issues I know of. Have you specified an output monitor in the Settings page?

**Comment by Andyg216** [comment]
I have had the same issue. The Onlym program opens but when I drag images into the app, the play button does not work. I can go to settings and the file folder on the app and the help button, they all work. It's only the play button. I have uninstalled and re-installed the app , with no success. I am using windows 11. 
thanks,

**Comment by AntonyCorbett** [comment]
@Andyg216 Have you specified an output monitor in the Settings page?

**Comment by Andyg216** [comment]
Thank you for getting back with me so soon and yes that was the problem. It
had been set but I think when I uninstalled and reinstalled i didn't select
it again.  Thanks again.

**Comment by AntonyCorbett** [comment]
@mpjohn3 is this the same solution for you?

**Comment by mpjohn3** [comment]
I will ask our team to try this solution.

Thanks,
Michael Johnson

**Comment by AntonyCorbett** [comment]
Closing as no response.
