### ISSUE TITLE
Audio Delay

### ISSUE THREAD

**Issue by ucphinni** [AntonyCorbett/OnlyM#49]
Add a setting for millisecond delay to audio similar to VLC.

**Comment by Blann** [comment]
If desynced audio is a system-wide issue (and it could be quite common given the length of cable required for media monitors in most places), it’s worth checking if your audio driver allows you to add a delay.

Alternatively, you can install the Equalizer APO utility – this allows you to add a delay (among many other things that could potentially be useful) and uses minimal system resources.

**Comment by ucphinni** [comment]
Checked the audio driver, it does not.

However, I am not at the kingdom hall and if Equalizer APO works the way I
think it should, then that is exactly what I need.  Been searching the
internet for a while for something like that thanks.  Wonder why Windows
MPC and VLC have audio delay built in?

**Comment by Blann** [comment]
I imagine it’s included for when the issue is caused by the file’s audio track actually being out of sync with the video (as opposed to it being caused by any hardware-related factors).

Equalizer APO is very lightweight so shouldn’t cause you any issues.

**Comment by ucphinni** [comment]
Thank you.  I installed it on the kingdom hall computer via teamviewer.  My meeting has been moved to today due to CO visit of another congregation so we will have a live test.  I will close this if it works. 

Once again, thank you for your suggestion.

**Comment by AntonyCorbett** [comment]
> Alternatively, you can install the Equalizer APO utility – this allows you to add a delay (among many other things that could potentially be useful) and uses minimal system resources.

@Blann This is a useful tool - I'll add a link somewhere. Thanks!

**Comment by ucphinni** [comment]
Changing the delay does not eliminate the echo (I was not close enough to the tv, but allows proper lip sync with audio system and tv video which is what the friends want.

**Comment by AntonyCorbett** [comment]
@ucphinni if the TV speakers are on then that will account for the echo

**Comment by Blann** [comment]
Yes, it won’t eliminate the delay between your sound system and your TVs because they’re using the same output device from your PC. The signal is just taking longer to reach the TVs.

**Comment by blazer2004** [comment]
@ucphinni, You could run the audio straight out of the sound card instead of out of the HDMI, change your default audio device to your sound card if you do so. This will eliminate the being transmitted to the TV's in the first place. Or better still if you have a newer digital or hybrid mixer with USB input, run a USB cable to the mixer, and change it to your default sound device.
