### ISSUE TITLE
Support for Media Folders

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyM#493]
Good day Antony,
Would it be possible for OnlyM to support organizing media files into separate folders?
For example, Midweek Media, Circuit Overseer, etc.

**Comment by AntonyCorbett** [comment]
Hi Scotty. There are a couple of workarounds that may be acceptable. 
1. Do as you propose and organise content into folders and then switch between them in Settings => Media files => Media folder. The drop-down menu can be used to make the folder selection.
2. Use the command-line option "/source=" to specify the folder. Set up shortcuts to launch the one you want.

**Comment by scottys94** [comment]
Thank you so much, @AntonyCorbett. The option to use a command line switch will suffice for us.
