### ISSUE TITLE
Malware detection

### ISSUE THREAD

**Issue by bradenpintar** [AntonyCorbett/OnlyM#499]
I tried downloading an update to the program only to have it detected and deleted by NordVPN's Threat Protection Anti-Malware service.

I got around this by downloading the mobile version of the program.

![OnlyM](https://github.com/user-attachments/assets/fb201fea-8fd1-404e-8d96-a0d748e35000)

**Comment by AntonyCorbett** [comment]
@bradenpintar Please see [this part](https://github.com/AntonyCorbett/OnlyM/wiki/Malware) of the wiki.
