### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by Blann** [AntonyCorbett/OnlyM#5]
First off just wanted to thank you for developing the three applications for use with JWL. OnlyM in particular will save a lot of hassle - the compatibility mode with JWL seems to work perfectly so far. Good work.

Just a small seeming issue - when an image is first imported into OnlyM and displayed, the fade-in transition does not occur and the image appears abruptly. It just seems to be the first time an image is displayed during a session, and it is the case whether displaying each image one-by-one or moving directly from one to the next.

It can be worked around by just momentarily displaying all the images in advance, but thought I'd let you know just in case it's something worth looking at.

Thanks again.

**Comment by AntonyCorbett** [comment]
@Blann This should be fixed in the latest release (or at least be somewhat better). Note that if not using the permanent backdrop, the image will still display abruptly.
