### ISSUE TITLE
OnlyM not keeping Display Settings

### ISSUE THREAD

**Issue by Pickles-The-Cat** [AntonyCorbett/OnlyM#51]
Hi,

We've just started using OnlyM and JW Library in an attempt to wean our congregations off of SoundBox, and one of the issues that I've noticed is that I set OnlyM to display on the correct screen, (we have 3 screens, SoundDesk Display, Front Screens and a Timer Display) but when we reboot the sound PC (Windows 10) the display settings are lost and we have to reset them. 

Is this something that we are doing wrong or is that common behaviour and if so could the settings be made persistent, as it is a little beyond most operators to set up the display settings at each meeting.

Thanks

**Comment by AntonyCorbett** [comment]
OnlyM will remember the setting. I suspect your video driver is recreating the device definitions on each reboot in which case OnlyM can't match the device with the saved identifier. Please try updating your video driver.
