### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by talkingdragon** [AntonyCorbett/OnlyM#52]
Can we have the same featured u had on soundbox for background music?
We were told by the elders that bkground music is recommend in the letter for sound. It be very handy to have the feature like on soundbox with lower volume.

**Comment by AntonyCorbett** [comment]
@talkingdragon thanks for feedback. there is a background music function in JW Library - I won't try to reproduce functions that are provided by JWL.

**Comment by Pickles-The-Cat** [comment]
Antony,

Can you enlighten me as to where this function is in JWL? I have been looking but can only see how to play one song at time.. 

Thanks

Mike

**Comment by talkingdragon** [comment]
Uff made my day with that name @pickels-the-cat when I media tab and in audio. If u select a section u want so music with chorus at top u got the play button and it randomly plays that section. Wich is grate.. Except it full volume wich is rly annoying in out setup and its a difrent tab so when time start u rushing to the meeting tab.. Wich are laptop.. Don't know how to rush.. Hahaha

**Comment by Pickles-The-Cat** [comment]
Thanks, but that isn’t really a random play. It will “Play All” so will always do this from the first song and you will hear this at every meeting as you can’t start the play back from anywhere else, and if you do you just get that song played and then it stops.

Is there anyway you know to “Play All” in a random way?

Thanks

Mike

**Comment by TizianoNoto** [comment]
>If u select a section u want so music with chorus for e.g. at top u got the play button and it randomly plays that section. Wich is grate.. Except it full volume wich is rly annoying in out setup and its a difrent tab so when time start u rushing to the meeting tab.. Wich are laptop.. Don't know how to rush.. Hahaha

Can't you lower the volume in the notebook? (You don't use a mixer to control all audio devices, do you?)

Also you can go in the "media" page in the "Meetings" section, do what you need in other sections of the app and when you click on "Meetings" again you will already be in the media page.

**Comment by Pickles-The-Cat** [comment]
Thanks.. I have never noticed that and you are right it does work.

Thanks for reading the instructions, always helps!

Mike
