### ISSUE TITLE
Sound problem with 1.0.0.33

### ISSUE THREAD

**Issue by AlexandreTortevois** [AntonyCorbett/OnlyM#54]
Hi Anthony,
Yesterday I have updated last OnlyM version and i have a problem with sound media file.
When i play a song (or an other audio file), first second is repeat once time.
Good tracking ;)

Thank's for your job !

**Comment by AntonyCorbett** [comment]
@AlexandreTortevois thanks for reporting this. I am having some problems with MP3 playback. Am investigating.

**Comment by AntonyCorbett** [comment]
@AlexandreTortevois I haven't been able to reproduce this issue but have made some changes to MP3 playback in the latest release. I'll mark as fixed but please reopen if needed.
