### ISSUE TITLE
Delete files directly from UI

### ISSUE THREAD

**Issue by phillipnunes** [AntonyCorbett/OnlyM#55]
**Describe the solution you'd like**
It would be nice if we can delete files directly from interface. At the moment we need open folder and delete files manually.

**Comment by Blann** [comment]
You can do this by enabling the command panel in settings. From the wiki:

“Media Files => Enable command panel - If checked, OnlyM displays a command panel button to the left of the media items. The panel contains commands to Hide and Delete the item. Note that the Delete command actually removes the file from disk.”

**Comment by phillipnunes** [comment]
Ok, thanks!

**Comment by n8y8sLSdrmr** [comment]
Is there a way to recover deleted files?  While doing some testing, I deleted a file expecting to find and recover it from the recycle bin, but could not find it.  I did a search for it on the computer but could not find it anywhere.  I am using Windows 10, the release prior to 19.03.
thanks,
Nate

**Comment by AntonyCorbett** [comment]
@n8y8sLSdrmr No - the delete function does not add to the recycle bin. Please feel free to add a feature request in a new issue

**Comment by n8y8sLSdrmr** [comment]
Ok, will do.  thank you brother.

Nate 

    On Friday, July 12, 2019, 12:33:59 AM PDT, Antony Corbett <notifications@github.com> wrote:  
 
 
@n8y8sLSdrmr No - the delete function does not add to the recycle bin. Please feel free to add a feature request in a new issue
