### ISSUE TITLE
Caching blurs my images

### ISSUE THREAD

**Issue by mbrakutt1** [AntonyCorbett/OnlyM#57]
Upon opening the application and loading my images, when I press the play button they become blurry, only when caching is enabled. When the option is disabled it works perfectly. The feature only blurs images not videos when enabled.

Here is my log.

[log-20181008.txt](https://github.com/AntonyCorbett/OnlyM/files/2456640/log-20181008.txt)

**Comment by AntonyCorbett** [comment]
@mbrakutt1 Please would you send me a link to a sample image that exhibits the problem?

**Comment by mbrakutt1** [comment]
**Hello Antony here is a better look at the problem**

![screenshot 20](https://user-images.githubusercontent.com/36244009/46621683-7ea44980-cafe-11e8-91be-e2190a267441.png)
![screenshot 21](https://user-images.githubusercontent.com/36244009/46621684-7ea44980-cafe-11e8-8769-b75defb74dca.png)

**Also here are the images you requested**

![img_20180603_173301](https://user-images.githubusercontent.com/36244009/46621761-bdd29a80-cafe-11e8-950f-a2741943163f.jpg)
![img_20180603_173200](https://user-images.githubusercontent.com/36244009/46621762-bdd29a80-cafe-11e8-8d5e-bce819d8babb.jpg)

**Comment by AntonyCorbett** [comment]
@mbrakutt1 excellent thanks, I can reproduce the issue

**Comment by AntonyCorbett** [comment]
@mbrakutt1 Fixed in the latest release. Thanks for reporting.

**Comment by mbrakutt1** [comment]
Now that's a record, good work Anthony and thanks 👍
