### ISSUE TITLE
JW Yearly Text Now Showing

### ISSUE THREAD

**Issue by TENSEAN** [AntonyCorbett/OnlyM#58]
**After starting and stopping multiple images in OnlyM, the yearly text will not reappear**
We had 3 images in OnlyM and after playing through them, the yearly text would not display. If we started and stopped the Blank Screen option, it would reappear. It was sporadic with how many times we start and stopped an image in OnlyM with the text not reappearing. It was typically after the 2nd or 3rd image.

**To Reproduce**
1. Upload multiple images so they are showing in OnlyM
2. Start then stop image 1 and text would reappear
3. Start and stop image 2 and text would reappear the majority of the time 
4. Start and stop image 3 and text would typically not reappear
3. Yearly text from JWL would not show on external displays
4. Start and stop Blank Screen and yearly text would show

**Expected behavior**
Yearly text should appear after stopping a video or image every single time.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Home x64 Version 1803 (build 17134.286)
 - Updated video driver from manufacturer website
 - Only applications launched were JWL and OnlyM
 - Updated OnlyM with release from 10/8/2018

**Comment by AntonyCorbett** [comment]
@TENSEAN thanks for the report. A couple of questions:

1. When you state that the JWL year text does not appear, do you mean that the black JWL secondary window does show, but without the white text? Or do you mean that the monitor reverts to the desktop background?

2. Can you confirm that no other Windowed applications are active? If an application becomes active on the same desktop monitor as the JWL window it will can cause problems as explained in the project wiki.

Thanks
Antony

**Comment by AntonyCorbett** [comment]
Another test you might perform is repeatedly hiding and showing the JWL year text window (via the taskbar). Although I can't reproduce the problem on test systems here, others have been able to get JWL to display the year text window with no text using this method (i.e. without OnlyM loaded).

**Comment by TENSEAN** [comment]
I will give that a try Wednesday and let you know the results.

Appreciate all your assistance!

**Comment by TizianoNoto** [comment]
I tried replicating the issue. This is the result so far:

- OnlyM is started, media items are played one after the other then STOP is pressed - sometimes JWL window is not resumed;
- the issue seems to never occur after pressing STOP at least once during a single session.

Hope this helps somehow.

**Comment by AntonyCorbett** [comment]
@TizianoNoto Thanks for feedback. This seems to be an issue with JWL itself as it can be reproduced without launching OnlyM. Will close for now, but please reopen if you have extra information.
