### ISSUE TITLE
Not able to select Media Monitor

### ISSUE THREAD

**Issue by jwpub** [AntonyCorbett/OnlyM#6]
I have installed original and version released today, not able to select Media Monitor in settings, it always states None.
I have Soundbox installed and that works fine with second monitor.
Display adapter is Intel(R) HD Graphics 3000
Main monitor is a HP 650 laptop, with HDMI to Sony tv. Output setting is extended mode.

And a big thank you for development. Been looking for something to perform this function for a while!

**Comment by AntonyCorbett** [comment]
@jwpub I've come across this before with OnlyT. The solution that works for most it to ensure the video driver is up to date (i.e. go to the Intel website to get the latest driver). Let me know how you get on.

**Comment by Mike2352** [comment]
Really excited when I saw the addition of OnlyM, Unfortunately, I have the same problem, only shows none" in the monitor box. Running Win10 with all drivers updated and run many applications that share my extended monitor. Any ideas?

**Comment by AntonyCorbett** [comment]
@Mike2352 - thanks for the feedback. It appears to be a common issue. Please would you double-check that the video diver has been updated with reference to the manufacturer's website (don't rely on the Windows update function).

**Comment by Mike2352** [comment]
Looks like we're up to date with latest drivers. Main monitor is and Acer 24", and remote is an Acer 23". This is my home setup so I'm just experimenting before we install at KH. I just loaded it on my Lenovo laptop and used and external Lenovo 28" as an external. Works great. Might just be a glitch somehow in my home desktop setup.

**Comment by AntonyCorbett** [comment]
@jwpub @Mike2352 Have now fixed this (I think). It's difficuklt because I have been unabel to rerpduce the error, but reverted to SoundBox code for monitor detection if the new method fails. Please try version 1.0.0.14

**Comment by omaha4** [comment]
This version is much better, works on a Surface book over miracast, on a Surface Book where the complicated video driver scheme is best left to windows update (mine has the GPU in the base), where the only way it worked in the past is to have three monitors hooked up.

**Comment by Mike2352** [comment]
Perfect!! Thank you. Works great, awesome addition to JW Library.

Mike


===========================
*Mike Smith*
Cell/Text: 613-876-2352


The information (and any attachments) in this e-mail message is to be
viewed only by the party to whom it is addressed. Please do not forward
unless asked to do so.
