### ISSUE TITLE
lyrics of the songs

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyM#61]
Hi Antony,
I understand that as of January 2019 SoudBox stops working, but will it be possible that the lyrics of the songs in SoundBox format can be played with OnlyM?

**Comment by AntonyCorbett** [comment]
@gonzo041 Sorry, there is no support for playing Folio lyrics (if that's what you mean by "SoundBox format"). You can play the song videos using OnlyM.

**Comment by gonzo041** [comment]
It's a shame, because there are many Kingdom halls (like ours), that we have projected screens, and the videos of the songs put their lyrics in the center making those of us sitting from the middle back of the room, we can not see the lyrics .
With the Folio de letras de SoundBox, we can adapt our need by configuring the projection of the letters to 50% of the screen at the top, so that we can all see the letters wherever we are sitting.
I hope you can understand what I want to convey, since I do not speak English and I write everything through a WEB translator.
Antony, thank you equally for everything you do for us.
Best regards.

**Comment by AntonyCorbett** [comment]
@gonzo041 Yes, I understand the problem - we have exactly the same in our KH. We are moving to JWL and will likely reposition the projector to the right of the platform and reduce the size of the projected image. OnlyM does allow you to modify the size and position of the prohjection for images and videos. Have you tried it? See Settings Margins. It may help if you reduce the size and position top right (or left)

**Comment by gonzo041** [comment]
Yes, I tested the margins when the OnlyM application came out, but it looked too small the letter, which led to the conclusion that the brothers located behind the KH and with vision problems would not read. I will also follow your suggestion using more test time and see if we achieve better results.
As I said before, it's a real pity that you do not have support for the lyrics of SoundBox and play them in OnlyM.
Greetings.

**Comment by blazer2004** [comment]
Projectors are game of angles and distances. You could tilt the projector up ever so slightly, and use the digital zoom to shrink the image, and move the screen forward a couple feet, which would effectively raise the image relative to the audience. Or you could try just simply titling the projector up just a little and see how it does. Or you could give the projector and lyrics a fair shake where they are. The last time we used our projector with a large audience was the AM last year, had both TVs and the center projector going. While the center of the image projected about lecturn high, the songs didn't cause much of a problem.

**Comment by gonzo041** [comment]
Hi Antony,
I did the variation tests in the margins of OnlyM for the reproduction of videos, and I came to the conclusion that it will not be practical.
1) It is displayed too small as I mentioned earlier for the brothers in the back of the KH.
2) Modifying the margins would also affect the size in the reproduction of the other videos for the meeting, and since not all the brothers have the technical capacity to operate, they could not vary from one video to the other. We were advised to be the most practical and simple to ensure the operation of the meeting.
We will see what we can do to solve this problem.
Meanwhile I ask you if you decide later to include support for the reproduction with the lyrics of SoundBox in the APP OnlyM, keep me up to date as that is our solution and probably thousands of KH more.
Thank you very much for your attention and apologize for the inconvenience caused.
Christian greetings

**Comment by TizianoNoto** [comment]
@gonzo041 
> I understand that as of January 2019 SoudBox stops working

Technically speaking, SoundBox will still work but, after the meeting format changes, you won't be able to use the timing function properly and nobody's going to fix it.

How big is your hall? Having more screens could help if the last seats are too far. In a KH in our city the LDC installed three displays, two on the sides of the rostrum and one in the middle-left of the room, fixed to the ceiling.

**Comment by AntonyCorbett** [comment]
@gonzo041 Yes, I'll let you know if there are any further developments.
