### ISSUE TITLE
Funzione Web

### ISSUE THREAD

**Issue by AlainDema** [AntonyCorbett/OnlyM#71]
Salve. Grazie per questa semplice ma efficace applicazione. volevo chiedere se è possibile successivamente implementare la funzione di visualizzazione delle pagine internet (come era presente su Sound Box) con il relativo clone sul computer dell'acustica. Al riguardo del clone sul computer dell'acustica della pagine internet (a differenza di un problema riscontrato su Sound Box) spero che possa essere realizzato con le stesse proporzione del monitor sul podio perché altrimenti la differenza tra i due display crea un effetto in acustica MOLTO FASTIDIOSO per comandare il cursore sulla pagina internet specialmente se la sala è molto lunga.

**Comment by AntonyCorbett** [comment]
@AlainDema Thanks for the feedback. Please see #8
