### ISSUE TITLE
Ability to show websites and PDFs

### ISSUE THREAD

**Issue by AnsNie** [AntonyCorbett/OnlyM#8]
Request of a feature similar to the one that SoundBox has.

**Comment by Blann** [comment]
Could this be done without using an external viewer? PDFs are not well-suited for these applications because they almost always require some zooming, positioning and so on, which sort of defeats the object of having everything happen off-screen.

**Comment by AntonyCorbett** [comment]
@Blann Thanks for yoru question. What do you mean by "without using an external viewer"? All PDFs require some sort of viewer. Please expand a little on your suggestion.

**Comment by Blann** [comment]
I was asking more in hope than expectation really! It depends what the content of the PDF is as to how we handle it really but I’ve always just found displaying them on a second screen very cumbersome, to the point that if we need to actually control it during a presentation I just switch the desktop to Duplicate. Same with websites. If you could do all this sort of stuff on the main monitor, in a kind of ‘Preview’ mode, and then apply it to the media display, that’d be great, but I know that’s not something that’s likely possible.

**Comment by AntonyCorbett** [comment]
@Blann - do you use the "Mirror" function in SoundBox when displaying PDFs and websites? If so, is that what you had in mind?

**Comment by Blann** [comment]
We have done but it’s not most practical for routine use as we use a touchscreen due to limited space. It can be a workable compromise as long as the operator has enough notice but we try to avoid the audience seeing any UI interaction at all if possible as it can be distracting. That’s the main thrust of what I’m thinking here.

**Comment by Ukeret** [comment]
I love the ONLY-M. Easy to use, Drag and drop.

**Comment by Blann** [comment]
That would certainly work, but I’m conscious of not unnecessarily complicating things, both for our operators and for Antony!

Appreciate we’re probably a fringe case using a touch screen. If a SoundBox-style solution works for the majority then that’s fine – we’ll just continue with our PDF converter.

**Comment by jrfig** [comment]
As we move on from Soundbox and start using JW Library. We would like to request enhancing Only M so that It can display pdf files.

**Comment by jrfig** [comment]
Would also like to inquire about enhancing the Bible Text app and the speaker announcement app to be able to display to secondary monitors without Soundbox.

**Comment by AntonyCorbett** [comment]
@jrfig OnlyV is already available for displaying Bible verses.

**Comment by AntonyCorbett** [comment]
@jrfig please raise a separate issue regarding the speaker message app. I suspect it is not widely used, but a new issue would allow others to comment on it. Thanks.

**Comment by jrfig** [comment]
Would it be possible to make the Speaker Messaging app work without Soundbox?

**Comment by AntonyCorbett** [comment]
There is a separate branch named "addedbrowser" on which I am working on browser support using Cef (Chromium).

**Comment by AntonyCorbett** [comment]
Website support in latest pre-release

**Comment by drmeyer** [comment]
Found Chrome completely blocks download of 1.2.0.4.  Was able to download
with Firefox.   On running installation file, the program will not start
when executed.  Cursor spins for 2-3 seconds then screen stays blank.
Program does not show up in Task Manager.   Any reason why?  I will have to
roll back to 1.1.0.25.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/05/18,
10:48:58 AM

**Comment by AntonyCorbett** [comment]
@drmeyer You may also need to check that the MS VC++ 2015 runtime is on your machine. You can download and run the installer from here:

https://www.microsoft.com/en-us/download/details.aspx?id=53840

I have yet to finalise all dependencies.

**Comment by levihaynes** [comment]
Thanks for all your hard work. PDF documents can now be displaying using an internet shortcut. First create the shortcut to something like google. Then edit the shortcut and replace the URL with a web browser path (eg. file:///C:/Users/windows user/Documents/OnlyM/Media/pdf.pdf). This also gives you the option to zoom in through the Chromium PDF plugin.
![capture01](https://user-images.githubusercontent.com/45662504/49589264-dd503d00-f960-11e8-9ebb-0321ec1afbe0.PNG)
![capture02](https://user-images.githubusercontent.com/45662504/49589284-e3deb480-f960-11e8-9727-325b76101ad4.PNG)

**Comment by AntonyCorbett** [comment]
@levihaynes yes, thanks. I will add a custom scheme and support PDFs explicitly soon.

**Comment by AntonyCorbett** [comment]
PDFs now supported using internal http scheme. Please see latest pre-release (1.2.0.8)
Closing this feature request
