### ISSUE TITLE
During Pause stop video display on media monitor

### ISSUE THREAD

**Issue by sewru** [AntonyCorbett/OnlyM#83]
Hi Anthony,

A feature request for a sign language congregation. Sometimes they play videos, but need to pause in between. Is there a way to stop the video display, so that it  switches back to jwlibrary or the signlanguage app easily , as no output is send to the mediamonitor.

Maybe this could be an optional setting

Thanks,

**Comment by AntonyCorbett** [comment]
Hi. Thanks for your feedback. Please would you describe exactly what the requirement is? Tell me what you click and what happens - just as though the software actually works as you want it to.

**Comment by sewru** [comment]
Anthony,
When you click on pause during video. The media monitor is not occupied(as if the video has ended) and jwlibrary comes back up.

Thanks,

**Comment by AntonyCorbett** [comment]
@sewru It seems to me that this is niche requirement and one that has a suitable work-around (alt-tab as described above). I am closing now. Sorry I won't be working on this request but I don't have time to implement all the good ideas! Thanks for your feedback.
