### ISSUE TITLE
Preview, zoom Image

### ISSUE THREAD

**Issue by Fer2P** [AntonyCorbett/OnlyM#88]
Hi Antony! I like that the program is very simple to use. Now, im missing the preview window that allow us to zoom an image before Displaying it. This is useful when there's a single image with multiple scenes in it. Theres any possibility to add this feature?
Thanks!

**Comment by LvDaniel** [comment]
@Fer2P I find it useful as well.

**Comment by vitzter** [comment]
Me too.  I would love to have this feature.

**Comment by MorrieB** [comment]
Ditto. Preview very useful.

**Comment by Adso2004** [comment]
Hello. Yes this feature was great and very useful. If possible to include in OnlyM, that would be amazing. Thanks again for your hard work.

**Comment by AntonyCorbett** [comment]
This is unlikely to be implemented. It's a niche requirement and the focus is on basic functionality. OnlyM is primarily a stop-gap. If JWL adds support for 3rd-party images then any additional work on OnlyM image display will have been futile.

**Comment by Adso2004** [comment]
Thank you for your response. Regards Adam C

**Comment by gonzo041** [comment]
> Es poco probable que esto se implemente. Es un requisito de nicho y el foco está en la funcionalidad básica. OnlyM es principalmente un espacio intermedio. Si JWL agrega soporte para imágenes de terceros, cualquier trabajo adicional en la visualización de imágenes OnlyM habrá sido inútil.

Hi Antony,
For the time that has elapsed and since JWL does not implement support for images, it may now be possible to develop it in ONLYM # 88.
Sorry for the insistence, but it is a very useful tool to see the details of the photographs that the faithful slave presents for each meeting.
Many thanks
Best regards
Sergio
